/*
  Copyright (c) 2019 Arnix Chen All right reserved.
  This is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public
  License as published by the Free Software Foundation; either
  version 3.0 of the License, or (at your option) any later version.
  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.
  You should have received a copy of the GNU General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

  Modified 05-03-2019 by Arnix Chen
*/

#ifndef __SPELL_LIST__
#define __SPELL_LIST__

const spell spellList[] PROGMEM = {
  (const spell PROGMEM) {"1"}, // ㄅ 12
  (const spell PROGMEM) {"q"}, // ㄆ 13
  (const spell PROGMEM) {"a"}, // ㄇ 14
  (const spell PROGMEM) {"z"}, // ㄈ 15
  (const spell PROGMEM) {"2"}, // ㄉ 16
  (const spell PROGMEM) {"w"}, // ㄊ 17
  (const spell PROGMEM) {"s"}, // ㄋ 18
  (const spell PROGMEM) {"x"}, // ㄌ 19
  (const spell PROGMEM) {"e"}, // ㄍ 20
  (const spell PROGMEM) {"d"}, // ㄎ 21
  (const spell PROGMEM) {"c"}, // ㄏ 22
  (const spell PROGMEM) {"r"}, // ㄐ 23
  (const spell PROGMEM) {"f"}, // ㄑ 24
  (const spell PROGMEM) {"v"}, // ㄒ 25
  (const spell PROGMEM) {"5"}, // ㄓ 26
  (const spell PROGMEM) {"t"}, // ㄔ 27
  (const spell PROGMEM) {"g"}, // ㄕ 28
  (const spell PROGMEM) {"b"}, // ㄖ 29
  (const spell PROGMEM) {"y"}, // ㄗ 30
  (const spell PROGMEM) {"h"}, // ㄘ 31
  (const spell PROGMEM) {"n"}, // ㄙ 32
  (const spell PROGMEM) {"u"}, // ㄧ 33
  (const spell PROGMEM) {"j"}, // ㄨ 34
  (const spell PROGMEM) {"m"}, // ㄩ 35
  (const spell PROGMEM) {"8"}, // ㄚ 36
  (const spell PROGMEM) {"i"}, // ㄛ 37
  (const spell PROGMEM) {"k"}, // ㄜ 38
  (const spell PROGMEM) {","}, // ㄝ 39
  (const spell PROGMEM) {"9"}, // ㄞ 40
  (const spell PROGMEM) {"o"}, // ㄟ 41
  (const spell PROGMEM) {"l"}, // ㄠ 42
  (const spell PROGMEM) {"."}, // ㄡ 43
  (const spell PROGMEM) {"0"}, // ㄢ 44
  (const spell PROGMEM) {"p"}, // ㄣ 45
  (const spell PROGMEM) {";"}, // ㄤ 46
  (const spell PROGMEM) {"/"}, // ㄥ 47
  (const spell PROGMEM) {"-"}, // ㄦ 48
  (const spell PROGMEM) {"18"}, // ㄅㄚ 49
  (const spell PROGMEM) {"186"}, // ㄅㄚˊ 50
  (const spell PROGMEM) {"183"}, // ㄅㄚˇ 51
  (const spell PROGMEM) {"184"}, // ㄅㄚˋ 52
  (const spell PROGMEM) {"187"}, // ㄅㄚ˙ 53
  (const spell PROGMEM) {"1i"}, // ㄅㄛ 54
  (const spell PROGMEM) {"1i6"}, // ㄅㄛˊ 55
  (const spell PROGMEM) {"1i3"}, // ㄅㄛˇ 56
  (const spell PROGMEM) {"1i4"}, // ㄅㄛˋ 57
  (const spell PROGMEM) {"1i7"}, // ㄅㄛ˙ 58
  (const spell PROGMEM) {"19"}, // ㄅㄞ 59
  (const spell PROGMEM) {"196"}, // ㄅㄞˊ 60
  (const spell PROGMEM) {"193"}, // ㄅㄞˇ 61
  (const spell PROGMEM) {"194"}, // ㄅㄞˋ 62
  (const spell PROGMEM) {"1o"}, // ㄅㄟ 63
  (const spell PROGMEM) {"1o6"}, // ㄅㄟˊ 64
  (const spell PROGMEM) {"1o3"}, // ㄅㄟˇ 65
  (const spell PROGMEM) {"1o4"}, // ㄅㄟˋ 66
  (const spell PROGMEM) {"1o7"}, // ㄅㄟ˙ 67
  (const spell PROGMEM) {"1l"}, // ㄅㄠ 68
  (const spell PROGMEM) {"1l6"}, // ㄅㄠˊ 69
  (const spell PROGMEM) {"1l3"}, // ㄅㄠˇ 70
  (const spell PROGMEM) {"1l4"}, // ㄅㄠˋ 71
  (const spell PROGMEM) {"1l7"}, // ㄅㄠ˙ 72
  (const spell PROGMEM) {"10"}, // ㄅㄢ 73
  (const spell PROGMEM) {"106"}, // ㄅㄢˊ 74
  (const spell PROGMEM) {"103"}, // ㄅㄢˇ 75
  (const spell PROGMEM) {"104"}, // ㄅㄢˋ 76
  (const spell PROGMEM) {"1p"}, // ㄅㄣ 77
  (const spell PROGMEM) {"1p3"}, // ㄅㄣˇ 78
  (const spell PROGMEM) {"1p4"}, // ㄅㄣˋ 79
  (const spell PROGMEM) {"1;"}, // ㄅㄤ 80
  (const spell PROGMEM) {"1;3"}, // ㄅㄤˇ 81
  (const spell PROGMEM) {"1;4"}, // ㄅㄤˋ 82
  (const spell PROGMEM) {"1/"}, // ㄅㄥ 83
  (const spell PROGMEM) {"1/6"}, // ㄅㄥˊ 84
  (const spell PROGMEM) {"1/3"}, // ㄅㄥˇ 85
  (const spell PROGMEM) {"1/4"}, // ㄅㄥˋ 86
  (const spell PROGMEM) {"1u"}, // ㄅㄧ 87
  (const spell PROGMEM) {"1u6"}, // ㄅㄧˊ 88
  (const spell PROGMEM) {"1u3"}, // ㄅㄧˇ 89
  (const spell PROGMEM) {"1u4"}, // ㄅㄧˋ 90
  (const spell PROGMEM) {"1u7"}, // ㄅㄧ˙ 91
  (const spell PROGMEM) {"1u,"}, // ㄅㄧㄝ 92
  (const spell PROGMEM) {"1u,6"}, // ㄅㄧㄝˊ 93
  (const spell PROGMEM) {"1u,3"}, // ㄅㄧㄝˇ 94
  (const spell PROGMEM) {"1u,4"}, // ㄅㄧㄝˋ 95
  (const spell PROGMEM) {"1ul"}, // ㄅㄧㄠ 96
  (const spell PROGMEM) {"1ul6"}, // ㄅㄧㄠˊ 97
  (const spell PROGMEM) {"1ul3"}, // ㄅㄧㄠˇ 98
  (const spell PROGMEM) {"1ul4"}, // ㄅㄧㄠˋ 99
  (const spell PROGMEM) {"1u0"}, // ㄅㄧㄢ 100
  (const spell PROGMEM) {"1u06"}, // ㄅㄧㄢˊ 101
  (const spell PROGMEM) {"1u03"}, // ㄅㄧㄢˇ 102
  (const spell PROGMEM) {"1u04"}, // ㄅㄧㄢˋ 103
  (const spell PROGMEM) {"1up"}, // ㄅㄧㄣ 104
  (const spell PROGMEM) {"1up6"}, // ㄅㄧㄣˊ 105
  (const spell PROGMEM) {"1up3"}, // ㄅㄧㄣˇ 106
  (const spell PROGMEM) {"1up4"}, // ㄅㄧㄣˋ 107
  (const spell PROGMEM) {"1u/"}, // ㄅㄧㄥ 108
  (const spell PROGMEM) {"1u/6"}, // ㄅㄧㄥˊ 109
  (const spell PROGMEM) {"1u/3"}, // ㄅㄧㄥˇ 110
  (const spell PROGMEM) {"1u/4"}, // ㄅㄧㄥˋ 111
  (const spell PROGMEM) {"1j"}, // ㄅㄨ 112
  (const spell PROGMEM) {"1j6"}, // ㄅㄨˊ 113
  (const spell PROGMEM) {"1j3"}, // ㄅㄨˇ 114
  (const spell PROGMEM) {"1j4"}, // ㄅㄨˋ 115
  (const spell PROGMEM) {"q8"}, // ㄆㄚ 116
  (const spell PROGMEM) {"q86"}, // ㄆㄚˊ 117
  (const spell PROGMEM) {"q84"}, // ㄆㄚˋ 118
  (const spell PROGMEM) {"qi"}, // ㄆㄛ 119
  (const spell PROGMEM) {"qi6"}, // ㄆㄛˊ 120
  (const spell PROGMEM) {"qi3"}, // ㄆㄛˇ 121
  (const spell PROGMEM) {"qi4"}, // ㄆㄛˋ 122
  (const spell PROGMEM) {"q9"}, // ㄆㄞ 123
  (const spell PROGMEM) {"q96"}, // ㄆㄞˊ 124
  (const spell PROGMEM) {"q93"}, // ㄆㄞˇ 125
  (const spell PROGMEM) {"q94"}, // ㄆㄞˋ 126
  (const spell PROGMEM) {"qo"}, // ㄆㄟ 127
  (const spell PROGMEM) {"qo6"}, // ㄆㄟˊ 128
  (const spell PROGMEM) {"qo4"}, // ㄆㄟˋ 129
  (const spell PROGMEM) {"ql"}, // ㄆㄠ 130
  (const spell PROGMEM) {"ql6"}, // ㄆㄠˊ 131
  (const spell PROGMEM) {"ql3"}, // ㄆㄠˇ 132
  (const spell PROGMEM) {"ql4"}, // ㄆㄠˋ 133
  (const spell PROGMEM) {"q."}, // ㄆㄡ 134
  (const spell PROGMEM) {"q.6"}, // ㄆㄡˊ 135
  (const spell PROGMEM) {"q.3"}, // ㄆㄡˇ 136
  (const spell PROGMEM) {"q0"}, // ㄆㄢ 137
  (const spell PROGMEM) {"q06"}, // ㄆㄢˊ 138
  (const spell PROGMEM) {"q04"}, // ㄆㄢˋ 139
  (const spell PROGMEM) {"qp"}, // ㄆㄣ 140
  (const spell PROGMEM) {"qp6"}, // ㄆㄣˊ 141
  (const spell PROGMEM) {"qp4"}, // ㄆㄣˋ 142
  (const spell PROGMEM) {"q;"}, // ㄆㄤ 143
  (const spell PROGMEM) {"q;6"}, // ㄆㄤˊ 144
  (const spell PROGMEM) {"q;3"}, // ㄆㄤˇ 145
  (const spell PROGMEM) {"q;4"}, // ㄆㄤˋ 146
  (const spell PROGMEM) {"q/"}, // ㄆㄥ 147
  (const spell PROGMEM) {"q/6"}, // ㄆㄥˊ 148
  (const spell PROGMEM) {"q/3"}, // ㄆㄥˇ 149
  (const spell PROGMEM) {"q/4"}, // ㄆㄥˋ 150
  (const spell PROGMEM) {"qu"}, // ㄆㄧ 151
  (const spell PROGMEM) {"qu6"}, // ㄆㄧˊ 152
  (const spell PROGMEM) {"qu3"}, // ㄆㄧˇ 153
  (const spell PROGMEM) {"qu4"}, // ㄆㄧˋ 154
  (const spell PROGMEM) {"qu8"}, // ㄆㄧㄚ 155
  (const spell PROGMEM) {"qu,"}, // ㄆㄧㄝ 156
  (const spell PROGMEM) {"qu,6"}, // ㄆㄧㄝˊ 157
  (const spell PROGMEM) {"qu,3"}, // ㄆㄧㄝˇ 158
  (const spell PROGMEM) {"qu,4"}, // ㄆㄧㄝˋ 159
  (const spell PROGMEM) {"qul"}, // ㄆㄧㄠ 160
  (const spell PROGMEM) {"qul6"}, // ㄆㄧㄠˊ 161
  (const spell PROGMEM) {"qul3"}, // ㄆㄧㄠˇ 162
  (const spell PROGMEM) {"qul4"}, // ㄆㄧㄠˋ 163
  (const spell PROGMEM) {"qu0"}, // ㄆㄧㄢ 164
  (const spell PROGMEM) {"qu06"}, // ㄆㄧㄢˊ 165
  (const spell PROGMEM) {"qu03"}, // ㄆㄧㄢˇ 166
  (const spell PROGMEM) {"qu04"}, // ㄆㄧㄢˋ 167
  (const spell PROGMEM) {"qup"}, // ㄆㄧㄣ 168
  (const spell PROGMEM) {"qup6"}, // ㄆㄧㄣˊ 169
  (const spell PROGMEM) {"qup3"}, // ㄆㄧㄣˇ 170
  (const spell PROGMEM) {"qup4"}, // ㄆㄧㄣˋ 171
  (const spell PROGMEM) {"qu/"}, // ㄆㄧㄥ 172
  (const spell PROGMEM) {"qu/6"}, // ㄆㄧㄥˊ 173
  (const spell PROGMEM) {"qj"}, // ㄆㄨ 174
  (const spell PROGMEM) {"qj6"}, // ㄆㄨˊ 175
  (const spell PROGMEM) {"qj3"}, // ㄆㄨˇ 176
  (const spell PROGMEM) {"qj4"}, // ㄆㄨˋ 177
  (const spell PROGMEM) {"a8"}, // ㄇㄚ 178
  (const spell PROGMEM) {"a86"}, // ㄇㄚˊ 179
  (const spell PROGMEM) {"a83"}, // ㄇㄚˇ 180
  (const spell PROGMEM) {"a84"}, // ㄇㄚˋ 181
  (const spell PROGMEM) {"a87"}, // ㄇㄚ˙ 182
  (const spell PROGMEM) {"ai"}, // ㄇㄛ 183
  (const spell PROGMEM) {"ai6"}, // ㄇㄛˊ 184
  (const spell PROGMEM) {"ai3"}, // ㄇㄛˇ 185
  (const spell PROGMEM) {"ai4"}, // ㄇㄛˋ 186
  (const spell PROGMEM) {"ak7"}, // ㄇㄜ˙ 187
  (const spell PROGMEM) {"a96"}, // ㄇㄞˊ 188
  (const spell PROGMEM) {"a93"}, // ㄇㄞˇ 189
  (const spell PROGMEM) {"a94"}, // ㄇㄞˋ 190
  (const spell PROGMEM) {"ao"}, // ㄇㄟ 191
  (const spell PROGMEM) {"ao6"}, // ㄇㄟˊ 192
  (const spell PROGMEM) {"ao3"}, // ㄇㄟˇ 193
  (const spell PROGMEM) {"ao4"}, // ㄇㄟˋ 194
  (const spell PROGMEM) {"ao7"}, // ㄇㄟ˙ 195
  (const spell PROGMEM) {"al"}, // ㄇㄠ 196
  (const spell PROGMEM) {"al6"}, // ㄇㄠˊ 197
  (const spell PROGMEM) {"al3"}, // ㄇㄠˇ 198
  (const spell PROGMEM) {"al4"}, // ㄇㄠˋ 199
  (const spell PROGMEM) {"a."}, // ㄇㄡ 200
  (const spell PROGMEM) {"a.6"}, // ㄇㄡˊ 201
  (const spell PROGMEM) {"a.3"}, // ㄇㄡˇ 202
  (const spell PROGMEM) {"a.4"}, // ㄇㄡˋ 203
  (const spell PROGMEM) {"a0"}, // ㄇㄢ 204
  (const spell PROGMEM) {"a06"}, // ㄇㄢˊ 205
  (const spell PROGMEM) {"a03"}, // ㄇㄢˇ 206
  (const spell PROGMEM) {"a04"}, // ㄇㄢˋ 207
  (const spell PROGMEM) {"ap"}, // ㄇㄣ 208
  (const spell PROGMEM) {"ap6"}, // ㄇㄣˊ 209
  (const spell PROGMEM) {"ap4"}, // ㄇㄣˋ 210
  (const spell PROGMEM) {"ap7"}, // ㄇㄣ˙ 211
  (const spell PROGMEM) {"a;6"}, // ㄇㄤˊ 212
  (const spell PROGMEM) {"a;3"}, // ㄇㄤˇ 213
  (const spell PROGMEM) {"a/"}, // ㄇㄥ 214
  (const spell PROGMEM) {"a/6"}, // ㄇㄥˊ 215
  (const spell PROGMEM) {"a/3"}, // ㄇㄥˇ 216
  (const spell PROGMEM) {"a/4"}, // ㄇㄥˋ 217
  (const spell PROGMEM) {"au"}, // ㄇㄧ 218
  (const spell PROGMEM) {"au6"}, // ㄇㄧˊ 219
  (const spell PROGMEM) {"au3"}, // ㄇㄧˇ 220
  (const spell PROGMEM) {"au4"}, // ㄇㄧˋ 221
  (const spell PROGMEM) {"au,"}, // ㄇㄧㄝ 222
  (const spell PROGMEM) {"au,4"}, // ㄇㄧㄝˋ 223
  (const spell PROGMEM) {"aul"}, // ㄇㄧㄠ 224
  (const spell PROGMEM) {"aul6"}, // ㄇㄧㄠˊ 225
  (const spell PROGMEM) {"aul3"}, // ㄇㄧㄠˇ 226
  (const spell PROGMEM) {"aul4"}, // ㄇㄧㄠˋ 227
  (const spell PROGMEM) {"au.4"}, // ㄇㄧㄡˋ 228
  (const spell PROGMEM) {"au06"}, // ㄇㄧㄢˊ 229
  (const spell PROGMEM) {"au03"}, // ㄇㄧㄢˇ 230
  (const spell PROGMEM) {"au04"}, // ㄇㄧㄢˋ 231
  (const spell PROGMEM) {"aup6"}, // ㄇㄧㄣˊ 232
  (const spell PROGMEM) {"aup3"}, // ㄇㄧㄣˇ 233
  (const spell PROGMEM) {"au/6"}, // ㄇㄧㄥˊ 234
  (const spell PROGMEM) {"au/3"}, // ㄇㄧㄥˇ 235
  (const spell PROGMEM) {"au/4"}, // ㄇㄧㄥˋ 236
  (const spell PROGMEM) {"aj6"}, // ㄇㄨˊ 237
  (const spell PROGMEM) {"aj3"}, // ㄇㄨˇ 238
  (const spell PROGMEM) {"aj4"}, // ㄇㄨˋ 239
  (const spell PROGMEM) {"z8"}, // ㄈㄚ 240
  (const spell PROGMEM) {"z86"}, // ㄈㄚˊ 241
  (const spell PROGMEM) {"z83"}, // ㄈㄚˇ 242
  (const spell PROGMEM) {"z84"}, // ㄈㄚˋ 243
  (const spell PROGMEM) {"zi6"}, // ㄈㄛˊ 244
  (const spell PROGMEM) {"zi4"}, // ㄈㄛˋ 245
  (const spell PROGMEM) {"zo"}, // ㄈㄟ 246
  (const spell PROGMEM) {"zo6"}, // ㄈㄟˊ 247
  (const spell PROGMEM) {"zo3"}, // ㄈㄟˇ 248
  (const spell PROGMEM) {"zo4"}, // ㄈㄟˋ 249
  (const spell PROGMEM) {"z.6"}, // ㄈㄡˊ 250
  (const spell PROGMEM) {"z.3"}, // ㄈㄡˇ 251
  (const spell PROGMEM) {"z0"}, // ㄈㄢ 252
  (const spell PROGMEM) {"z06"}, // ㄈㄢˊ 253
  (const spell PROGMEM) {"z03"}, // ㄈㄢˇ 254
  (const spell PROGMEM) {"z04"}, // ㄈㄢˋ 255
  (const spell PROGMEM) {"zp"}, // ㄈㄣ 256
  (const spell PROGMEM) {"zp6"}, // ㄈㄣˊ 257
  (const spell PROGMEM) {"zp3"}, // ㄈㄣˇ 258
  (const spell PROGMEM) {"zp4"}, // ㄈㄣˋ 259
  (const spell PROGMEM) {"z;"}, // ㄈㄤ 260
  (const spell PROGMEM) {"z;6"}, // ㄈㄤˊ 261
  (const spell PROGMEM) {"z;3"}, // ㄈㄤˇ 262
  (const spell PROGMEM) {"z;4"}, // ㄈㄤˋ 263
  (const spell PROGMEM) {"z/"}, // ㄈㄥ 264
  (const spell PROGMEM) {"z/6"}, // ㄈㄥˊ 265
  (const spell PROGMEM) {"z/3"}, // ㄈㄥˇ 266
  (const spell PROGMEM) {"z/4"}, // ㄈㄥˋ 267
  (const spell PROGMEM) {"zj"}, // ㄈㄨ 268
  (const spell PROGMEM) {"zj6"}, // ㄈㄨˊ 269
  (const spell PROGMEM) {"zj3"}, // ㄈㄨˇ 270
  (const spell PROGMEM) {"zj4"}, // ㄈㄨˋ 271
  (const spell PROGMEM) {"28"}, // ㄉㄚ 272
  (const spell PROGMEM) {"286"}, // ㄉㄚˊ 273
  (const spell PROGMEM) {"283"}, // ㄉㄚˇ 274
  (const spell PROGMEM) {"284"}, // ㄉㄚˋ 275
  (const spell PROGMEM) {"2k6"}, // ㄉㄜˊ 276
  (const spell PROGMEM) {"2k7"}, // ㄉㄜ˙ 277
  (const spell PROGMEM) {"29"}, // ㄉㄞ 278
  (const spell PROGMEM) {"293"}, // ㄉㄞˇ 279
  (const spell PROGMEM) {"294"}, // ㄉㄞˋ 280
  (const spell PROGMEM) {"2o6"}, // ㄉㄟˊ 281
  (const spell PROGMEM) {"2o3"}, // ㄉㄟˇ 282
  (const spell PROGMEM) {"2l"}, // ㄉㄠ 283
  (const spell PROGMEM) {"2l6"}, // ㄉㄠˊ 284
  (const spell PROGMEM) {"2l3"}, // ㄉㄠˇ 285
  (const spell PROGMEM) {"2l4"}, // ㄉㄠˋ 286
  (const spell PROGMEM) {"2."}, // ㄉㄡ 287
  (const spell PROGMEM) {"2.6"}, // ㄉㄡˊ 288
  (const spell PROGMEM) {"2.3"}, // ㄉㄡˇ 289
  (const spell PROGMEM) {"2.4"}, // ㄉㄡˋ 290
  (const spell PROGMEM) {"20"}, // ㄉㄢ 291
  (const spell PROGMEM) {"206"}, // ㄉㄢˊ 292
  (const spell PROGMEM) {"203"}, // ㄉㄢˇ 293
  (const spell PROGMEM) {"204"}, // ㄉㄢˋ 294
  (const spell PROGMEM) {"2;"}, // ㄉㄤ 295
  (const spell PROGMEM) {"2;6"}, // ㄉㄤˊ 296
  (const spell PROGMEM) {"2;3"}, // ㄉㄤˇ 297
  (const spell PROGMEM) {"2;4"}, // ㄉㄤˋ 298
  (const spell PROGMEM) {"2/"}, // ㄉㄥ 299
  (const spell PROGMEM) {"2/6"}, // ㄉㄥˊ 300
  (const spell PROGMEM) {"2/3"}, // ㄉㄥˇ 301
  (const spell PROGMEM) {"2/4"}, // ㄉㄥˋ 302
  (const spell PROGMEM) {"2u"}, // ㄉㄧ 303
  (const spell PROGMEM) {"2u6"}, // ㄉㄧˊ 304
  (const spell PROGMEM) {"2u3"}, // ㄉㄧˇ 305
  (const spell PROGMEM) {"2u4"}, // ㄉㄧˋ 306
  (const spell PROGMEM) {"2u7"}, // ㄉㄧ˙ 307
  (const spell PROGMEM) {"2u,"}, // ㄉㄧㄝ 308
  (const spell PROGMEM) {"2u,6"}, // ㄉㄧㄝˊ 309
  (const spell PROGMEM) {"2u,7"}, // ㄉㄧㄝ˙ 310
  (const spell PROGMEM) {"2ul"}, // ㄉㄧㄠ 311
  (const spell PROGMEM) {"2ul3"}, // ㄉㄧㄠˇ 312
  (const spell PROGMEM) {"2ul4"}, // ㄉㄧㄠˋ 313
  (const spell PROGMEM) {"2u."}, // ㄉㄧㄡ 314
  (const spell PROGMEM) {"2u0"}, // ㄉㄧㄢ 315
  (const spell PROGMEM) {"2u06"}, // ㄉㄧㄢˊ 316
  (const spell PROGMEM) {"2u03"}, // ㄉㄧㄢˇ 317
  (const spell PROGMEM) {"2u04"}, // ㄉㄧㄢˋ 318
  (const spell PROGMEM) {"2u;"}, // ㄉㄧㄤ 319
  (const spell PROGMEM) {"2u/"}, // ㄉㄧㄥ 320
  (const spell PROGMEM) {"2u/6"}, // ㄉㄧㄥˊ 321
  (const spell PROGMEM) {"2u/3"}, // ㄉㄧㄥˇ 322
  (const spell PROGMEM) {"2u/4"}, // ㄉㄧㄥˋ 323
  (const spell PROGMEM) {"2j"}, // ㄉㄨ 324
  (const spell PROGMEM) {"2j6"}, // ㄉㄨˊ 325
  (const spell PROGMEM) {"2j3"}, // ㄉㄨˇ 326
  (const spell PROGMEM) {"2j4"}, // ㄉㄨˋ 327
  (const spell PROGMEM) {"2ji"}, // ㄉㄨㄛ 328
  (const spell PROGMEM) {"2ji6"}, // ㄉㄨㄛˊ 329
  (const spell PROGMEM) {"2ji3"}, // ㄉㄨㄛˇ 330
  (const spell PROGMEM) {"2ji4"}, // ㄉㄨㄛˋ 331
  (const spell PROGMEM) {"2ji7"}, // ㄉㄨㄛ˙ 332
  (const spell PROGMEM) {"2jo"}, // ㄉㄨㄟ 333
  (const spell PROGMEM) {"2jo4"}, // ㄉㄨㄟˋ 334
  (const spell PROGMEM) {"2j0"}, // ㄉㄨㄢ 335
  (const spell PROGMEM) {"2j06"}, // ㄉㄨㄢˊ 336
  (const spell PROGMEM) {"2j03"}, // ㄉㄨㄢˇ 337
  (const spell PROGMEM) {"2j04"}, // ㄉㄨㄢˋ 338
  (const spell PROGMEM) {"2jp"}, // ㄉㄨㄣ 339
  (const spell PROGMEM) {"2jp3"}, // ㄉㄨㄣˇ 340
  (const spell PROGMEM) {"2jp4"}, // ㄉㄨㄣˋ 341
  (const spell PROGMEM) {"2j/"}, // ㄉㄨㄥ 342
  (const spell PROGMEM) {"2j/3"}, // ㄉㄨㄥˇ 343
  (const spell PROGMEM) {"2j/4"}, // ㄉㄨㄥˋ 344
  (const spell PROGMEM) {"w8"}, // ㄊㄚ 345
  (const spell PROGMEM) {"w86"}, // ㄊㄚˊ 346
  (const spell PROGMEM) {"w83"}, // ㄊㄚˇ 347
  (const spell PROGMEM) {"w84"}, // ㄊㄚˋ 348
  (const spell PROGMEM) {"wk"}, // ㄊㄜ 349
  (const spell PROGMEM) {"wk4"}, // ㄊㄜˋ 350
  (const spell PROGMEM) {"w9"}, // ㄊㄞ 351
  (const spell PROGMEM) {"w96"}, // ㄊㄞˊ 352
  (const spell PROGMEM) {"w94"}, // ㄊㄞˋ 353
  (const spell PROGMEM) {"wl"}, // ㄊㄠ 354
  (const spell PROGMEM) {"wl6"}, // ㄊㄠˊ 355
  (const spell PROGMEM) {"wl3"}, // ㄊㄠˇ 356
  (const spell PROGMEM) {"wl4"}, // ㄊㄠˋ 357
  (const spell PROGMEM) {"wl7"}, // ㄊㄠ˙ 358
  (const spell PROGMEM) {"w."}, // ㄊㄡ 359
  (const spell PROGMEM) {"w.6"}, // ㄊㄡˊ 360
  (const spell PROGMEM) {"w.3"}, // ㄊㄡˇ 361
  (const spell PROGMEM) {"w.4"}, // ㄊㄡˋ 362
  (const spell PROGMEM) {"w.7"}, // ㄊㄡ˙ 363
  (const spell PROGMEM) {"w0"}, // ㄊㄢ 364
  (const spell PROGMEM) {"w06"}, // ㄊㄢˊ 365
  (const spell PROGMEM) {"w03"}, // ㄊㄢˇ 366
  (const spell PROGMEM) {"w04"}, // ㄊㄢˋ 367
  (const spell PROGMEM) {"w;"}, // ㄊㄤ 368
  (const spell PROGMEM) {"w;6"}, // ㄊㄤˊ 369
  (const spell PROGMEM) {"w;3"}, // ㄊㄤˇ 370
  (const spell PROGMEM) {"w;4"}, // ㄊㄤˋ 371
  (const spell PROGMEM) {"w/"}, // ㄊㄥ 372
  (const spell PROGMEM) {"w/6"}, // ㄊㄥˊ 373
  (const spell PROGMEM) {"wu"}, // ㄊㄧ 374
  (const spell PROGMEM) {"wu6"}, // ㄊㄧˊ 375
  (const spell PROGMEM) {"wu3"}, // ㄊㄧˇ 376
  (const spell PROGMEM) {"wu4"}, // ㄊㄧˋ 377
  (const spell PROGMEM) {"wu,"}, // ㄊㄧㄝ 378
  (const spell PROGMEM) {"wu,6"}, // ㄊㄧㄝˊ 379
  (const spell PROGMEM) {"wu,3"}, // ㄊㄧㄝˇ 380
  (const spell PROGMEM) {"wul"}, // ㄊㄧㄠ 381
  (const spell PROGMEM) {"wul6"}, // ㄊㄧㄠˊ 382
  (const spell PROGMEM) {"wul3"}, // ㄊㄧㄠˇ 383
  (const spell PROGMEM) {"wul4"}, // ㄊㄧㄠˋ 384
  (const spell PROGMEM) {"wu0"}, // ㄊㄧㄢ 385
  (const spell PROGMEM) {"wu06"}, // ㄊㄧㄢˊ 386
  (const spell PROGMEM) {"wu03"}, // ㄊㄧㄢˇ 387
  (const spell PROGMEM) {"wu04"}, // ㄊㄧㄢˋ 388
  (const spell PROGMEM) {"wu/"}, // ㄊㄧㄥ 389
  (const spell PROGMEM) {"wu/6"}, // ㄊㄧㄥˊ 390
  (const spell PROGMEM) {"wu/3"}, // ㄊㄧㄥˇ 391
  (const spell PROGMEM) {"wu/4"}, // ㄊㄧㄥˋ 392
  (const spell PROGMEM) {"wj"}, // ㄊㄨ 393
  (const spell PROGMEM) {"wj6"}, // ㄊㄨˊ 394
  (const spell PROGMEM) {"wj3"}, // ㄊㄨˇ 395
  (const spell PROGMEM) {"wj4"}, // ㄊㄨˋ 396
  (const spell PROGMEM) {"wji"}, // ㄊㄨㄛ 397
  (const spell PROGMEM) {"wji6"}, // ㄊㄨㄛˊ 398
  (const spell PROGMEM) {"wji3"}, // ㄊㄨㄛˇ 399
  (const spell PROGMEM) {"wji4"}, // ㄊㄨㄛˋ 400
  (const spell PROGMEM) {"wjo"}, // ㄊㄨㄟ 401
  (const spell PROGMEM) {"wjo6"}, // ㄊㄨㄟˊ 402
  (const spell PROGMEM) {"wjo3"}, // ㄊㄨㄟˇ 403
  (const spell PROGMEM) {"wjo4"}, // ㄊㄨㄟˋ 404
  (const spell PROGMEM) {"wj0"}, // ㄊㄨㄢ 405
  (const spell PROGMEM) {"wj06"}, // ㄊㄨㄢˊ 406
  (const spell PROGMEM) {"wj03"}, // ㄊㄨㄢˇ 407
  (const spell PROGMEM) {"wj04"}, // ㄊㄨㄢˋ 408
  (const spell PROGMEM) {"wjp"}, // ㄊㄨㄣ 409
  (const spell PROGMEM) {"wjp6"}, // ㄊㄨㄣˊ 410
  (const spell PROGMEM) {"wjp4"}, // ㄊㄨㄣˋ 411
  (const spell PROGMEM) {"wj/"}, // ㄊㄨㄥ 412
  (const spell PROGMEM) {"wj/6"}, // ㄊㄨㄥˊ 413
  (const spell PROGMEM) {"wj/3"}, // ㄊㄨㄥˇ 414
  (const spell PROGMEM) {"wj/4"}, // ㄊㄨㄥˋ 415
  (const spell PROGMEM) {"s8"}, // ㄋㄚ 416
  (const spell PROGMEM) {"s86"}, // ㄋㄚˊ 417
  (const spell PROGMEM) {"s83"}, // ㄋㄚˇ 418
  (const spell PROGMEM) {"s84"}, // ㄋㄚˋ 419
  (const spell PROGMEM) {"s87"}, // ㄋㄚ˙ 420
  (const spell PROGMEM) {"sk"}, // ㄋㄜ 421
  (const spell PROGMEM) {"sk7"}, // ㄋㄜ˙ 422
  (const spell PROGMEM) {"s93"}, // ㄋㄞˇ 423
  (const spell PROGMEM) {"s94"}, // ㄋㄞˋ 424
  (const spell PROGMEM) {"s97"}, // ㄋㄞ˙ 425
  (const spell PROGMEM) {"so3"}, // ㄋㄟˇ 426
  (const spell PROGMEM) {"so4"}, // ㄋㄟˋ 427
  (const spell PROGMEM) {"sl"}, // ㄋㄠ 428
  (const spell PROGMEM) {"sl6"}, // ㄋㄠˊ 429
  (const spell PROGMEM) {"sl3"}, // ㄋㄠˇ 430
  (const spell PROGMEM) {"sl4"}, // ㄋㄠˋ 431
  (const spell PROGMEM) {"s.4"}, // ㄋㄡˋ 432
  (const spell PROGMEM) {"s0"}, // ㄋㄢ 433
  (const spell PROGMEM) {"s06"}, // ㄋㄢˊ 434
  (const spell PROGMEM) {"s03"}, // ㄋㄢˇ 435
  (const spell PROGMEM) {"s04"}, // ㄋㄢˋ 436
  (const spell PROGMEM) {"sp4"}, // ㄋㄣˋ 437
  (const spell PROGMEM) {"s;6"}, // ㄋㄤˊ 438
  (const spell PROGMEM) {"s;3"}, // ㄋㄤˇ 439
  (const spell PROGMEM) {"s;4"}, // ㄋㄤˋ 440
  (const spell PROGMEM) {"s;7"}, // ㄋㄤ˙ 441
  (const spell PROGMEM) {"s/6"}, // ㄋㄥˊ 442
  (const spell PROGMEM) {"su6"}, // ㄋㄧˊ 443
  (const spell PROGMEM) {"su3"}, // ㄋㄧˇ 444
  (const spell PROGMEM) {"su4"}, // ㄋㄧˋ 445
  (const spell PROGMEM) {"su,"}, // ㄋㄧㄝ 446
  (const spell PROGMEM) {"su,6"}, // ㄋㄧㄝˊ 447
  (const spell PROGMEM) {"su,4"}, // ㄋㄧㄝˋ 448
  (const spell PROGMEM) {"sul3"}, // ㄋㄧㄠˇ 449
  (const spell PROGMEM) {"sul4"}, // ㄋㄧㄠˋ 450
  (const spell PROGMEM) {"su."}, // ㄋㄧㄡ 451
  (const spell PROGMEM) {"su.6"}, // ㄋㄧㄡˊ 452
  (const spell PROGMEM) {"su.3"}, // ㄋㄧㄡˇ 453
  (const spell PROGMEM) {"su.4"}, // ㄋㄧㄡˋ 454
  (const spell PROGMEM) {"su0"}, // ㄋㄧㄢ 455
  (const spell PROGMEM) {"su06"}, // ㄋㄧㄢˊ 456
  (const spell PROGMEM) {"su03"}, // ㄋㄧㄢˇ 457
  (const spell PROGMEM) {"su04"}, // ㄋㄧㄢˋ 458
  (const spell PROGMEM) {"sup6"}, // ㄋㄧㄣˊ 459
  (const spell PROGMEM) {"su;6"}, // ㄋㄧㄤˊ 460
  (const spell PROGMEM) {"su;4"}, // ㄋㄧㄤˋ 461
  (const spell PROGMEM) {"su;7"}, // ㄋㄧㄤ˙ 462
  (const spell PROGMEM) {"su/6"}, // ㄋㄧㄥˊ 463
  (const spell PROGMEM) {"su/3"}, // ㄋㄧㄥˇ 464
  (const spell PROGMEM) {"su/4"}, // ㄋㄧㄥˋ 465
  (const spell PROGMEM) {"sj6"}, // ㄋㄨˊ 466
  (const spell PROGMEM) {"sj3"}, // ㄋㄨˇ 467
  (const spell PROGMEM) {"sj4"}, // ㄋㄨˋ 468
  (const spell PROGMEM) {"sji6"}, // ㄋㄨㄛˊ 469
  (const spell PROGMEM) {"sji3"}, // ㄋㄨㄛˇ 470
  (const spell PROGMEM) {"sji4"}, // ㄋㄨㄛˋ 471
  (const spell PROGMEM) {"sj03"}, // ㄋㄨㄢˇ 472
  (const spell PROGMEM) {"sj/6"}, // ㄋㄨㄥˊ 473
  (const spell PROGMEM) {"sj/4"}, // ㄋㄨㄥˋ 474
  (const spell PROGMEM) {"sj/7"}, // ㄋㄨㄥ˙ 475
  (const spell PROGMEM) {"sm3"}, // ㄋㄩˇ 476
  (const spell PROGMEM) {"sm4"}, // ㄋㄩˋ 477
  (const spell PROGMEM) {"sm,4"}, // ㄋㄩㄝˋ 478
  (const spell PROGMEM) {"x8"}, // ㄌㄚ 479
  (const spell PROGMEM) {"x86"}, // ㄌㄚˊ 480
  (const spell PROGMEM) {"x83"}, // ㄌㄚˇ 481
  (const spell PROGMEM) {"x84"}, // ㄌㄚˋ 482
  (const spell PROGMEM) {"x87"}, // ㄌㄚ˙ 483
  (const spell PROGMEM) {"xk"}, // ㄌㄜ 484
  (const spell PROGMEM) {"xk4"}, // ㄌㄜˋ 485
  (const spell PROGMEM) {"xk7"}, // ㄌㄜ˙ 486
  (const spell PROGMEM) {"x96"}, // ㄌㄞˊ 487
  (const spell PROGMEM) {"x94"}, // ㄌㄞˋ 488
  (const spell PROGMEM) {"xo"}, // ㄌㄟ 489
  (const spell PROGMEM) {"xo6"}, // ㄌㄟˊ 490
  (const spell PROGMEM) {"xo3"}, // ㄌㄟˇ 491
  (const spell PROGMEM) {"xo4"}, // ㄌㄟˋ 492
  (const spell PROGMEM) {"xl"}, // ㄌㄠ 493
  (const spell PROGMEM) {"xl6"}, // ㄌㄠˊ 494
  (const spell PROGMEM) {"xl3"}, // ㄌㄠˇ 495
  (const spell PROGMEM) {"xl4"}, // ㄌㄠˋ 496
  (const spell PROGMEM) {"xl7"}, // ㄌㄠ˙ 497
  (const spell PROGMEM) {"x."}, // ㄌㄡ 498
  (const spell PROGMEM) {"x.6"}, // ㄌㄡˊ 499
  (const spell PROGMEM) {"x.3"}, // ㄌㄡˇ 500
  (const spell PROGMEM) {"x.4"}, // ㄌㄡˋ 501
  (const spell PROGMEM) {"x.7"}, // ㄌㄡ˙ 502
  (const spell PROGMEM) {"x06"}, // ㄌㄢˊ 503
  (const spell PROGMEM) {"x03"}, // ㄌㄢˇ 504
  (const spell PROGMEM) {"x04"}, // ㄌㄢˋ 505
  (const spell PROGMEM) {"x;"}, // ㄌㄤ 506
  (const spell PROGMEM) {"x;6"}, // ㄌㄤˊ 507
  (const spell PROGMEM) {"x;3"}, // ㄌㄤˇ 508
  (const spell PROGMEM) {"x;4"}, // ㄌㄤˋ 509
  (const spell PROGMEM) {"x/"}, // ㄌㄥ 510
  (const spell PROGMEM) {"x/6"}, // ㄌㄥˊ 511
  (const spell PROGMEM) {"x/3"}, // ㄌㄥˇ 512
  (const spell PROGMEM) {"x/4"}, // ㄌㄥˋ 513
  (const spell PROGMEM) {"xu"}, // ㄌㄧ 514
  (const spell PROGMEM) {"xu6"}, // ㄌㄧˊ 515
  (const spell PROGMEM) {"xu3"}, // ㄌㄧˇ 516
  (const spell PROGMEM) {"xu4"}, // ㄌㄧˋ 517
  (const spell PROGMEM) {"xu7"}, // ㄌㄧ˙ 518
  (const spell PROGMEM) {"xu83"}, // ㄌㄧㄚˇ 519
  (const spell PROGMEM) {"xu,"}, // ㄌㄧㄝ 520
  (const spell PROGMEM) {"xu,6"}, // ㄌㄧㄝˊ 521
  (const spell PROGMEM) {"xu,3"}, // ㄌㄧㄝˇ 522
  (const spell PROGMEM) {"xu,4"}, // ㄌㄧㄝˋ 523
  (const spell PROGMEM) {"xul"}, // ㄌㄧㄠ 524
  (const spell PROGMEM) {"xul6"}, // ㄌㄧㄠˊ 525
  (const spell PROGMEM) {"xul3"}, // ㄌㄧㄠˇ 526
  (const spell PROGMEM) {"xul4"}, // ㄌㄧㄠˋ 527
  (const spell PROGMEM) {"xu."}, // ㄌㄧㄡ 528
  (const spell PROGMEM) {"xu.6"}, // ㄌㄧㄡˊ 529
  (const spell PROGMEM) {"xu.3"}, // ㄌㄧㄡˇ 530
  (const spell PROGMEM) {"xu.4"}, // ㄌㄧㄡˋ 531
  (const spell PROGMEM) {"xu0"}, // ㄌㄧㄢ 532
  (const spell PROGMEM) {"xu06"}, // ㄌㄧㄢˊ 533
  (const spell PROGMEM) {"xu03"}, // ㄌㄧㄢˇ 534
  (const spell PROGMEM) {"xu04"}, // ㄌㄧㄢˋ 535
  (const spell PROGMEM) {"xup6"}, // ㄌㄧㄣˊ 536
  (const spell PROGMEM) {"xup3"}, // ㄌㄧㄣˇ 537
  (const spell PROGMEM) {"xup4"}, // ㄌㄧㄣˋ 538
  (const spell PROGMEM) {"xu;6"}, // ㄌㄧㄤˊ 539
  (const spell PROGMEM) {"xu;3"}, // ㄌㄧㄤˇ 540
  (const spell PROGMEM) {"xu;4"}, // ㄌㄧㄤˋ 541
  (const spell PROGMEM) {"xu/"}, // ㄌㄧㄥ 542
  (const spell PROGMEM) {"xu/6"}, // ㄌㄧㄥˊ 543
  (const spell PROGMEM) {"xu/3"}, // ㄌㄧㄥˇ 544
  (const spell PROGMEM) {"xu/4"}, // ㄌㄧㄥˋ 545
  (const spell PROGMEM) {"xj"}, // ㄌㄨ 546
  (const spell PROGMEM) {"xj6"}, // ㄌㄨˊ 547
  (const spell PROGMEM) {"xj3"}, // ㄌㄨˇ 548
  (const spell PROGMEM) {"xj4"}, // ㄌㄨˋ 549
  (const spell PROGMEM) {"xj7"}, // ㄌㄨ˙ 550
  (const spell PROGMEM) {"xji"}, // ㄌㄨㄛ 551
  (const spell PROGMEM) {"xji6"}, // ㄌㄨㄛˊ 552
  (const spell PROGMEM) {"xji3"}, // ㄌㄨㄛˇ 553
  (const spell PROGMEM) {"xji4"}, // ㄌㄨㄛˋ 554
  (const spell PROGMEM) {"xj06"}, // ㄌㄨㄢˊ 555
  (const spell PROGMEM) {"xj03"}, // ㄌㄨㄢˇ 556
  (const spell PROGMEM) {"xj04"}, // ㄌㄨㄢˋ 557
  (const spell PROGMEM) {"xjp"}, // ㄌㄨㄣ 558
  (const spell PROGMEM) {"xjp6"}, // ㄌㄨㄣˊ 559
  (const spell PROGMEM) {"xjp4"}, // ㄌㄨㄣˋ 560
  (const spell PROGMEM) {"xj/6"}, // ㄌㄨㄥˊ 561
  (const spell PROGMEM) {"xj/3"}, // ㄌㄨㄥˇ 562
  (const spell PROGMEM) {"xj/4"}, // ㄌㄨㄥˋ 563
  (const spell PROGMEM) {"xm6"}, // ㄌㄩˊ 564
  (const spell PROGMEM) {"xm3"}, // ㄌㄩˇ 565
  (const spell PROGMEM) {"xm4"}, // ㄌㄩˋ 566
  (const spell PROGMEM) {"xm,4"}, // ㄌㄩㄝˋ 567
  (const spell PROGMEM) {"xm06"}, // ㄌㄩㄢˊ 568
  (const spell PROGMEM) {"xm03"}, // ㄌㄩㄢˇ 569
  (const spell PROGMEM) {"e8"}, // ㄍㄚ 570
  (const spell PROGMEM) {"e86"}, // ㄍㄚˊ 571
  (const spell PROGMEM) {"e83"}, // ㄍㄚˇ 572
  (const spell PROGMEM) {"e84"}, // ㄍㄚˋ 573
  (const spell PROGMEM) {"e87"}, // ㄍㄚ˙ 574
  (const spell PROGMEM) {"ek"}, // ㄍㄜ 575
  (const spell PROGMEM) {"ek6"}, // ㄍㄜˊ 576
  (const spell PROGMEM) {"ek3"}, // ㄍㄜˇ 577
  (const spell PROGMEM) {"ek4"}, // ㄍㄜˋ 578
  (const spell PROGMEM) {"ek7"}, // ㄍㄜ˙ 579
  (const spell PROGMEM) {"e9"}, // ㄍㄞ 580
  (const spell PROGMEM) {"e96"}, // ㄍㄞˊ 581
  (const spell PROGMEM) {"e93"}, // ㄍㄞˇ 582
  (const spell PROGMEM) {"e94"}, // ㄍㄞˋ 583
  (const spell PROGMEM) {"eo6"}, // ㄍㄟˊ 584
  (const spell PROGMEM) {"eo3"}, // ㄍㄟˇ 585
  (const spell PROGMEM) {"el"}, // ㄍㄠ 586
  (const spell PROGMEM) {"el6"}, // ㄍㄠˊ 587
  (const spell PROGMEM) {"el3"}, // ㄍㄠˇ 588
  (const spell PROGMEM) {"el4"}, // ㄍㄠˋ 589
  (const spell PROGMEM) {"e."}, // ㄍㄡ 590
  (const spell PROGMEM) {"e.6"}, // ㄍㄡˊ 591
  (const spell PROGMEM) {"e.3"}, // ㄍㄡˇ 592
  (const spell PROGMEM) {"e.4"}, // ㄍㄡˋ 593
  (const spell PROGMEM) {"e.7"}, // ㄍㄡ˙ 594
  (const spell PROGMEM) {"e0"}, // ㄍㄢ 595
  (const spell PROGMEM) {"e06"}, // ㄍㄢˊ 596
  (const spell PROGMEM) {"e03"}, // ㄍㄢˇ 597
  (const spell PROGMEM) {"e04"}, // ㄍㄢˋ 598
  (const spell PROGMEM) {"ep"}, // ㄍㄣ 599
  (const spell PROGMEM) {"ep6"}, // ㄍㄣˊ 600
  (const spell PROGMEM) {"ep3"}, // ㄍㄣˇ 601
  (const spell PROGMEM) {"ep4"}, // ㄍㄣˋ 602
  (const spell PROGMEM) {"e;"}, // ㄍㄤ 603
  (const spell PROGMEM) {"e;6"}, // ㄍㄤˊ 604
  (const spell PROGMEM) {"e;3"}, // ㄍㄤˇ 605
  (const spell PROGMEM) {"e;4"}, // ㄍㄤˋ 606
  (const spell PROGMEM) {"e/"}, // ㄍㄥ 607
  (const spell PROGMEM) {"e/6"}, // ㄍㄥˊ 608
  (const spell PROGMEM) {"e/3"}, // ㄍㄥˇ 609
  (const spell PROGMEM) {"e/4"}, // ㄍㄥˋ 610
  (const spell PROGMEM) {"euj4"}, // ㄍㄧㄨˋ 611
  (const spell PROGMEM) {"eup"}, // ㄍㄧㄣ 612
  (const spell PROGMEM) {"ej"}, // ㄍㄨ 613
  (const spell PROGMEM) {"ej6"}, // ㄍㄨˊ 614
  (const spell PROGMEM) {"ej3"}, // ㄍㄨˇ 615
  (const spell PROGMEM) {"ej4"}, // ㄍㄨˋ 616
  (const spell PROGMEM) {"ej8"}, // ㄍㄨㄚ 617
  (const spell PROGMEM) {"ej86"}, // ㄍㄨㄚˊ 618
  (const spell PROGMEM) {"ej83"}, // ㄍㄨㄚˇ 619
  (const spell PROGMEM) {"ej84"}, // ㄍㄨㄚˋ 620
  (const spell PROGMEM) {"eji"}, // ㄍㄨㄛ 621
  (const spell PROGMEM) {"eji6"}, // ㄍㄨㄛˊ 622
  (const spell PROGMEM) {"eji3"}, // ㄍㄨㄛˇ 623
  (const spell PROGMEM) {"eji4"}, // ㄍㄨㄛˋ 624
  (const spell PROGMEM) {"eji7"}, // ㄍㄨㄛ˙ 625
  (const spell PROGMEM) {"ej9"}, // ㄍㄨㄞ 626
  (const spell PROGMEM) {"ej96"}, // ㄍㄨㄞˊ 627
  (const spell PROGMEM) {"ej93"}, // ㄍㄨㄞˇ 628
  (const spell PROGMEM) {"ej94"}, // ㄍㄨㄞˋ 629
  (const spell PROGMEM) {"ejo"}, // ㄍㄨㄟ 630
  (const spell PROGMEM) {"ejo6"}, // ㄍㄨㄟˊ 631
  (const spell PROGMEM) {"ejo3"}, // ㄍㄨㄟˇ 632
  (const spell PROGMEM) {"ejo4"}, // ㄍㄨㄟˋ 633
  (const spell PROGMEM) {"ej0"}, // ㄍㄨㄢ 634
  (const spell PROGMEM) {"ej06"}, // ㄍㄨㄢˊ 635
  (const spell PROGMEM) {"ej03"}, // ㄍㄨㄢˇ 636
  (const spell PROGMEM) {"ej04"}, // ㄍㄨㄢˋ 637
  (const spell PROGMEM) {"ejp6"}, // ㄍㄨㄣˊ 638
  (const spell PROGMEM) {"ejp3"}, // ㄍㄨㄣˇ 639
  (const spell PROGMEM) {"ejp4"}, // ㄍㄨㄣˋ 640
  (const spell PROGMEM) {"ej;"}, // ㄍㄨㄤ 641
  (const spell PROGMEM) {"ej;6"}, // ㄍㄨㄤˊ 642
  (const spell PROGMEM) {"ej;3"}, // ㄍㄨㄤˇ 643
  (const spell PROGMEM) {"ej;4"}, // ㄍㄨㄤˋ 644
  (const spell PROGMEM) {"ej/"}, // ㄍㄨㄥ 645
  (const spell PROGMEM) {"ej/6"}, // ㄍㄨㄥˊ 646
  (const spell PROGMEM) {"ej/3"}, // ㄍㄨㄥˇ 647
  (const spell PROGMEM) {"ej/4"}, // ㄍㄨㄥˋ 648
  (const spell PROGMEM) {"d8"}, // ㄎㄚ 649
  (const spell PROGMEM) {"d86"}, // ㄎㄚˊ 650
  (const spell PROGMEM) {"d83"}, // ㄎㄚˇ 651
  (const spell PROGMEM) {"d84"}, // ㄎㄚˋ 652
  (const spell PROGMEM) {"dk"}, // ㄎㄜ 653
  (const spell PROGMEM) {"dk6"}, // ㄎㄜˊ 654
  (const spell PROGMEM) {"dk3"}, // ㄎㄜˇ 655
  (const spell PROGMEM) {"dk4"}, // ㄎㄜˋ 656
  (const spell PROGMEM) {"d9"}, // ㄎㄞ 657
  (const spell PROGMEM) {"d96"}, // ㄎㄞˊ 658
  (const spell PROGMEM) {"d93"}, // ㄎㄞˇ 659
  (const spell PROGMEM) {"d94"}, // ㄎㄞˋ 660
  (const spell PROGMEM) {"do"}, // ㄎㄟ 661
  (const spell PROGMEM) {"dl"}, // ㄎㄠ 662
  (const spell PROGMEM) {"dl6"}, // ㄎㄠˊ 663
  (const spell PROGMEM) {"dl3"}, // ㄎㄠˇ 664
  (const spell PROGMEM) {"dl4"}, // ㄎㄠˋ 665
  (const spell PROGMEM) {"dl7"}, // ㄎㄠ˙ 666
  (const spell PROGMEM) {"d."}, // ㄎㄡ 667
  (const spell PROGMEM) {"d.6"}, // ㄎㄡˊ 668
  (const spell PROGMEM) {"d.3"}, // ㄎㄡˇ 669
  (const spell PROGMEM) {"d.4"}, // ㄎㄡˋ 670
  (const spell PROGMEM) {"d0"}, // ㄎㄢ 671
  (const spell PROGMEM) {"d06"}, // ㄎㄢˊ 672
  (const spell PROGMEM) {"d03"}, // ㄎㄢˇ 673
  (const spell PROGMEM) {"d04"}, // ㄎㄢˋ 674
  (const spell PROGMEM) {"dp6"}, // ㄎㄣˊ 675
  (const spell PROGMEM) {"dp3"}, // ㄎㄣˇ 676
  (const spell PROGMEM) {"dp4"}, // ㄎㄣˋ 677
  (const spell PROGMEM) {"d;"}, // ㄎㄤ 678
  (const spell PROGMEM) {"d;6"}, // ㄎㄤˊ 679
  (const spell PROGMEM) {"d;3"}, // ㄎㄤˇ 680
  (const spell PROGMEM) {"d;4"}, // ㄎㄤˋ 681
  (const spell PROGMEM) {"d/"}, // ㄎㄥ 682
  (const spell PROGMEM) {"d/6"}, // ㄎㄥˊ 683
  (const spell PROGMEM) {"d/3"}, // ㄎㄥˇ 684
  (const spell PROGMEM) {"dj"}, // ㄎㄨ 685
  (const spell PROGMEM) {"dj6"}, // ㄎㄨˊ 686
  (const spell PROGMEM) {"dj3"}, // ㄎㄨˇ 687
  (const spell PROGMEM) {"dj4"}, // ㄎㄨˋ 688
  (const spell PROGMEM) {"dj8"}, // ㄎㄨㄚ 689
  (const spell PROGMEM) {"dj86"}, // ㄎㄨㄚˊ 690
  (const spell PROGMEM) {"dj83"}, // ㄎㄨㄚˇ 691
  (const spell PROGMEM) {"dj84"}, // ㄎㄨㄚˋ 692
  (const spell PROGMEM) {"dj9"}, // ㄎㄨㄞ 693
  (const spell PROGMEM) {"dj96"}, // ㄎㄨㄞˊ 694
  (const spell PROGMEM) {"dj93"}, // ㄎㄨㄞˇ 695
  (const spell PROGMEM) {"dj94"}, // ㄎㄨㄞˋ 696
  (const spell PROGMEM) {"djo"}, // ㄎㄨㄟ 697
  (const spell PROGMEM) {"djo6"}, // ㄎㄨㄟˊ 698
  (const spell PROGMEM) {"djo3"}, // ㄎㄨㄟˇ 699
  (const spell PROGMEM) {"djo4"}, // ㄎㄨㄟˋ 700
  (const spell PROGMEM) {"dj0"}, // ㄎㄨㄢ 701
  (const spell PROGMEM) {"dj06"}, // ㄎㄨㄢˊ 702
  (const spell PROGMEM) {"dj03"}, // ㄎㄨㄢˇ 703
  (const spell PROGMEM) {"djp"}, // ㄎㄨㄣ 704
  (const spell PROGMEM) {"djp6"}, // ㄎㄨㄣˊ 705
  (const spell PROGMEM) {"djp3"}, // ㄎㄨㄣˇ 706
  (const spell PROGMEM) {"djp4"}, // ㄎㄨㄣˋ 707
  (const spell PROGMEM) {"dj;"}, // ㄎㄨㄤ 708
  (const spell PROGMEM) {"dj;6"}, // ㄎㄨㄤˊ 709
  (const spell PROGMEM) {"dj;4"}, // ㄎㄨㄤˋ 710
  (const spell PROGMEM) {"dj/"}, // ㄎㄨㄥ 711
  (const spell PROGMEM) {"dj/6"}, // ㄎㄨㄥˊ 712
  (const spell PROGMEM) {"dj/3"}, // ㄎㄨㄥˇ 713
  (const spell PROGMEM) {"dj/4"}, // ㄎㄨㄥˋ 714
  (const spell PROGMEM) {"c8"}, // ㄏㄚ 715
  (const spell PROGMEM) {"c86"}, // ㄏㄚˊ 716
  (const spell PROGMEM) {"c83"}, // ㄏㄚˇ 717
  (const spell PROGMEM) {"c84"}, // ㄏㄚˋ 718
  (const spell PROGMEM) {"ck"}, // ㄏㄜ 719
  (const spell PROGMEM) {"ck6"}, // ㄏㄜˊ 720
  (const spell PROGMEM) {"ck4"}, // ㄏㄜˋ 721
  (const spell PROGMEM) {"c9"}, // ㄏㄞ 722
  (const spell PROGMEM) {"c96"}, // ㄏㄞˊ 723
  (const spell PROGMEM) {"c93"}, // ㄏㄞˇ 724
  (const spell PROGMEM) {"c94"}, // ㄏㄞˋ 725
  (const spell PROGMEM) {"co"}, // ㄏㄟ 726
  (const spell PROGMEM) {"co3"}, // ㄏㄟˇ 727
  (const spell PROGMEM) {"co4"}, // ㄏㄟˋ 728
  (const spell PROGMEM) {"cl"}, // ㄏㄠ 729
  (const spell PROGMEM) {"cl6"}, // ㄏㄠˊ 730
  (const spell PROGMEM) {"cl3"}, // ㄏㄠˇ 731
  (const spell PROGMEM) {"cl4"}, // ㄏㄠˋ 732
  (const spell PROGMEM) {"c."}, // ㄏㄡ 733
  (const spell PROGMEM) {"c.6"}, // ㄏㄡˊ 734
  (const spell PROGMEM) {"c.3"}, // ㄏㄡˇ 735
  (const spell PROGMEM) {"c.4"}, // ㄏㄡˋ 736
  (const spell PROGMEM) {"c0"}, // ㄏㄢ 737
  (const spell PROGMEM) {"c06"}, // ㄏㄢˊ 738
  (const spell PROGMEM) {"c03"}, // ㄏㄢˇ 739
  (const spell PROGMEM) {"c04"}, // ㄏㄢˋ 740
  (const spell PROGMEM) {"cp"}, // ㄏㄣ 741
  (const spell PROGMEM) {"cp6"}, // ㄏㄣˊ 742
  (const spell PROGMEM) {"cp3"}, // ㄏㄣˇ 743
  (const spell PROGMEM) {"cp4"}, // ㄏㄣˋ 744
  (const spell PROGMEM) {"c;"}, // ㄏㄤ 745
  (const spell PROGMEM) {"c;6"}, // ㄏㄤˊ 746
  (const spell PROGMEM) {"c;4"}, // ㄏㄤˋ 747
  (const spell PROGMEM) {"c/"}, // ㄏㄥ 748
  (const spell PROGMEM) {"c/6"}, // ㄏㄥˊ 749
  (const spell PROGMEM) {"c/4"}, // ㄏㄥˋ 750
  (const spell PROGMEM) {"cj"}, // ㄏㄨ 751
  (const spell PROGMEM) {"cj6"}, // ㄏㄨˊ 752
  (const spell PROGMEM) {"cj3"}, // ㄏㄨˇ 753
  (const spell PROGMEM) {"cj4"}, // ㄏㄨˋ 754
  (const spell PROGMEM) {"cj8"}, // ㄏㄨㄚ 755
  (const spell PROGMEM) {"cj86"}, // ㄏㄨㄚˊ 756
  (const spell PROGMEM) {"cj84"}, // ㄏㄨㄚˋ 757
  (const spell PROGMEM) {"cji"}, // ㄏㄨㄛ 758
  (const spell PROGMEM) {"cji6"}, // ㄏㄨㄛˊ 759
  (const spell PROGMEM) {"cji3"}, // ㄏㄨㄛˇ 760
  (const spell PROGMEM) {"cji4"}, // ㄏㄨㄛˋ 761
  (const spell PROGMEM) {"cji7"}, // ㄏㄨㄛ˙ 762
  (const spell PROGMEM) {"cj96"}, // ㄏㄨㄞˊ 763
  (const spell PROGMEM) {"cj94"}, // ㄏㄨㄞˋ 764
  (const spell PROGMEM) {"cjo"}, // ㄏㄨㄟ 765
  (const spell PROGMEM) {"cjo6"}, // ㄏㄨㄟˊ 766
  (const spell PROGMEM) {"cjo3"}, // ㄏㄨㄟˇ 767
  (const spell PROGMEM) {"cjo4"}, // ㄏㄨㄟˋ 768
  (const spell PROGMEM) {"cj0"}, // ㄏㄨㄢ 769
  (const spell PROGMEM) {"cj06"}, // ㄏㄨㄢˊ 770
  (const spell PROGMEM) {"cj03"}, // ㄏㄨㄢˇ 771
  (const spell PROGMEM) {"cj04"}, // ㄏㄨㄢˋ 772
  (const spell PROGMEM) {"cjp"}, // ㄏㄨㄣ 773
  (const spell PROGMEM) {"cjp6"}, // ㄏㄨㄣˊ 774
  (const spell PROGMEM) {"cjp3"}, // ㄏㄨㄣˇ 775
  (const spell PROGMEM) {"cjp4"}, // ㄏㄨㄣˋ 776
  (const spell PROGMEM) {"cj;"}, // ㄏㄨㄤ 777
  (const spell PROGMEM) {"cj;6"}, // ㄏㄨㄤˊ 778
  (const spell PROGMEM) {"cj;3"}, // ㄏㄨㄤˇ 779
  (const spell PROGMEM) {"cj;4"}, // ㄏㄨㄤˋ 780
  (const spell PROGMEM) {"cj;7"}, // ㄏㄨㄤ˙ 781
  (const spell PROGMEM) {"cj/"}, // ㄏㄨㄥ 782
  (const spell PROGMEM) {"cj/6"}, // ㄏㄨㄥˊ 783
  (const spell PROGMEM) {"cj/3"}, // ㄏㄨㄥˇ 784
  (const spell PROGMEM) {"cj/4"}, // ㄏㄨㄥˋ 785
  (const spell PROGMEM) {"ru"}, // ㄐㄧ 786
  (const spell PROGMEM) {"ru6"}, // ㄐㄧˊ 787
  (const spell PROGMEM) {"ru3"}, // ㄐㄧˇ 788
  (const spell PROGMEM) {"ru4"}, // ㄐㄧˋ 789
  (const spell PROGMEM) {"ru7"}, // ㄐㄧ˙ 790
  (const spell PROGMEM) {"ru8"}, // ㄐㄧㄚ 791
  (const spell PROGMEM) {"ru86"}, // ㄐㄧㄚˊ 792
  (const spell PROGMEM) {"ru83"}, // ㄐㄧㄚˇ 793
  (const spell PROGMEM) {"ru84"}, // ㄐㄧㄚˋ 794
  (const spell PROGMEM) {"ru,"}, // ㄐㄧㄝ 795
  (const spell PROGMEM) {"ru,6"}, // ㄐㄧㄝˊ 796
  (const spell PROGMEM) {"ru,3"}, // ㄐㄧㄝˇ 797
  (const spell PROGMEM) {"ru,4"}, // ㄐㄧㄝˋ 798
  (const spell PROGMEM) {"ru,7"}, // ㄐㄧㄝ˙ 799
  (const spell PROGMEM) {"rul"}, // ㄐㄧㄠ 800
  (const spell PROGMEM) {"rul6"}, // ㄐㄧㄠˊ 801
  (const spell PROGMEM) {"rul3"}, // ㄐㄧㄠˇ 802
  (const spell PROGMEM) {"rul4"}, // ㄐㄧㄠˋ 803
  (const spell PROGMEM) {"ru."}, // ㄐㄧㄡ 804
  (const spell PROGMEM) {"ru.6"}, // ㄐㄧㄡˊ 805
  (const spell PROGMEM) {"ru.3"}, // ㄐㄧㄡˇ 806
  (const spell PROGMEM) {"ru.4"}, // ㄐㄧㄡˋ 807
  (const spell PROGMEM) {"ru0"}, // ㄐㄧㄢ 808
  (const spell PROGMEM) {"ru06"}, // ㄐㄧㄢˊ 809
  (const spell PROGMEM) {"ru03"}, // ㄐㄧㄢˇ 810
  (const spell PROGMEM) {"ru04"}, // ㄐㄧㄢˋ 811
  (const spell PROGMEM) {"rup"}, // ㄐㄧㄣ 812
  (const spell PROGMEM) {"rup6"}, // ㄐㄧㄣˊ 813
  (const spell PROGMEM) {"rup3"}, // ㄐㄧㄣˇ 814
  (const spell PROGMEM) {"rup4"}, // ㄐㄧㄣˋ 815
  (const spell PROGMEM) {"rup7"}, // ㄐㄧㄣ˙ 816
  (const spell PROGMEM) {"ru;"}, // ㄐㄧㄤ 817
  (const spell PROGMEM) {"ru;6"}, // ㄐㄧㄤˊ 818
  (const spell PROGMEM) {"ru;3"}, // ㄐㄧㄤˇ 819
  (const spell PROGMEM) {"ru;4"}, // ㄐㄧㄤˋ 820
  (const spell PROGMEM) {"ru/"}, // ㄐㄧㄥ 821
  (const spell PROGMEM) {"ru/6"}, // ㄐㄧㄥˊ 822
  (const spell PROGMEM) {"ru/3"}, // ㄐㄧㄥˇ 823
  (const spell PROGMEM) {"ru/4"}, // ㄐㄧㄥˋ 824
  (const spell PROGMEM) {"rm"}, // ㄐㄩ 825
  (const spell PROGMEM) {"rm6"}, // ㄐㄩˊ 826
  (const spell PROGMEM) {"rm3"}, // ㄐㄩˇ 827
  (const spell PROGMEM) {"rm4"}, // ㄐㄩˋ 828
  (const spell PROGMEM) {"rm,"}, // ㄐㄩㄝ 829
  (const spell PROGMEM) {"rm,6"}, // ㄐㄩㄝˊ 830
  (const spell PROGMEM) {"rm,3"}, // ㄐㄩㄝˇ 831
  (const spell PROGMEM) {"rm,4"}, // ㄐㄩㄝˋ 832
  (const spell PROGMEM) {"rm0"}, // ㄐㄩㄢ 833
  (const spell PROGMEM) {"rm06"}, // ㄐㄩㄢˊ 834
  (const spell PROGMEM) {"rm03"}, // ㄐㄩㄢˇ 835
  (const spell PROGMEM) {"rm04"}, // ㄐㄩㄢˋ 836
  (const spell PROGMEM) {"rmp"}, // ㄐㄩㄣ 837
  (const spell PROGMEM) {"rmp4"}, // ㄐㄩㄣˋ 838
  (const spell PROGMEM) {"rm/"}, // ㄐㄩㄥ 839
  (const spell PROGMEM) {"rm/6"}, // ㄐㄩㄥˊ 840
  (const spell PROGMEM) {"rm/3"}, // ㄐㄩㄥˇ 841
  (const spell PROGMEM) {"fu"}, // ㄑㄧ 842
  (const spell PROGMEM) {"fu6"}, // ㄑㄧˊ 843
  (const spell PROGMEM) {"fu3"}, // ㄑㄧˇ 844
  (const spell PROGMEM) {"fu4"}, // ㄑㄧˋ 845
  (const spell PROGMEM) {"fu8"}, // ㄑㄧㄚ 846
  (const spell PROGMEM) {"fu86"}, // ㄑㄧㄚˊ 847
  (const spell PROGMEM) {"fu83"}, // ㄑㄧㄚˇ 848
  (const spell PROGMEM) {"fu84"}, // ㄑㄧㄚˋ 849
  (const spell PROGMEM) {"fu,"}, // ㄑㄧㄝ 850
  (const spell PROGMEM) {"fu,6"}, // ㄑㄧㄝˊ 851
  (const spell PROGMEM) {"fu,3"}, // ㄑㄧㄝˇ 852
  (const spell PROGMEM) {"fu,4"}, // ㄑㄧㄝˋ 853
  (const spell PROGMEM) {"ful"}, // ㄑㄧㄠ 854
  (const spell PROGMEM) {"ful6"}, // ㄑㄧㄠˊ 855
  (const spell PROGMEM) {"ful3"}, // ㄑㄧㄠˇ 856
  (const spell PROGMEM) {"ful4"}, // ㄑㄧㄠˋ 857
  (const spell PROGMEM) {"fu."}, // ㄑㄧㄡ 858
  (const spell PROGMEM) {"fu.6"}, // ㄑㄧㄡˊ 859
  (const spell PROGMEM) {"fu.3"}, // ㄑㄧㄡˇ 860
  (const spell PROGMEM) {"fu.7"}, // ㄑㄧㄡ˙ 861
  (const spell PROGMEM) {"fu0"}, // ㄑㄧㄢ 862
  (const spell PROGMEM) {"fu06"}, // ㄑㄧㄢˊ 863
  (const spell PROGMEM) {"fu03"}, // ㄑㄧㄢˇ 864
  (const spell PROGMEM) {"fu04"}, // ㄑㄧㄢˋ 865
  (const spell PROGMEM) {"fup"}, // ㄑㄧㄣ 866
  (const spell PROGMEM) {"fup6"}, // ㄑㄧㄣˊ 867
  (const spell PROGMEM) {"fup3"}, // ㄑㄧㄣˇ 868
  (const spell PROGMEM) {"fup4"}, // ㄑㄧㄣˋ 869
  (const spell PROGMEM) {"fu;"}, // ㄑㄧㄤ 870
  (const spell PROGMEM) {"fu;6"}, // ㄑㄧㄤˊ 871
  (const spell PROGMEM) {"fu;3"}, // ㄑㄧㄤˇ 872
  (const spell PROGMEM) {"fu;4"}, // ㄑㄧㄤˋ 873
  (const spell PROGMEM) {"fu/"}, // ㄑㄧㄥ 874
  (const spell PROGMEM) {"fu/6"}, // ㄑㄧㄥˊ 875
  (const spell PROGMEM) {"fu/3"}, // ㄑㄧㄥˇ 876
  (const spell PROGMEM) {"fu/4"}, // ㄑㄧㄥˋ 877
  (const spell PROGMEM) {"fm"}, // ㄑㄩ 878
  (const spell PROGMEM) {"fm6"}, // ㄑㄩˊ 879
  (const spell PROGMEM) {"fm3"}, // ㄑㄩˇ 880
  (const spell PROGMEM) {"fm4"}, // ㄑㄩˋ 881
  (const spell PROGMEM) {"fm,"}, // ㄑㄩㄝ 882
  (const spell PROGMEM) {"fm,6"}, // ㄑㄩㄝˊ 883
  (const spell PROGMEM) {"fm,4"}, // ㄑㄩㄝˋ 884
  (const spell PROGMEM) {"fm0"}, // ㄑㄩㄢ 885
  (const spell PROGMEM) {"fm06"}, // ㄑㄩㄢˊ 886
  (const spell PROGMEM) {"fm03"}, // ㄑㄩㄢˇ 887
  (const spell PROGMEM) {"fm04"}, // ㄑㄩㄢˋ 888
  (const spell PROGMEM) {"fmp"}, // ㄑㄩㄣ 889
  (const spell PROGMEM) {"fmp6"}, // ㄑㄩㄣˊ 890
  (const spell PROGMEM) {"fm/"}, // ㄑㄩㄥ 891
  (const spell PROGMEM) {"fm/6"}, // ㄑㄩㄥˊ 892
  (const spell PROGMEM) {"fm/3"}, // ㄑㄩㄥˇ 893
  (const spell PROGMEM) {"vu"}, // ㄒㄧ 894
  (const spell PROGMEM) {"vu6"}, // ㄒㄧˊ 895
  (const spell PROGMEM) {"vu3"}, // ㄒㄧˇ 896
  (const spell PROGMEM) {"vu4"}, // ㄒㄧˋ 897
  (const spell PROGMEM) {"vu7"}, // ㄒㄧ˙ 898
  (const spell PROGMEM) {"vu8"}, // ㄒㄧㄚ 899
  (const spell PROGMEM) {"vu86"}, // ㄒㄧㄚˊ 900
  (const spell PROGMEM) {"vu84"}, // ㄒㄧㄚˋ 901
  (const spell PROGMEM) {"vu,"}, // ㄒㄧㄝ 902
  (const spell PROGMEM) {"vu,6"}, // ㄒㄧㄝˊ 903
  (const spell PROGMEM) {"vu,3"}, // ㄒㄧㄝˇ 904
  (const spell PROGMEM) {"vu,4"}, // ㄒㄧㄝˋ 905
  (const spell PROGMEM) {"vu,7"}, // ㄒㄧㄝ˙ 906
  (const spell PROGMEM) {"vul"}, // ㄒㄧㄠ 907
  (const spell PROGMEM) {"vul6"}, // ㄒㄧㄠˊ 908
  (const spell PROGMEM) {"vul3"}, // ㄒㄧㄠˇ 909
  (const spell PROGMEM) {"vul4"}, // ㄒㄧㄠˋ 910
  (const spell PROGMEM) {"vu."}, // ㄒㄧㄡ 911
  (const spell PROGMEM) {"vu.6"}, // ㄒㄧㄡˊ 912
  (const spell PROGMEM) {"vu.3"}, // ㄒㄧㄡˇ 913
  (const spell PROGMEM) {"vu.4"}, // ㄒㄧㄡˋ 914
  (const spell PROGMEM) {"vu0"}, // ㄒㄧㄢ 915
  (const spell PROGMEM) {"vu06"}, // ㄒㄧㄢˊ 916
  (const spell PROGMEM) {"vu03"}, // ㄒㄧㄢˇ 917
  (const spell PROGMEM) {"vu04"}, // ㄒㄧㄢˋ 918
  (const spell PROGMEM) {"vup"}, // ㄒㄧㄣ 919
  (const spell PROGMEM) {"vup6"}, // ㄒㄧㄣˊ 920
  (const spell PROGMEM) {"vup4"}, // ㄒㄧㄣˋ 921
  (const spell PROGMEM) {"vu;"}, // ㄒㄧㄤ 922
  (const spell PROGMEM) {"vu;6"}, // ㄒㄧㄤˊ 923
  (const spell PROGMEM) {"vu;3"}, // ㄒㄧㄤˇ 924
  (const spell PROGMEM) {"vu;4"}, // ㄒㄧㄤˋ 925
  (const spell PROGMEM) {"vu/"}, // ㄒㄧㄥ 926
  (const spell PROGMEM) {"vu/6"}, // ㄒㄧㄥˊ 927
  (const spell PROGMEM) {"vu/3"}, // ㄒㄧㄥˇ 928
  (const spell PROGMEM) {"vu/4"}, // ㄒㄧㄥˋ 929
  (const spell PROGMEM) {"vm"}, // ㄒㄩ 930
  (const spell PROGMEM) {"vm6"}, // ㄒㄩˊ 931
  (const spell PROGMEM) {"vm3"}, // ㄒㄩˇ 932
  (const spell PROGMEM) {"vm4"}, // ㄒㄩˋ 933
  (const spell PROGMEM) {"vm,"}, // ㄒㄩㄝ 934
  (const spell PROGMEM) {"vm,6"}, // ㄒㄩㄝˊ 935
  (const spell PROGMEM) {"vm,3"}, // ㄒㄩㄝˇ 936
  (const spell PROGMEM) {"vm,4"}, // ㄒㄩㄝˋ 937
  (const spell PROGMEM) {"vm0"}, // ㄒㄩㄢ 938
  (const spell PROGMEM) {"vm06"}, // ㄒㄩㄢˊ 939
  (const spell PROGMEM) {"vm03"}, // ㄒㄩㄢˇ 940
  (const spell PROGMEM) {"vm04"}, // ㄒㄩㄢˋ 941
  (const spell PROGMEM) {"vmp"}, // ㄒㄩㄣ 942
  (const spell PROGMEM) {"vmp6"}, // ㄒㄩㄣˊ 943
  (const spell PROGMEM) {"vmp4"}, // ㄒㄩㄣˋ 944
  (const spell PROGMEM) {"vm/"}, // ㄒㄩㄥ 945
  (const spell PROGMEM) {"vm/6"}, // ㄒㄩㄥˊ 946
  (const spell PROGMEM) {"vm/3"}, // ㄒㄩㄥˇ 947
  (const spell PROGMEM) {"vm/4"}, // ㄒㄩㄥˋ 948
  (const spell PROGMEM) {"5"}, // ㄓ 949
  (const spell PROGMEM) {"56"}, // ㄓˊ 950
  (const spell PROGMEM) {"53"}, // ㄓˇ 951
  (const spell PROGMEM) {"54"}, // ㄓˋ 952
  (const spell PROGMEM) {"58"}, // ㄓㄚ 953
  (const spell PROGMEM) {"586"}, // ㄓㄚˊ 954
  (const spell PROGMEM) {"583"}, // ㄓㄚˇ 955
  (const spell PROGMEM) {"584"}, // ㄓㄚˋ 956
  (const spell PROGMEM) {"5k"}, // ㄓㄜ 957
  (const spell PROGMEM) {"5k6"}, // ㄓㄜˊ 958
  (const spell PROGMEM) {"5k3"}, // ㄓㄜˇ 959
  (const spell PROGMEM) {"5k4"}, // ㄓㄜˋ 960
  (const spell PROGMEM) {"5k7"}, // ㄓㄜ˙ 961
  (const spell PROGMEM) {"59"}, // ㄓㄞ 962
  (const spell PROGMEM) {"596"}, // ㄓㄞˊ 963
  (const spell PROGMEM) {"593"}, // ㄓㄞˇ 964
  (const spell PROGMEM) {"594"}, // ㄓㄞˋ 965
  (const spell PROGMEM) {"5o4"}, // ㄓㄟˋ 966
  (const spell PROGMEM) {"5l"}, // ㄓㄠ 967
  (const spell PROGMEM) {"5l6"}, // ㄓㄠˊ 968
  (const spell PROGMEM) {"5l3"}, // ㄓㄠˇ 969
  (const spell PROGMEM) {"5l4"}, // ㄓㄠˋ 970
  (const spell PROGMEM) {"5."}, // ㄓㄡ 971
  (const spell PROGMEM) {"5.6"}, // ㄓㄡˊ 972
  (const spell PROGMEM) {"5.3"}, // ㄓㄡˇ 973
  (const spell PROGMEM) {"5.4"}, // ㄓㄡˋ 974
  (const spell PROGMEM) {"50"}, // ㄓㄢ 975
  (const spell PROGMEM) {"506"}, // ㄓㄢˊ 976
  (const spell PROGMEM) {"503"}, // ㄓㄢˇ 977
  (const spell PROGMEM) {"504"}, // ㄓㄢˋ 978
  (const spell PROGMEM) {"5p"}, // ㄓㄣ 979
  (const spell PROGMEM) {"5p6"}, // ㄓㄣˊ 980
  (const spell PROGMEM) {"5p3"}, // ㄓㄣˇ 981
  (const spell PROGMEM) {"5p4"}, // ㄓㄣˋ 982
  (const spell PROGMEM) {"5;"}, // ㄓㄤ 983
  (const spell PROGMEM) {"5;6"}, // ㄓㄤˊ 984
  (const spell PROGMEM) {"5;3"}, // ㄓㄤˇ 985
  (const spell PROGMEM) {"5;4"}, // ㄓㄤˋ 986
  (const spell PROGMEM) {"5/"}, // ㄓㄥ 987
  (const spell PROGMEM) {"5/6"}, // ㄓㄥˊ 988
  (const spell PROGMEM) {"5/3"}, // ㄓㄥˇ 989
  (const spell PROGMEM) {"5/4"}, // ㄓㄥˋ 990
  (const spell PROGMEM) {"5j"}, // ㄓㄨ 991
  (const spell PROGMEM) {"5j6"}, // ㄓㄨˊ 992
  (const spell PROGMEM) {"5j3"}, // ㄓㄨˇ 993
  (const spell PROGMEM) {"5j4"}, // ㄓㄨˋ 994
  (const spell PROGMEM) {"5j8"}, // ㄓㄨㄚ 995
  (const spell PROGMEM) {"5j86"}, // ㄓㄨㄚˊ 996
  (const spell PROGMEM) {"5j83"}, // ㄓㄨㄚˇ 997
  (const spell PROGMEM) {"5ji"}, // ㄓㄨㄛ 998
  (const spell PROGMEM) {"5ji6"}, // ㄓㄨㄛˊ 999
  (const spell PROGMEM) {"5j9"}, // ㄓㄨㄞ 1000
  (const spell PROGMEM) {"5j93"}, // ㄓㄨㄞˇ 1001
  (const spell PROGMEM) {"5j94"}, // ㄓㄨㄞˋ 1002
  (const spell PROGMEM) {"5jo"}, // ㄓㄨㄟ 1003
  (const spell PROGMEM) {"5jo4"}, // ㄓㄨㄟˋ 1004
  (const spell PROGMEM) {"5j0"}, // ㄓㄨㄢ 1005
  (const spell PROGMEM) {"5j06"}, // ㄓㄨㄢˊ 1006
  (const spell PROGMEM) {"5j03"}, // ㄓㄨㄢˇ 1007
  (const spell PROGMEM) {"5j04"}, // ㄓㄨㄢˋ 1008
  (const spell PROGMEM) {"5jp"}, // ㄓㄨㄣ 1009
  (const spell PROGMEM) {"5jp3"}, // ㄓㄨㄣˇ 1010
  (const spell PROGMEM) {"5j;"}, // ㄓㄨㄤ 1011
  (const spell PROGMEM) {"5j;3"}, // ㄓㄨㄤˇ 1012
  (const spell PROGMEM) {"5j;4"}, // ㄓㄨㄤˋ 1013
  (const spell PROGMEM) {"5j/"}, // ㄓㄨㄥ 1014
  (const spell PROGMEM) {"5j/6"}, // ㄓㄨㄥˊ 1015
  (const spell PROGMEM) {"5j/3"}, // ㄓㄨㄥˇ 1016
  (const spell PROGMEM) {"5j/4"}, // ㄓㄨㄥˋ 1017
  (const spell PROGMEM) {"t"}, // ㄔ 1018
  (const spell PROGMEM) {"t6"}, // ㄔˊ 1019
  (const spell PROGMEM) {"t3"}, // ㄔˇ 1020
  (const spell PROGMEM) {"t4"}, // ㄔˋ 1021
  (const spell PROGMEM) {"t8"}, // ㄔㄚ 1022
  (const spell PROGMEM) {"t86"}, // ㄔㄚˊ 1023
  (const spell PROGMEM) {"t83"}, // ㄔㄚˇ 1024
  (const spell PROGMEM) {"t84"}, // ㄔㄚˋ 1025
  (const spell PROGMEM) {"tk"}, // ㄔㄜ 1026
  (const spell PROGMEM) {"tk6"}, // ㄔㄜˊ 1027
  (const spell PROGMEM) {"tk3"}, // ㄔㄜˇ 1028
  (const spell PROGMEM) {"tk4"}, // ㄔㄜˋ 1029
  (const spell PROGMEM) {"t9"}, // ㄔㄞ 1030
  (const spell PROGMEM) {"t96"}, // ㄔㄞˊ 1031
  (const spell PROGMEM) {"t93"}, // ㄔㄞˇ 1032
  (const spell PROGMEM) {"t94"}, // ㄔㄞˋ 1033
  (const spell PROGMEM) {"tl"}, // ㄔㄠ 1034
  (const spell PROGMEM) {"tl6"}, // ㄔㄠˊ 1035
  (const spell PROGMEM) {"tl3"}, // ㄔㄠˇ 1036
  (const spell PROGMEM) {"tl4"}, // ㄔㄠˋ 1037
  (const spell PROGMEM) {"t."}, // ㄔㄡ 1038
  (const spell PROGMEM) {"t.6"}, // ㄔㄡˊ 1039
  (const spell PROGMEM) {"t.3"}, // ㄔㄡˇ 1040
  (const spell PROGMEM) {"t.4"}, // ㄔㄡˋ 1041
  (const spell PROGMEM) {"t0"}, // ㄔㄢ 1042
  (const spell PROGMEM) {"t06"}, // ㄔㄢˊ 1043
  (const spell PROGMEM) {"t03"}, // ㄔㄢˇ 1044
  (const spell PROGMEM) {"t04"}, // ㄔㄢˋ 1045
  (const spell PROGMEM) {"tp"}, // ㄔㄣ 1046
  (const spell PROGMEM) {"tp6"}, // ㄔㄣˊ 1047
  (const spell PROGMEM) {"tp3"}, // ㄔㄣˇ 1048
  (const spell PROGMEM) {"tp4"}, // ㄔㄣˋ 1049
  (const spell PROGMEM) {"t;"}, // ㄔㄤ 1050
  (const spell PROGMEM) {"t;6"}, // ㄔㄤˊ 1051
  (const spell PROGMEM) {"t;3"}, // ㄔㄤˇ 1052
  (const spell PROGMEM) {"t;4"}, // ㄔㄤˋ 1053
  (const spell PROGMEM) {"t/"}, // ㄔㄥ 1054
  (const spell PROGMEM) {"t/6"}, // ㄔㄥˊ 1055
  (const spell PROGMEM) {"t/3"}, // ㄔㄥˇ 1056
  (const spell PROGMEM) {"t/4"}, // ㄔㄥˋ 1057
  (const spell PROGMEM) {"tj"}, // ㄔㄨ 1058
  (const spell PROGMEM) {"tj6"}, // ㄔㄨˊ 1059
  (const spell PROGMEM) {"tj3"}, // ㄔㄨˇ 1060
  (const spell PROGMEM) {"tj4"}, // ㄔㄨˋ 1061
  (const spell PROGMEM) {"tj8"}, // ㄔㄨㄚ 1062
  (const spell PROGMEM) {"tj83"}, // ㄔㄨㄚˇ 1063
  (const spell PROGMEM) {"tj84"}, // ㄔㄨㄚˋ 1064
  (const spell PROGMEM) {"tji"}, // ㄔㄨㄛ 1065
  (const spell PROGMEM) {"tji4"}, // ㄔㄨㄛˋ 1066
  (const spell PROGMEM) {"tj9"}, // ㄔㄨㄞ 1067
  (const spell PROGMEM) {"tj93"}, // ㄔㄨㄞˇ 1068
  (const spell PROGMEM) {"tj94"}, // ㄔㄨㄞˋ 1069
  (const spell PROGMEM) {"tjo"}, // ㄔㄨㄟ 1070
  (const spell PROGMEM) {"tjo6"}, // ㄔㄨㄟˊ 1071
  (const spell PROGMEM) {"tjo4"}, // ㄔㄨㄟˋ 1072
  (const spell PROGMEM) {"tj0"}, // ㄔㄨㄢ 1073
  (const spell PROGMEM) {"tj06"}, // ㄔㄨㄢˊ 1074
  (const spell PROGMEM) {"tj03"}, // ㄔㄨㄢˇ 1075
  (const spell PROGMEM) {"tj04"}, // ㄔㄨㄢˋ 1076
  (const spell PROGMEM) {"tjp"}, // ㄔㄨㄣ 1077
  (const spell PROGMEM) {"tjp6"}, // ㄔㄨㄣˊ 1078
  (const spell PROGMEM) {"tjp3"}, // ㄔㄨㄣˇ 1079
  (const spell PROGMEM) {"tj;"}, // ㄔㄨㄤ 1080
  (const spell PROGMEM) {"tj;6"}, // ㄔㄨㄤˊ 1081
  (const spell PROGMEM) {"tj;3"}, // ㄔㄨㄤˇ 1082
  (const spell PROGMEM) {"tj;4"}, // ㄔㄨㄤˋ 1083
  (const spell PROGMEM) {"tj/"}, // ㄔㄨㄥ 1084
  (const spell PROGMEM) {"tj/6"}, // ㄔㄨㄥˊ 1085
  (const spell PROGMEM) {"tj/3"}, // ㄔㄨㄥˇ 1086
  (const spell PROGMEM) {"tj/4"}, // ㄔㄨㄥˋ 1087
  (const spell PROGMEM) {"g"}, // ㄕ 1088
  (const spell PROGMEM) {"g6"}, // ㄕˊ 1089
  (const spell PROGMEM) {"g3"}, // ㄕˇ 1090
  (const spell PROGMEM) {"g4"}, // ㄕˋ 1091
  (const spell PROGMEM) {"g7"}, // ㄕ˙ 1092
  (const spell PROGMEM) {"g8"}, // ㄕㄚ 1093
  (const spell PROGMEM) {"g86"}, // ㄕㄚˊ 1094
  (const spell PROGMEM) {"g83"}, // ㄕㄚˇ 1095
  (const spell PROGMEM) {"g84"}, // ㄕㄚˋ 1096
  (const spell PROGMEM) {"gk"}, // ㄕㄜ 1097
  (const spell PROGMEM) {"gk6"}, // ㄕㄜˊ 1098
  (const spell PROGMEM) {"gk3"}, // ㄕㄜˇ 1099
  (const spell PROGMEM) {"gk4"}, // ㄕㄜˋ 1100
  (const spell PROGMEM) {"g9"}, // ㄕㄞ 1101
  (const spell PROGMEM) {"g93"}, // ㄕㄞˇ 1102
  (const spell PROGMEM) {"g94"}, // ㄕㄞˋ 1103
  (const spell PROGMEM) {"go6"}, // ㄕㄟˊ 1104
  (const spell PROGMEM) {"gl"}, // ㄕㄠ 1105
  (const spell PROGMEM) {"gl6"}, // ㄕㄠˊ 1106
  (const spell PROGMEM) {"gl3"}, // ㄕㄠˇ 1107
  (const spell PROGMEM) {"gl4"}, // ㄕㄠˋ 1108
  (const spell PROGMEM) {"g."}, // ㄕㄡ 1109
  (const spell PROGMEM) {"g.6"}, // ㄕㄡˊ 1110
  (const spell PROGMEM) {"g.3"}, // ㄕㄡˇ 1111
  (const spell PROGMEM) {"g.4"}, // ㄕㄡˋ 1112
  (const spell PROGMEM) {"g0"}, // ㄕㄢ 1113
  (const spell PROGMEM) {"g06"}, // ㄕㄢˊ 1114
  (const spell PROGMEM) {"g03"}, // ㄕㄢˇ 1115
  (const spell PROGMEM) {"g04"}, // ㄕㄢˋ 1116
  (const spell PROGMEM) {"gp"}, // ㄕㄣ 1117
  (const spell PROGMEM) {"gp6"}, // ㄕㄣˊ 1118
  (const spell PROGMEM) {"gp3"}, // ㄕㄣˇ 1119
  (const spell PROGMEM) {"gp4"}, // ㄕㄣˋ 1120
  (const spell PROGMEM) {"g;"}, // ㄕㄤ 1121
  (const spell PROGMEM) {"g;6"}, // ㄕㄤˊ 1122
  (const spell PROGMEM) {"g;3"}, // ㄕㄤˇ 1123
  (const spell PROGMEM) {"g;4"}, // ㄕㄤˋ 1124
  (const spell PROGMEM) {"g/"}, // ㄕㄥ 1125
  (const spell PROGMEM) {"g/6"}, // ㄕㄥˊ 1126
  (const spell PROGMEM) {"g/3"}, // ㄕㄥˇ 1127
  (const spell PROGMEM) {"g/4"}, // ㄕㄥˋ 1128
  (const spell PROGMEM) {"g/7"}, // ㄕㄥ˙ 1129
  (const spell PROGMEM) {"gj"}, // ㄕㄨ 1130
  (const spell PROGMEM) {"gj6"}, // ㄕㄨˊ 1131
  (const spell PROGMEM) {"gj3"}, // ㄕㄨˇ 1132
  (const spell PROGMEM) {"gj4"}, // ㄕㄨˋ 1133
  (const spell PROGMEM) {"gj7"}, // ㄕㄨ˙ 1134
  (const spell PROGMEM) {"gj8"}, // ㄕㄨㄚ 1135
  (const spell PROGMEM) {"gj86"}, // ㄕㄨㄚˊ 1136
  (const spell PROGMEM) {"gj83"}, // ㄕㄨㄚˇ 1137
  (const spell PROGMEM) {"gj84"}, // ㄕㄨㄚˋ 1138
  (const spell PROGMEM) {"gji"}, // ㄕㄨㄛ 1139
  (const spell PROGMEM) {"gji4"}, // ㄕㄨㄛˋ 1140
  (const spell PROGMEM) {"gj9"}, // ㄕㄨㄞ 1141
  (const spell PROGMEM) {"gj93"}, // ㄕㄨㄞˇ 1142
  (const spell PROGMEM) {"gj94"}, // ㄕㄨㄞˋ 1143
  (const spell PROGMEM) {"gjo6"}, // ㄕㄨㄟˊ 1144
  (const spell PROGMEM) {"gjo3"}, // ㄕㄨㄟˇ 1145
  (const spell PROGMEM) {"gjo4"}, // ㄕㄨㄟˋ 1146
  (const spell PROGMEM) {"gj0"}, // ㄕㄨㄢ 1147
  (const spell PROGMEM) {"gj04"}, // ㄕㄨㄢˋ 1148
  (const spell PROGMEM) {"gjp3"}, // ㄕㄨㄣˇ 1149
  (const spell PROGMEM) {"gjp4"}, // ㄕㄨㄣˋ 1150
  (const spell PROGMEM) {"gj;"}, // ㄕㄨㄤ 1151
  (const spell PROGMEM) {"gj;6"}, // ㄕㄨㄤˊ 1152
  (const spell PROGMEM) {"gj;3"}, // ㄕㄨㄤˇ 1153
  (const spell PROGMEM) {"gj;4"}, // ㄕㄨㄤˋ 1154
  (const spell PROGMEM) {"b4"}, // ㄖˋ 1155
  (const spell PROGMEM) {"bk3"}, // ㄖㄜˇ 1156
  (const spell PROGMEM) {"bk4"}, // ㄖㄜˋ 1157
  (const spell PROGMEM) {"bl6"}, // ㄖㄠˊ 1158
  (const spell PROGMEM) {"bl3"}, // ㄖㄠˇ 1159
  (const spell PROGMEM) {"bl4"}, // ㄖㄠˋ 1160
  (const spell PROGMEM) {"b.6"}, // ㄖㄡˊ 1161
  (const spell PROGMEM) {"b.3"}, // ㄖㄡˇ 1162
  (const spell PROGMEM) {"b.4"}, // ㄖㄡˋ 1163
  (const spell PROGMEM) {"b06"}, // ㄖㄢˊ 1164
  (const spell PROGMEM) {"b03"}, // ㄖㄢˇ 1165
  (const spell PROGMEM) {"bp6"}, // ㄖㄣˊ 1166
  (const spell PROGMEM) {"bp3"}, // ㄖㄣˇ 1167
  (const spell PROGMEM) {"bp4"}, // ㄖㄣˋ 1168
  (const spell PROGMEM) {"b;"}, // ㄖㄤ 1169
  (const spell PROGMEM) {"b;6"}, // ㄖㄤˊ 1170
  (const spell PROGMEM) {"b;3"}, // ㄖㄤˇ 1171
  (const spell PROGMEM) {"b;4"}, // ㄖㄤˋ 1172
  (const spell PROGMEM) {"b/"}, // ㄖㄥ 1173
  (const spell PROGMEM) {"b/6"}, // ㄖㄥˊ 1174
  (const spell PROGMEM) {"b/3"}, // ㄖㄥˇ 1175
  (const spell PROGMEM) {"bj6"}, // ㄖㄨˊ 1176
  (const spell PROGMEM) {"bj3"}, // ㄖㄨˇ 1177
  (const spell PROGMEM) {"bj4"}, // ㄖㄨˋ 1178
  (const spell PROGMEM) {"bji6"}, // ㄖㄨㄛˊ 1179
  (const spell PROGMEM) {"bji4"}, // ㄖㄨㄛˋ 1180
  (const spell PROGMEM) {"bjo6"}, // ㄖㄨㄟˊ 1181
  (const spell PROGMEM) {"bjo3"}, // ㄖㄨㄟˇ 1182
  (const spell PROGMEM) {"bjo4"}, // ㄖㄨㄟˋ 1183
  (const spell PROGMEM) {"bj06"}, // ㄖㄨㄢˊ 1184
  (const spell PROGMEM) {"bj03"}, // ㄖㄨㄢˇ 1185
  (const spell PROGMEM) {"bjp4"}, // ㄖㄨㄣˋ 1186
  (const spell PROGMEM) {"bj/6"}, // ㄖㄨㄥˊ 1187
  (const spell PROGMEM) {"bj/3"}, // ㄖㄨㄥˇ 1188
  (const spell PROGMEM) {"bj/7"}, // ㄖㄨㄥ˙ 1189
  (const spell PROGMEM) {"y"}, // ㄗ 1190
  (const spell PROGMEM) {"y6"}, // ㄗˊ 1191
  (const spell PROGMEM) {"y3"}, // ㄗˇ 1192
  (const spell PROGMEM) {"y4"}, // ㄗˋ 1193
  (const spell PROGMEM) {"y7"}, // ㄗ˙ 1194
  (const spell PROGMEM) {"y8"}, // ㄗㄚ 1195
  (const spell PROGMEM) {"y86"}, // ㄗㄚˊ 1196
  (const spell PROGMEM) {"yk6"}, // ㄗㄜˊ 1197
  (const spell PROGMEM) {"yk3"}, // ㄗㄜˇ 1198
  (const spell PROGMEM) {"yk4"}, // ㄗㄜˋ 1199
  (const spell PROGMEM) {"y9"}, // ㄗㄞ 1200
  (const spell PROGMEM) {"y96"}, // ㄗㄞˊ 1201
  (const spell PROGMEM) {"y93"}, // ㄗㄞˇ 1202
  (const spell PROGMEM) {"y94"}, // ㄗㄞˋ 1203
  (const spell PROGMEM) {"yo6"}, // ㄗㄟˊ 1204
  (const spell PROGMEM) {"yl"}, // ㄗㄠ 1205
  (const spell PROGMEM) {"yl6"}, // ㄗㄠˊ 1206
  (const spell PROGMEM) {"yl3"}, // ㄗㄠˇ 1207
  (const spell PROGMEM) {"yl4"}, // ㄗㄠˋ 1208
  (const spell PROGMEM) {"y."}, // ㄗㄡ 1209
  (const spell PROGMEM) {"y.6"}, // ㄗㄡˊ 1210
  (const spell PROGMEM) {"y.3"}, // ㄗㄡˇ 1211
  (const spell PROGMEM) {"y.4"}, // ㄗㄡˋ 1212
  (const spell PROGMEM) {"y0"}, // ㄗㄢ 1213
  (const spell PROGMEM) {"y06"}, // ㄗㄢˊ 1214
  (const spell PROGMEM) {"y03"}, // ㄗㄢˇ 1215
  (const spell PROGMEM) {"y04"}, // ㄗㄢˋ 1216
  (const spell PROGMEM) {"yp"}, // ㄗㄣ 1217
  (const spell PROGMEM) {"yp3"}, // ㄗㄣˇ 1218
  (const spell PROGMEM) {"yp4"}, // ㄗㄣˋ 1219
  (const spell PROGMEM) {"y;"}, // ㄗㄤ 1220
  (const spell PROGMEM) {"y;6"}, // ㄗㄤˊ 1221
  (const spell PROGMEM) {"y;3"}, // ㄗㄤˇ 1222
  (const spell PROGMEM) {"y;4"}, // ㄗㄤˋ 1223
  (const spell PROGMEM) {"y/"}, // ㄗㄥ 1224
  (const spell PROGMEM) {"y/4"}, // ㄗㄥˋ 1225
  (const spell PROGMEM) {"yj"}, // ㄗㄨ 1226
  (const spell PROGMEM) {"yj6"}, // ㄗㄨˊ 1227
  (const spell PROGMEM) {"yj3"}, // ㄗㄨˇ 1228
  (const spell PROGMEM) {"yj4"}, // ㄗㄨˋ 1229
  (const spell PROGMEM) {"yji"}, // ㄗㄨㄛ 1230
  (const spell PROGMEM) {"yji6"}, // ㄗㄨㄛˊ 1231
  (const spell PROGMEM) {"yji3"}, // ㄗㄨㄛˇ 1232
  (const spell PROGMEM) {"yji4"}, // ㄗㄨㄛˋ 1233
  (const spell PROGMEM) {"yjo"}, // ㄗㄨㄟ 1234
  (const spell PROGMEM) {"yjo6"}, // ㄗㄨㄟˊ 1235
  (const spell PROGMEM) {"yjo3"}, // ㄗㄨㄟˇ 1236
  (const spell PROGMEM) {"yjo4"}, // ㄗㄨㄟˋ 1237
  (const spell PROGMEM) {"yj0"}, // ㄗㄨㄢ 1238
  (const spell PROGMEM) {"yj06"}, // ㄗㄨㄢˊ 1239
  (const spell PROGMEM) {"yj03"}, // ㄗㄨㄢˇ 1240
  (const spell PROGMEM) {"yj04"}, // ㄗㄨㄢˋ 1241
  (const spell PROGMEM) {"yjp"}, // ㄗㄨㄣ 1242
  (const spell PROGMEM) {"yjp6"}, // ㄗㄨㄣˊ 1243
  (const spell PROGMEM) {"yjp3"}, // ㄗㄨㄣˇ 1244
  (const spell PROGMEM) {"yjp4"}, // ㄗㄨㄣˋ 1245
  (const spell PROGMEM) {"yj/"}, // ㄗㄨㄥ 1246
  (const spell PROGMEM) {"yj/6"}, // ㄗㄨㄥˊ 1247
  (const spell PROGMEM) {"yj/3"}, // ㄗㄨㄥˇ 1248
  (const spell PROGMEM) {"yj/4"}, // ㄗㄨㄥˋ 1249
  (const spell PROGMEM) {"h"}, // ㄘ 1250
  (const spell PROGMEM) {"h6"}, // ㄘˊ 1251
  (const spell PROGMEM) {"h3"}, // ㄘˇ 1252
  (const spell PROGMEM) {"h4"}, // ㄘˋ 1253
  (const spell PROGMEM) {"h8"}, // ㄘㄚ 1254
  (const spell PROGMEM) {"h86"}, // ㄘㄚˊ 1255
  (const spell PROGMEM) {"h83"}, // ㄘㄚˇ 1256
  (const spell PROGMEM) {"hk4"}, // ㄘㄜˋ 1257
  (const spell PROGMEM) {"h9"}, // ㄘㄞ 1258
  (const spell PROGMEM) {"h96"}, // ㄘㄞˊ 1259
  (const spell PROGMEM) {"h93"}, // ㄘㄞˇ 1260
  (const spell PROGMEM) {"h94"}, // ㄘㄞˋ 1261
  (const spell PROGMEM) {"hl"}, // ㄘㄠ 1262
  (const spell PROGMEM) {"hl6"}, // ㄘㄠˊ 1263
  (const spell PROGMEM) {"hl3"}, // ㄘㄠˇ 1264
  (const spell PROGMEM) {"hl4"}, // ㄘㄠˋ 1265
  (const spell PROGMEM) {"h.4"}, // ㄘㄡˋ 1266
  (const spell PROGMEM) {"h0"}, // ㄘㄢ 1267
  (const spell PROGMEM) {"h06"}, // ㄘㄢˊ 1268
  (const spell PROGMEM) {"h03"}, // ㄘㄢˇ 1269
  (const spell PROGMEM) {"h04"}, // ㄘㄢˋ 1270
  (const spell PROGMEM) {"hp"}, // ㄘㄣ 1271
  (const spell PROGMEM) {"hp6"}, // ㄘㄣˊ 1272
  (const spell PROGMEM) {"h;"}, // ㄘㄤ 1273
  (const spell PROGMEM) {"h;6"}, // ㄘㄤˊ 1274
  (const spell PROGMEM) {"h;3"}, // ㄘㄤˇ 1275
  (const spell PROGMEM) {"h/"}, // ㄘㄥ 1276
  (const spell PROGMEM) {"h/6"}, // ㄘㄥˊ 1277
  (const spell PROGMEM) {"h/3"}, // ㄘㄥˇ 1278
  (const spell PROGMEM) {"h/4"}, // ㄘㄥˋ 1279
  (const spell PROGMEM) {"hj"}, // ㄘㄨ 1280
  (const spell PROGMEM) {"hj6"}, // ㄘㄨˊ 1281
  (const spell PROGMEM) {"hj4"}, // ㄘㄨˋ 1282
  (const spell PROGMEM) {"hji"}, // ㄘㄨㄛ 1283
  (const spell PROGMEM) {"hji6"}, // ㄘㄨㄛˊ 1284
  (const spell PROGMEM) {"hji3"}, // ㄘㄨㄛˇ 1285
  (const spell PROGMEM) {"hji4"}, // ㄘㄨㄛˋ 1286
  (const spell PROGMEM) {"hjo"}, // ㄘㄨㄟ 1287
  (const spell PROGMEM) {"hjo6"}, // ㄘㄨㄟˊ 1288
  (const spell PROGMEM) {"hjo3"}, // ㄘㄨㄟˇ 1289
  (const spell PROGMEM) {"hjo4"}, // ㄘㄨㄟˋ 1290
  (const spell PROGMEM) {"hj0"}, // ㄘㄨㄢ 1291
  (const spell PROGMEM) {"hj06"}, // ㄘㄨㄢˊ 1292
  (const spell PROGMEM) {"hj04"}, // ㄘㄨㄢˋ 1293
  (const spell PROGMEM) {"hjp"}, // ㄘㄨㄣ 1294
  (const spell PROGMEM) {"hjp6"}, // ㄘㄨㄣˊ 1295
  (const spell PROGMEM) {"hjp3"}, // ㄘㄨㄣˇ 1296
  (const spell PROGMEM) {"hjp4"}, // ㄘㄨㄣˋ 1297
  (const spell PROGMEM) {"hj/"}, // ㄘㄨㄥ 1298
  (const spell PROGMEM) {"hj/6"}, // ㄘㄨㄥˊ 1299
  (const spell PROGMEM) {"n"}, // ㄙ 1300
  (const spell PROGMEM) {"n6"}, // ㄙˊ 1301
  (const spell PROGMEM) {"n3"}, // ㄙˇ 1302
  (const spell PROGMEM) {"n4"}, // ㄙˋ 1303
  (const spell PROGMEM) {"n7"}, // ㄙ˙ 1304
  (const spell PROGMEM) {"n8"}, // ㄙㄚ 1305
  (const spell PROGMEM) {"n86"}, // ㄙㄚˊ 1306
  (const spell PROGMEM) {"n83"}, // ㄙㄚˇ 1307
  (const spell PROGMEM) {"n84"}, // ㄙㄚˋ 1308
  (const spell PROGMEM) {"n87"}, // ㄙㄚ˙ 1309
  (const spell PROGMEM) {"nk4"}, // ㄙㄜˋ 1310
  (const spell PROGMEM) {"n9"}, // ㄙㄞ 1311
  (const spell PROGMEM) {"n94"}, // ㄙㄞˋ 1312
  (const spell PROGMEM) {"no"}, // ㄙㄟ 1313
  (const spell PROGMEM) {"nl"}, // ㄙㄠ 1314
  (const spell PROGMEM) {"nl6"}, // ㄙㄠˊ 1315
  (const spell PROGMEM) {"nl3"}, // ㄙㄠˇ 1316
  (const spell PROGMEM) {"nl4"}, // ㄙㄠˋ 1317
  (const spell PROGMEM) {"n."}, // ㄙㄡ 1318
  (const spell PROGMEM) {"n.6"}, // ㄙㄡˊ 1319
  (const spell PROGMEM) {"n.3"}, // ㄙㄡˇ 1320
  (const spell PROGMEM) {"n.4"}, // ㄙㄡˋ 1321
  (const spell PROGMEM) {"n0"}, // ㄙㄢ 1322
  (const spell PROGMEM) {"n06"}, // ㄙㄢˊ 1323
  (const spell PROGMEM) {"n03"}, // ㄙㄢˇ 1324
  (const spell PROGMEM) {"n04"}, // ㄙㄢˋ 1325
  (const spell PROGMEM) {"np"}, // ㄙㄣ 1326
  (const spell PROGMEM) {"n;"}, // ㄙㄤ 1327
  (const spell PROGMEM) {"n;6"}, // ㄙㄤˊ 1328
  (const spell PROGMEM) {"n;3"}, // ㄙㄤˇ 1329
  (const spell PROGMEM) {"n;4"}, // ㄙㄤˋ 1330
  (const spell PROGMEM) {"n/"}, // ㄙㄥ 1331
  (const spell PROGMEM) {"nj"}, // ㄙㄨ 1332
  (const spell PROGMEM) {"nj6"}, // ㄙㄨˊ 1333
  (const spell PROGMEM) {"nj4"}, // ㄙㄨˋ 1334
  (const spell PROGMEM) {"nji"}, // ㄙㄨㄛ 1335
  (const spell PROGMEM) {"nji6"}, // ㄙㄨㄛˊ 1336
  (const spell PROGMEM) {"nji3"}, // ㄙㄨㄛˇ 1337
  (const spell PROGMEM) {"nji4"}, // ㄙㄨㄛˋ 1338
  (const spell PROGMEM) {"njo"}, // ㄙㄨㄟ 1339
  (const spell PROGMEM) {"njo6"}, // ㄙㄨㄟˊ 1340
  (const spell PROGMEM) {"njo3"}, // ㄙㄨㄟˇ 1341
  (const spell PROGMEM) {"njo4"}, // ㄙㄨㄟˋ 1342
  (const spell PROGMEM) {"nj0"}, // ㄙㄨㄢ 1343
  (const spell PROGMEM) {"nj06"}, // ㄙㄨㄢˊ 1344
  (const spell PROGMEM) {"nj03"}, // ㄙㄨㄢˇ 1345
  (const spell PROGMEM) {"nj04"}, // ㄙㄨㄢˋ 1346
  (const spell PROGMEM) {"njp"}, // ㄙㄨㄣ 1347
  (const spell PROGMEM) {"njp6"}, // ㄙㄨㄣˊ 1348
  (const spell PROGMEM) {"njp3"}, // ㄙㄨㄣˇ 1349
  (const spell PROGMEM) {"njp4"}, // ㄙㄨㄣˋ 1350
  (const spell PROGMEM) {"nj/"}, // ㄙㄨㄥ 1351
  (const spell PROGMEM) {"nj/6"}, // ㄙㄨㄥˊ 1352
  (const spell PROGMEM) {"nj/3"}, // ㄙㄨㄥˇ 1353
  (const spell PROGMEM) {"nj/4"}, // ㄙㄨㄥˋ 1354
  (const spell PROGMEM) {"8"}, // ㄚ 1355
  (const spell PROGMEM) {"86"}, // ㄚˊ 1356
  (const spell PROGMEM) {"83"}, // ㄚˇ 1357
  (const spell PROGMEM) {"84"}, // ㄚˋ 1358
  (const spell PROGMEM) {"87"}, // ㄚ˙ 1359
  (const spell PROGMEM) {"i"}, // ㄛ 1360
  (const spell PROGMEM) {"i6"}, // ㄛˊ 1361
  (const spell PROGMEM) {"i3"}, // ㄛˇ 1362
  (const spell PROGMEM) {"i4"}, // ㄛˋ 1363
  (const spell PROGMEM) {"i7"}, // ㄛ˙ 1364
  (const spell PROGMEM) {"k"}, // ㄜ 1365
  (const spell PROGMEM) {"k6"}, // ㄜˊ 1366
  (const spell PROGMEM) {"k3"}, // ㄜˇ 1367
  (const spell PROGMEM) {"k4"}, // ㄜˋ 1368
  (const spell PROGMEM) {","}, // ㄝ 1369
  (const spell PROGMEM) {",4"}, // ㄝˋ 1370
  (const spell PROGMEM) {"9"}, // ㄞ 1371
  (const spell PROGMEM) {"96"}, // ㄞˊ 1372
  (const spell PROGMEM) {"93"}, // ㄞˇ 1373
  (const spell PROGMEM) {"94"}, // ㄞˋ 1374
  (const spell PROGMEM) {"97"}, // ㄞ˙ 1375
  (const spell PROGMEM) {"o"}, // ㄟ 1376
  (const spell PROGMEM) {"o6"}, // ㄟˊ 1377
  (const spell PROGMEM) {"o3"}, // ㄟˇ 1378
  (const spell PROGMEM) {"o4"}, // ㄟˋ 1379
  (const spell PROGMEM) {"o7"}, // ㄟ˙ 1380
  (const spell PROGMEM) {"l"}, // ㄠ 1381
  (const spell PROGMEM) {"l6"}, // ㄠˊ 1382
  (const spell PROGMEM) {"l3"}, // ㄠˇ 1383
  (const spell PROGMEM) {"l4"}, // ㄠˋ 1384
  (const spell PROGMEM) {"."}, // ㄡ 1385
  (const spell PROGMEM) {".6"}, // ㄡˊ 1386
  (const spell PROGMEM) {".3"}, // ㄡˇ 1387
  (const spell PROGMEM) {".4"}, // ㄡˋ 1388
  (const spell PROGMEM) {"0"}, // ㄢ 1389
  (const spell PROGMEM) {"06"}, // ㄢˊ 1390
  (const spell PROGMEM) {"03"}, // ㄢˇ 1391
  (const spell PROGMEM) {"04"}, // ㄢˋ 1392
  (const spell PROGMEM) {"p"}, // ㄣ 1393
  (const spell PROGMEM) {"p4"}, // ㄣˋ 1394
  (const spell PROGMEM) {";"}, // ㄤ 1395
  (const spell PROGMEM) {";6"}, // ㄤˊ 1396
  (const spell PROGMEM) {";4"}, // ㄤˋ 1397
  (const spell PROGMEM) {"-"}, // ㄦ 1398
  (const spell PROGMEM) {"-6"}, // ㄦˊ 1399
  (const spell PROGMEM) {"-3"}, // ㄦˇ 1400
  (const spell PROGMEM) {"-4"}, // ㄦˋ 1401
  (const spell PROGMEM) {"u"}, // ㄧ 1402
  (const spell PROGMEM) {"u6"}, // ㄧˊ 1403
  (const spell PROGMEM) {"u3"}, // ㄧˇ 1404
  (const spell PROGMEM) {"u4"}, // ㄧˋ 1405
  (const spell PROGMEM) {"u8"}, // ㄧㄚ 1406
  (const spell PROGMEM) {"u86"}, // ㄧㄚˊ 1407
  (const spell PROGMEM) {"u83"}, // ㄧㄚˇ 1408
  (const spell PROGMEM) {"u84"}, // ㄧㄚˋ 1409
  (const spell PROGMEM) {"u87"}, // ㄧㄚ˙ 1410
  (const spell PROGMEM) {"ui"}, // ㄧㄛ 1411
  (const spell PROGMEM) {"ui4"}, // ㄧㄛˋ 1412
  (const spell PROGMEM) {"u,"}, // ㄧㄝ 1413
  (const spell PROGMEM) {"u,6"}, // ㄧㄝˊ 1414
  (const spell PROGMEM) {"u,3"}, // ㄧㄝˇ 1415
  (const spell PROGMEM) {"u,4"}, // ㄧㄝˋ 1416
  (const spell PROGMEM) {"u,7"}, // ㄧㄝ˙ 1417
  (const spell PROGMEM) {"u96"}, // ㄧㄞˊ 1418
  (const spell PROGMEM) {"ul"}, // ㄧㄠ 1419
  (const spell PROGMEM) {"ul6"}, // ㄧㄠˊ 1420
  (const spell PROGMEM) {"ul3"}, // ㄧㄠˇ 1421
  (const spell PROGMEM) {"ul4"}, // ㄧㄠˋ 1422
  (const spell PROGMEM) {"u."}, // ㄧㄡ 1423
  (const spell PROGMEM) {"u.6"}, // ㄧㄡˊ 1424
  (const spell PROGMEM) {"u.3"}, // ㄧㄡˇ 1425
  (const spell PROGMEM) {"u.4"}, // ㄧㄡˋ 1426
  (const spell PROGMEM) {"u0"}, // ㄧㄢ 1427
  (const spell PROGMEM) {"u06"}, // ㄧㄢˊ 1428
  (const spell PROGMEM) {"u03"}, // ㄧㄢˇ 1429
  (const spell PROGMEM) {"u04"}, // ㄧㄢˋ 1430
  (const spell PROGMEM) {"up"}, // ㄧㄣ 1431
  (const spell PROGMEM) {"up6"}, // ㄧㄣˊ 1432
  (const spell PROGMEM) {"up3"}, // ㄧㄣˇ 1433
  (const spell PROGMEM) {"up4"}, // ㄧㄣˋ 1434
  (const spell PROGMEM) {"u;"}, // ㄧㄤ 1435
  (const spell PROGMEM) {"u;6"}, // ㄧㄤˊ 1436
  (const spell PROGMEM) {"u;3"}, // ㄧㄤˇ 1437
  (const spell PROGMEM) {"u;4"}, // ㄧㄤˋ 1438
  (const spell PROGMEM) {"u/"}, // ㄧㄥ 1439
  (const spell PROGMEM) {"u/6"}, // ㄧㄥˊ 1440
  (const spell PROGMEM) {"u/3"}, // ㄧㄥˇ 1441
  (const spell PROGMEM) {"u/4"}, // ㄧㄥˋ 1442
  (const spell PROGMEM) {"j"}, // ㄨ 1443
  (const spell PROGMEM) {"j6"}, // ㄨˊ 1444
  (const spell PROGMEM) {"j3"}, // ㄨˇ 1445
  (const spell PROGMEM) {"j4"}, // ㄨˋ 1446
  (const spell PROGMEM) {"j8"}, // ㄨㄚ 1447
  (const spell PROGMEM) {"j86"}, // ㄨㄚˊ 1448
  (const spell PROGMEM) {"j83"}, // ㄨㄚˇ 1449
  (const spell PROGMEM) {"j84"}, // ㄨㄚˋ 1450
  (const spell PROGMEM) {"j87"}, // ㄨㄚ˙ 1451
  (const spell PROGMEM) {"ji"}, // ㄨㄛ 1452
  (const spell PROGMEM) {"ji6"}, // ㄨㄛˊ 1453
  (const spell PROGMEM) {"ji3"}, // ㄨㄛˇ 1454
  (const spell PROGMEM) {"ji4"}, // ㄨㄛˋ 1455
  (const spell PROGMEM) {"j9"}, // ㄨㄞ 1456
  (const spell PROGMEM) {"j93"}, // ㄨㄞˇ 1457
  (const spell PROGMEM) {"j94"}, // ㄨㄞˋ 1458
  (const spell PROGMEM) {"jo"}, // ㄨㄟ 1459
  (const spell PROGMEM) {"jo6"}, // ㄨㄟˊ 1460
  (const spell PROGMEM) {"jo3"}, // ㄨㄟˇ 1461
  (const spell PROGMEM) {"jo4"}, // ㄨㄟˋ 1462
  (const spell PROGMEM) {"j0"}, // ㄨㄢ 1463
  (const spell PROGMEM) {"j06"}, // ㄨㄢˊ 1464
  (const spell PROGMEM) {"j03"}, // ㄨㄢˇ 1465
  (const spell PROGMEM) {"j04"}, // ㄨㄢˋ 1466
  (const spell PROGMEM) {"jp"}, // ㄨㄣ 1467
  (const spell PROGMEM) {"jp6"}, // ㄨㄣˊ 1468
  (const spell PROGMEM) {"jp3"}, // ㄨㄣˇ 1469
  (const spell PROGMEM) {"jp4"}, // ㄨㄣˋ 1470
  (const spell PROGMEM) {"j;"}, // ㄨㄤ 1471
  (const spell PROGMEM) {"j;6"}, // ㄨㄤˊ 1472
  (const spell PROGMEM) {"j;3"}, // ㄨㄤˇ 1473
  (const spell PROGMEM) {"j;4"}, // ㄨㄤˋ 1474
  (const spell PROGMEM) {"j/"}, // ㄨㄥ 1475
  (const spell PROGMEM) {"j/6"}, // ㄨㄥˊ 1476
  (const spell PROGMEM) {"j/3"}, // ㄨㄥˇ 1477
  (const spell PROGMEM) {"j/4"}, // ㄨㄥˋ 1478
  (const spell PROGMEM) {"m"}, // ㄩ 1479
  (const spell PROGMEM) {"m6"}, // ㄩˊ 1480
  (const spell PROGMEM) {"m3"}, // ㄩˇ 1481
  (const spell PROGMEM) {"m4"}, // ㄩˋ 1482
  (const spell PROGMEM) {"m,"}, // ㄩㄝ 1483
  (const spell PROGMEM) {"m,4"}, // ㄩㄝˋ 1484
  (const spell PROGMEM) {"m0"}, // ㄩㄢ 1485
  (const spell PROGMEM) {"m06"}, // ㄩㄢˊ 1486
  (const spell PROGMEM) {"m03"}, // ㄩㄢˇ 1487
  (const spell PROGMEM) {"m04"}, // ㄩㄢˋ 1488
  (const spell PROGMEM) {"mp"}, // ㄩㄣ 1489
  (const spell PROGMEM) {"mp6"}, // ㄩㄣˊ 1490
  (const spell PROGMEM) {"mp3"}, // ㄩㄣˇ 1491
  (const spell PROGMEM) {"mp4"}, // ㄩㄣˋ 1492
  (const spell PROGMEM) {"m/"}, // ㄩㄥ 1493
  (const spell PROGMEM) {"m/6"}, // ㄩㄥˊ 1494
  (const spell PROGMEM) {"m/3"}, // ㄩㄥˇ 1495
  (const spell PROGMEM) {"m/4"}, // ㄩㄥˋ 1496

  (const spell PROGMEM) {""},      // End Guard
};





#endif
