/*
  Copyright (c) 2019 Arnix Chen All right reserved.
  This is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public
  License as published by the Free Software Foundation; either
  version 3.0 of the License, or (at your option) any later version.
  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.
  You should have received a copy of the GNU General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

  Modified 05-03-2019 by Arnix Chen
*/

#ifndef __SPELL_LIST__
#define __SPELL_LIST__

// A spell(word) is formed of a series of chewin notes.
typedef struct {
  char keys[spellBufferSize];
} spell;

const spell spellList[] PROGMEM = {
  (const spell PROGMEM) {"1"}, // ㄅ 11
  (const spell PROGMEM) {"q"}, // ㄆ 12
  (const spell PROGMEM) {"a"}, // ㄇ 13
  (const spell PROGMEM) {"z"}, // ㄈ 14
  (const spell PROGMEM) {"2"}, // ㄉ 15
  (const spell PROGMEM) {"w"}, // ㄊ 16
  (const spell PROGMEM) {"s"}, // ㄋ 17
  (const spell PROGMEM) {"x"}, // ㄌ 18
  (const spell PROGMEM) {"e"}, // ㄍ 19
  (const spell PROGMEM) {"d"}, // ㄎ 20
  (const spell PROGMEM) {"c"}, // ㄏ 21
  (const spell PROGMEM) {"r"}, // ㄐ 22
  (const spell PROGMEM) {"f"}, // ㄑ 23
  (const spell PROGMEM) {"v"}, // ㄒ 24
  (const spell PROGMEM) {"5"}, // ㄓ 25
  (const spell PROGMEM) {"t"}, // ㄔ 26
  (const spell PROGMEM) {"g"}, // ㄕ 27
  (const spell PROGMEM) {"b"}, // ㄖ 28
  (const spell PROGMEM) {"y"}, // ㄗ 29
  (const spell PROGMEM) {"h"}, // ㄘ 30
  (const spell PROGMEM) {"n"}, // ㄙ 31
  (const spell PROGMEM) {"u"}, // ㄧ 32
  (const spell PROGMEM) {"j"}, // ㄨ 33
  (const spell PROGMEM) {"m"}, // ㄩ 34
  (const spell PROGMEM) {"8"}, // ㄚ 35
  (const spell PROGMEM) {"i"}, // ㄛ 36
  (const spell PROGMEM) {"k"}, // ㄜ 37
  (const spell PROGMEM) {","}, // ㄝ 38
  (const spell PROGMEM) {"9"}, // ㄞ 39
  (const spell PROGMEM) {"o"}, // ㄟ 40
  (const spell PROGMEM) {"l"}, // ㄠ 41
  (const spell PROGMEM) {"."}, // ㄡ 42
  (const spell PROGMEM) {"0"}, // ㄢ 43
  (const spell PROGMEM) {"p"}, // ㄣ 44
  (const spell PROGMEM) {";"}, // ㄤ 45
  (const spell PROGMEM) {"/"}, // ㄥ 46
  (const spell PROGMEM) {"-"}, // ㄦ 47
  (const spell PROGMEM) {"18"}, // ㄅㄚ 48
  (const spell PROGMEM) {"186"}, // ㄅㄚˊ 49
  (const spell PROGMEM) {"183"}, // ㄅㄚˇ 50
  (const spell PROGMEM) {"184"}, // ㄅㄚˋ 51
  (const spell PROGMEM) {"187"}, // ㄅㄚ˙ 52
  (const spell PROGMEM) {"1i"}, // ㄅㄛ 53
  (const spell PROGMEM) {"1i6"}, // ㄅㄛˊ 54
  (const spell PROGMEM) {"1i3"}, // ㄅㄛˇ 55
  (const spell PROGMEM) {"1i4"}, // ㄅㄛˋ 56
  (const spell PROGMEM) {"1i7"}, // ㄅㄛ˙ 57
  (const spell PROGMEM) {"19"}, // ㄅㄞ 58
  (const spell PROGMEM) {"196"}, // ㄅㄞˊ 59
  (const spell PROGMEM) {"193"}, // ㄅㄞˇ 60
  (const spell PROGMEM) {"194"}, // ㄅㄞˋ 61
  (const spell PROGMEM) {"1o"}, // ㄅㄟ 62
  (const spell PROGMEM) {"1o6"}, // ㄅㄟˊ 63
  (const spell PROGMEM) {"1o3"}, // ㄅㄟˇ 64
  (const spell PROGMEM) {"1o4"}, // ㄅㄟˋ 65
  (const spell PROGMEM) {"1o7"}, // ㄅㄟ˙ 66
  (const spell PROGMEM) {"1l"}, // ㄅㄠ 67
  (const spell PROGMEM) {"1l6"}, // ㄅㄠˊ 68
  (const spell PROGMEM) {"1l3"}, // ㄅㄠˇ 69
  (const spell PROGMEM) {"1l4"}, // ㄅㄠˋ 70
  (const spell PROGMEM) {"1l7"}, // ㄅㄠ˙ 71
  (const spell PROGMEM) {"10"}, // ㄅㄢ 72
  (const spell PROGMEM) {"106"}, // ㄅㄢˊ 73
  (const spell PROGMEM) {"103"}, // ㄅㄢˇ 74
  (const spell PROGMEM) {"104"}, // ㄅㄢˋ 75
  (const spell PROGMEM) {"1p"}, // ㄅㄣ 76
  (const spell PROGMEM) {"1p3"}, // ㄅㄣˇ 77
  (const spell PROGMEM) {"1p4"}, // ㄅㄣˋ 78
  (const spell PROGMEM) {"1;"}, // ㄅㄤ 79
  (const spell PROGMEM) {"1;3"}, // ㄅㄤˇ 80
  (const spell PROGMEM) {"1;4"}, // ㄅㄤˋ 81
  (const spell PROGMEM) {"1/"}, // ㄅㄥ 82
  (const spell PROGMEM) {"1/6"}, // ㄅㄥˊ 83
  (const spell PROGMEM) {"1/3"}, // ㄅㄥˇ 84
  (const spell PROGMEM) {"1/4"}, // ㄅㄥˋ 85
  (const spell PROGMEM) {"1u"}, // ㄅㄧ 86
  (const spell PROGMEM) {"1u6"}, // ㄅㄧˊ 87
  (const spell PROGMEM) {"1u3"}, // ㄅㄧˇ 88
  (const spell PROGMEM) {"1u4"}, // ㄅㄧˋ 89
  (const spell PROGMEM) {"1u7"}, // ㄅㄧ˙ 90
  (const spell PROGMEM) {"1u,"}, // ㄅㄧㄝ 91
  (const spell PROGMEM) {"1u,6"}, // ㄅㄧㄝˊ 92
  (const spell PROGMEM) {"1u,3"}, // ㄅㄧㄝˇ 93
  (const spell PROGMEM) {"1u,4"}, // ㄅㄧㄝˋ 94
  (const spell PROGMEM) {"1ul"}, // ㄅㄧㄠ 95
  (const spell PROGMEM) {"1ul6"}, // ㄅㄧㄠˊ 96
  (const spell PROGMEM) {"1ul3"}, // ㄅㄧㄠˇ 97
  (const spell PROGMEM) {"1ul4"}, // ㄅㄧㄠˋ 98
  (const spell PROGMEM) {"1u0"}, // ㄅㄧㄢ 99
  (const spell PROGMEM) {"1u06"}, // ㄅㄧㄢˊ 100
  (const spell PROGMEM) {"1u03"}, // ㄅㄧㄢˇ 101
  (const spell PROGMEM) {"1u04"}, // ㄅㄧㄢˋ 102
  (const spell PROGMEM) {"1up"}, // ㄅㄧㄣ 103
  (const spell PROGMEM) {"1up6"}, // ㄅㄧㄣˊ 104
  (const spell PROGMEM) {"1up3"}, // ㄅㄧㄣˇ 105
  (const spell PROGMEM) {"1up4"}, // ㄅㄧㄣˋ 106
  (const spell PROGMEM) {"1u/"}, // ㄅㄧㄥ 107
  (const spell PROGMEM) {"1u/6"}, // ㄅㄧㄥˊ 108
  (const spell PROGMEM) {"1u/3"}, // ㄅㄧㄥˇ 109
  (const spell PROGMEM) {"1u/4"}, // ㄅㄧㄥˋ 110
  (const spell PROGMEM) {"1j"}, // ㄅㄨ 111
  (const spell PROGMEM) {"1j6"}, // ㄅㄨˊ 112
  (const spell PROGMEM) {"1j3"}, // ㄅㄨˇ 113
  (const spell PROGMEM) {"1j4"}, // ㄅㄨˋ 114
  (const spell PROGMEM) {"q8"}, // ㄆㄚ 115
  (const spell PROGMEM) {"q86"}, // ㄆㄚˊ 116
  (const spell PROGMEM) {"q84"}, // ㄆㄚˋ 117
  (const spell PROGMEM) {"qi"}, // ㄆㄛ 118
  (const spell PROGMEM) {"qi6"}, // ㄆㄛˊ 119
  (const spell PROGMEM) {"qi3"}, // ㄆㄛˇ 120
  (const spell PROGMEM) {"qi4"}, // ㄆㄛˋ 121
  (const spell PROGMEM) {"q9"}, // ㄆㄞ 122
  (const spell PROGMEM) {"q96"}, // ㄆㄞˊ 123
  (const spell PROGMEM) {"q93"}, // ㄆㄞˇ 124
  (const spell PROGMEM) {"q94"}, // ㄆㄞˋ 125
  (const spell PROGMEM) {"qo"}, // ㄆㄟ 126
  (const spell PROGMEM) {"qo6"}, // ㄆㄟˊ 127
  (const spell PROGMEM) {"qo4"}, // ㄆㄟˋ 128
  (const spell PROGMEM) {"ql"}, // ㄆㄠ 129
  (const spell PROGMEM) {"ql6"}, // ㄆㄠˊ 130
  (const spell PROGMEM) {"ql3"}, // ㄆㄠˇ 131
  (const spell PROGMEM) {"ql4"}, // ㄆㄠˋ 132
  (const spell PROGMEM) {"q."}, // ㄆㄡ 133
  (const spell PROGMEM) {"q.6"}, // ㄆㄡˊ 134
  (const spell PROGMEM) {"q.3"}, // ㄆㄡˇ 135
  (const spell PROGMEM) {"q0"}, // ㄆㄢ 136
  (const spell PROGMEM) {"q06"}, // ㄆㄢˊ 137
  (const spell PROGMEM) {"q04"}, // ㄆㄢˋ 138
  (const spell PROGMEM) {"qp"}, // ㄆㄣ 139
  (const spell PROGMEM) {"qp6"}, // ㄆㄣˊ 140
  (const spell PROGMEM) {"qp4"}, // ㄆㄣˋ 141
  (const spell PROGMEM) {"q;"}, // ㄆㄤ 142
  (const spell PROGMEM) {"q;6"}, // ㄆㄤˊ 143
  (const spell PROGMEM) {"q;3"}, // ㄆㄤˇ 144
  (const spell PROGMEM) {"q;4"}, // ㄆㄤˋ 145
  (const spell PROGMEM) {"q/"}, // ㄆㄥ 146
  (const spell PROGMEM) {"q/6"}, // ㄆㄥˊ 147
  (const spell PROGMEM) {"q/3"}, // ㄆㄥˇ 148
  (const spell PROGMEM) {"q/4"}, // ㄆㄥˋ 149
  (const spell PROGMEM) {"qu"}, // ㄆㄧ 150
  (const spell PROGMEM) {"qu6"}, // ㄆㄧˊ 151
  (const spell PROGMEM) {"qu3"}, // ㄆㄧˇ 152
  (const spell PROGMEM) {"qu4"}, // ㄆㄧˋ 153
  (const spell PROGMEM) {"qu8"}, // ㄆㄧㄚ 154
  (const spell PROGMEM) {"qu,"}, // ㄆㄧㄝ 155
  (const spell PROGMEM) {"qu,6"}, // ㄆㄧㄝˊ 156
  (const spell PROGMEM) {"qu,3"}, // ㄆㄧㄝˇ 157
  (const spell PROGMEM) {"qu,4"}, // ㄆㄧㄝˋ 158
  (const spell PROGMEM) {"qul"}, // ㄆㄧㄠ 159
  (const spell PROGMEM) {"qul6"}, // ㄆㄧㄠˊ 160
  (const spell PROGMEM) {"qul3"}, // ㄆㄧㄠˇ 161
  (const spell PROGMEM) {"qul4"}, // ㄆㄧㄠˋ 162
  (const spell PROGMEM) {"qu0"}, // ㄆㄧㄢ 163
  (const spell PROGMEM) {"qu06"}, // ㄆㄧㄢˊ 164
  (const spell PROGMEM) {"qu03"}, // ㄆㄧㄢˇ 165
  (const spell PROGMEM) {"qu04"}, // ㄆㄧㄢˋ 166
  (const spell PROGMEM) {"qup"}, // ㄆㄧㄣ 167
  (const spell PROGMEM) {"qup6"}, // ㄆㄧㄣˊ 168
  (const spell PROGMEM) {"qup3"}, // ㄆㄧㄣˇ 169
  (const spell PROGMEM) {"qup4"}, // ㄆㄧㄣˋ 170
  (const spell PROGMEM) {"qu/"}, // ㄆㄧㄥ 171
  (const spell PROGMEM) {"qu/6"}, // ㄆㄧㄥˊ 172
  (const spell PROGMEM) {"qj"}, // ㄆㄨ 173
  (const spell PROGMEM) {"qj6"}, // ㄆㄨˊ 174
  (const spell PROGMEM) {"qj3"}, // ㄆㄨˇ 175
  (const spell PROGMEM) {"qj4"}, // ㄆㄨˋ 176
  (const spell PROGMEM) {"a8"}, // ㄇㄚ 177
  (const spell PROGMEM) {"a86"}, // ㄇㄚˊ 178
  (const spell PROGMEM) {"a83"}, // ㄇㄚˇ 179
  (const spell PROGMEM) {"a84"}, // ㄇㄚˋ 180
  (const spell PROGMEM) {"a87"}, // ㄇㄚ˙ 181
  (const spell PROGMEM) {"ai"}, // ㄇㄛ 182
  (const spell PROGMEM) {"ai6"}, // ㄇㄛˊ 183
  (const spell PROGMEM) {"ai3"}, // ㄇㄛˇ 184
  (const spell PROGMEM) {"ai4"}, // ㄇㄛˋ 185
  (const spell PROGMEM) {"ak7"}, // ㄇㄜ˙ 186
  (const spell PROGMEM) {"a96"}, // ㄇㄞˊ 187
  (const spell PROGMEM) {"a93"}, // ㄇㄞˇ 188
  (const spell PROGMEM) {"a94"}, // ㄇㄞˋ 189
  (const spell PROGMEM) {"ao"}, // ㄇㄟ 190
  (const spell PROGMEM) {"ao6"}, // ㄇㄟˊ 191
  (const spell PROGMEM) {"ao3"}, // ㄇㄟˇ 192
  (const spell PROGMEM) {"ao4"}, // ㄇㄟˋ 193
  (const spell PROGMEM) {"ao7"}, // ㄇㄟ˙ 194
  (const spell PROGMEM) {"al"}, // ㄇㄠ 195
  (const spell PROGMEM) {"al6"}, // ㄇㄠˊ 196
  (const spell PROGMEM) {"al3"}, // ㄇㄠˇ 197
  (const spell PROGMEM) {"al4"}, // ㄇㄠˋ 198
  (const spell PROGMEM) {"a."}, // ㄇㄡ 199
  (const spell PROGMEM) {"a.6"}, // ㄇㄡˊ 200
  (const spell PROGMEM) {"a.3"}, // ㄇㄡˇ 201
  (const spell PROGMEM) {"a.4"}, // ㄇㄡˋ 202
  (const spell PROGMEM) {"a0"}, // ㄇㄢ 203
  (const spell PROGMEM) {"a06"}, // ㄇㄢˊ 204
  (const spell PROGMEM) {"a03"}, // ㄇㄢˇ 205
  (const spell PROGMEM) {"a04"}, // ㄇㄢˋ 206
  (const spell PROGMEM) {"ap"}, // ㄇㄣ 207
  (const spell PROGMEM) {"ap6"}, // ㄇㄣˊ 208
  (const spell PROGMEM) {"ap4"}, // ㄇㄣˋ 209
  (const spell PROGMEM) {"ap7"}, // ㄇㄣ˙ 210
  (const spell PROGMEM) {"a;6"}, // ㄇㄤˊ 211
  (const spell PROGMEM) {"a;3"}, // ㄇㄤˇ 212
  (const spell PROGMEM) {"a/"}, // ㄇㄥ 213
  (const spell PROGMEM) {"a/6"}, // ㄇㄥˊ 214
  (const spell PROGMEM) {"a/3"}, // ㄇㄥˇ 215
  (const spell PROGMEM) {"a/4"}, // ㄇㄥˋ 216
  (const spell PROGMEM) {"au"}, // ㄇㄧ 217
  (const spell PROGMEM) {"au6"}, // ㄇㄧˊ 218
  (const spell PROGMEM) {"au3"}, // ㄇㄧˇ 219
  (const spell PROGMEM) {"au4"}, // ㄇㄧˋ 220
  (const spell PROGMEM) {"au,"}, // ㄇㄧㄝ 221
  (const spell PROGMEM) {"au,4"}, // ㄇㄧㄝˋ 222
  (const spell PROGMEM) {"aul"}, // ㄇㄧㄠ 223
  (const spell PROGMEM) {"aul6"}, // ㄇㄧㄠˊ 224
  (const spell PROGMEM) {"aul3"}, // ㄇㄧㄠˇ 225
  (const spell PROGMEM) {"aul4"}, // ㄇㄧㄠˋ 226
  (const spell PROGMEM) {"au.4"}, // ㄇㄧㄡˋ 227
  (const spell PROGMEM) {"au06"}, // ㄇㄧㄢˊ 228
  (const spell PROGMEM) {"au03"}, // ㄇㄧㄢˇ 229
  (const spell PROGMEM) {"au04"}, // ㄇㄧㄢˋ 230
  (const spell PROGMEM) {"aup6"}, // ㄇㄧㄣˊ 231
  (const spell PROGMEM) {"aup3"}, // ㄇㄧㄣˇ 232
  (const spell PROGMEM) {"au/6"}, // ㄇㄧㄥˊ 233
  (const spell PROGMEM) {"au/3"}, // ㄇㄧㄥˇ 234
  (const spell PROGMEM) {"au/4"}, // ㄇㄧㄥˋ 235
  (const spell PROGMEM) {"aj6"}, // ㄇㄨˊ 236
  (const spell PROGMEM) {"aj3"}, // ㄇㄨˇ 237
  (const spell PROGMEM) {"aj4"}, // ㄇㄨˋ 238
  (const spell PROGMEM) {"z8"}, // ㄈㄚ 239
  (const spell PROGMEM) {"z86"}, // ㄈㄚˊ 240
  (const spell PROGMEM) {"z83"}, // ㄈㄚˇ 241
  (const spell PROGMEM) {"z84"}, // ㄈㄚˋ 242
  (const spell PROGMEM) {"zi6"}, // ㄈㄛˊ 243
  (const spell PROGMEM) {"zi4"}, // ㄈㄛˋ 244
  (const spell PROGMEM) {"zo"}, // ㄈㄟ 245
  (const spell PROGMEM) {"zo6"}, // ㄈㄟˊ 246
  (const spell PROGMEM) {"zo3"}, // ㄈㄟˇ 247
  (const spell PROGMEM) {"zo4"}, // ㄈㄟˋ 248
  (const spell PROGMEM) {"z.6"}, // ㄈㄡˊ 249
  (const spell PROGMEM) {"z.3"}, // ㄈㄡˇ 250
  (const spell PROGMEM) {"z0"}, // ㄈㄢ 251
  (const spell PROGMEM) {"z06"}, // ㄈㄢˊ 252
  (const spell PROGMEM) {"z03"}, // ㄈㄢˇ 253
  (const spell PROGMEM) {"z04"}, // ㄈㄢˋ 254
  (const spell PROGMEM) {"zp"}, // ㄈㄣ 255
  (const spell PROGMEM) {"zp6"}, // ㄈㄣˊ 256
  (const spell PROGMEM) {"zp3"}, // ㄈㄣˇ 257
  (const spell PROGMEM) {"zp4"}, // ㄈㄣˋ 258
  (const spell PROGMEM) {"z;"}, // ㄈㄤ 259
  (const spell PROGMEM) {"z;6"}, // ㄈㄤˊ 260
  (const spell PROGMEM) {"z;3"}, // ㄈㄤˇ 261
  (const spell PROGMEM) {"z;4"}, // ㄈㄤˋ 262
  (const spell PROGMEM) {"z/"}, // ㄈㄥ 263
  (const spell PROGMEM) {"z/6"}, // ㄈㄥˊ 264
  (const spell PROGMEM) {"z/3"}, // ㄈㄥˇ 265
  (const spell PROGMEM) {"z/4"}, // ㄈㄥˋ 266
  (const spell PROGMEM) {"zj"}, // ㄈㄨ 267
  (const spell PROGMEM) {"zj6"}, // ㄈㄨˊ 268
  (const spell PROGMEM) {"zj3"}, // ㄈㄨˇ 269
  (const spell PROGMEM) {"zj4"}, // ㄈㄨˋ 270
  (const spell PROGMEM) {"28"}, // ㄉㄚ 271
  (const spell PROGMEM) {"286"}, // ㄉㄚˊ 272
  (const spell PROGMEM) {"283"}, // ㄉㄚˇ 273
  (const spell PROGMEM) {"284"}, // ㄉㄚˋ 274
  (const spell PROGMEM) {"2k6"}, // ㄉㄜˊ 275
  (const spell PROGMEM) {"2k7"}, // ㄉㄜ˙ 276
  (const spell PROGMEM) {"29"}, // ㄉㄞ 277
  (const spell PROGMEM) {"293"}, // ㄉㄞˇ 278
  (const spell PROGMEM) {"294"}, // ㄉㄞˋ 279
  (const spell PROGMEM) {"2o6"}, // ㄉㄟˊ 280
  (const spell PROGMEM) {"2o3"}, // ㄉㄟˇ 281
  (const spell PROGMEM) {"2l"}, // ㄉㄠ 282
  (const spell PROGMEM) {"2l6"}, // ㄉㄠˊ 283
  (const spell PROGMEM) {"2l3"}, // ㄉㄠˇ 284
  (const spell PROGMEM) {"2l4"}, // ㄉㄠˋ 285
  (const spell PROGMEM) {"2."}, // ㄉㄡ 286
  (const spell PROGMEM) {"2.6"}, // ㄉㄡˊ 287
  (const spell PROGMEM) {"2.3"}, // ㄉㄡˇ 288
  (const spell PROGMEM) {"2.4"}, // ㄉㄡˋ 289
  (const spell PROGMEM) {"20"}, // ㄉㄢ 290
  (const spell PROGMEM) {"206"}, // ㄉㄢˊ 291
  (const spell PROGMEM) {"203"}, // ㄉㄢˇ 292
  (const spell PROGMEM) {"204"}, // ㄉㄢˋ 293
  (const spell PROGMEM) {"2;"}, // ㄉㄤ 294
  (const spell PROGMEM) {"2;6"}, // ㄉㄤˊ 295
  (const spell PROGMEM) {"2;3"}, // ㄉㄤˇ 296
  (const spell PROGMEM) {"2;4"}, // ㄉㄤˋ 297
  (const spell PROGMEM) {"2/"}, // ㄉㄥ 298
  (const spell PROGMEM) {"2/6"}, // ㄉㄥˊ 299
  (const spell PROGMEM) {"2/3"}, // ㄉㄥˇ 300
  (const spell PROGMEM) {"2/4"}, // ㄉㄥˋ 301
  (const spell PROGMEM) {"2u"}, // ㄉㄧ 302
  (const spell PROGMEM) {"2u6"}, // ㄉㄧˊ 303
  (const spell PROGMEM) {"2u3"}, // ㄉㄧˇ 304
  (const spell PROGMEM) {"2u4"}, // ㄉㄧˋ 305
  (const spell PROGMEM) {"2u7"}, // ㄉㄧ˙ 306
  (const spell PROGMEM) {"2u,"}, // ㄉㄧㄝ 307
  (const spell PROGMEM) {"2u,6"}, // ㄉㄧㄝˊ 308
  (const spell PROGMEM) {"2u,7"}, // ㄉㄧㄝ˙ 309
  (const spell PROGMEM) {"2ul"}, // ㄉㄧㄠ 310
  (const spell PROGMEM) {"2ul3"}, // ㄉㄧㄠˇ 311
  (const spell PROGMEM) {"2ul4"}, // ㄉㄧㄠˋ 312
  (const spell PROGMEM) {"2u."}, // ㄉㄧㄡ 313
  (const spell PROGMEM) {"2u0"}, // ㄉㄧㄢ 314
  (const spell PROGMEM) {"2u06"}, // ㄉㄧㄢˊ 315
  (const spell PROGMEM) {"2u03"}, // ㄉㄧㄢˇ 316
  (const spell PROGMEM) {"2u04"}, // ㄉㄧㄢˋ 317
  (const spell PROGMEM) {"2u;"}, // ㄉㄧㄤ 318
  (const spell PROGMEM) {"2u/"}, // ㄉㄧㄥ 319
  (const spell PROGMEM) {"2u/6"}, // ㄉㄧㄥˊ 320
  (const spell PROGMEM) {"2u/3"}, // ㄉㄧㄥˇ 321
  (const spell PROGMEM) {"2u/4"}, // ㄉㄧㄥˋ 322
  (const spell PROGMEM) {"2j"}, // ㄉㄨ 323
  (const spell PROGMEM) {"2j6"}, // ㄉㄨˊ 324
  (const spell PROGMEM) {"2j3"}, // ㄉㄨˇ 325
  (const spell PROGMEM) {"2j4"}, // ㄉㄨˋ 326
  (const spell PROGMEM) {"2ji"}, // ㄉㄨㄛ 327
  (const spell PROGMEM) {"2ji6"}, // ㄉㄨㄛˊ 328
  (const spell PROGMEM) {"2ji3"}, // ㄉㄨㄛˇ 329
  (const spell PROGMEM) {"2ji4"}, // ㄉㄨㄛˋ 330
  (const spell PROGMEM) {"2ji7"}, // ㄉㄨㄛ˙ 331
  (const spell PROGMEM) {"2jo"}, // ㄉㄨㄟ 332
  (const spell PROGMEM) {"2jo4"}, // ㄉㄨㄟˋ 333
  (const spell PROGMEM) {"2j0"}, // ㄉㄨㄢ 334
  (const spell PROGMEM) {"2j06"}, // ㄉㄨㄢˊ 335
  (const spell PROGMEM) {"2j03"}, // ㄉㄨㄢˇ 336
  (const spell PROGMEM) {"2j04"}, // ㄉㄨㄢˋ 337
  (const spell PROGMEM) {"2jp"}, // ㄉㄨㄣ 338
  (const spell PROGMEM) {"2jp3"}, // ㄉㄨㄣˇ 339
  (const spell PROGMEM) {"2jp4"}, // ㄉㄨㄣˋ 340
  (const spell PROGMEM) {"2j/"}, // ㄉㄨㄥ 341
  (const spell PROGMEM) {"2j/3"}, // ㄉㄨㄥˇ 342
  (const spell PROGMEM) {"2j/4"}, // ㄉㄨㄥˋ 343
  (const spell PROGMEM) {"w8"}, // ㄊㄚ 344
  (const spell PROGMEM) {"w86"}, // ㄊㄚˊ 345
  (const spell PROGMEM) {"w83"}, // ㄊㄚˇ 346
  (const spell PROGMEM) {"w84"}, // ㄊㄚˋ 347
  (const spell PROGMEM) {"wk"}, // ㄊㄜ 348
  (const spell PROGMEM) {"wk4"}, // ㄊㄜˋ 349
  (const spell PROGMEM) {"w9"}, // ㄊㄞ 350
  (const spell PROGMEM) {"w96"}, // ㄊㄞˊ 351
  (const spell PROGMEM) {"w94"}, // ㄊㄞˋ 352
  (const spell PROGMEM) {"wl"}, // ㄊㄠ 353
  (const spell PROGMEM) {"wl6"}, // ㄊㄠˊ 354
  (const spell PROGMEM) {"wl3"}, // ㄊㄠˇ 355
  (const spell PROGMEM) {"wl4"}, // ㄊㄠˋ 356
  (const spell PROGMEM) {"wl7"}, // ㄊㄠ˙ 357
  (const spell PROGMEM) {"w."}, // ㄊㄡ 358
  (const spell PROGMEM) {"w.6"}, // ㄊㄡˊ 359
  (const spell PROGMEM) {"w.3"}, // ㄊㄡˇ 360
  (const spell PROGMEM) {"w.4"}, // ㄊㄡˋ 361
  (const spell PROGMEM) {"w.7"}, // ㄊㄡ˙ 362
  (const spell PROGMEM) {"w0"}, // ㄊㄢ 363
  (const spell PROGMEM) {"w06"}, // ㄊㄢˊ 364
  (const spell PROGMEM) {"w03"}, // ㄊㄢˇ 365
  (const spell PROGMEM) {"w04"}, // ㄊㄢˋ 366
  (const spell PROGMEM) {"w;"}, // ㄊㄤ 367
  (const spell PROGMEM) {"w;6"}, // ㄊㄤˊ 368
  (const spell PROGMEM) {"w;3"}, // ㄊㄤˇ 369
  (const spell PROGMEM) {"w;4"}, // ㄊㄤˋ 370
  (const spell PROGMEM) {"w/"}, // ㄊㄥ 371
  (const spell PROGMEM) {"w/6"}, // ㄊㄥˊ 372
  (const spell PROGMEM) {"wu"}, // ㄊㄧ 373
  (const spell PROGMEM) {"wu6"}, // ㄊㄧˊ 374
  (const spell PROGMEM) {"wu3"}, // ㄊㄧˇ 375
  (const spell PROGMEM) {"wu4"}, // ㄊㄧˋ 376
  (const spell PROGMEM) {"wu,"}, // ㄊㄧㄝ 377
  (const spell PROGMEM) {"wu,6"}, // ㄊㄧㄝˊ 378
  (const spell PROGMEM) {"wu,3"}, // ㄊㄧㄝˇ 379
  (const spell PROGMEM) {"wul"}, // ㄊㄧㄠ 380
  (const spell PROGMEM) {"wul6"}, // ㄊㄧㄠˊ 381
  (const spell PROGMEM) {"wul3"}, // ㄊㄧㄠˇ 382
  (const spell PROGMEM) {"wul4"}, // ㄊㄧㄠˋ 383
  (const spell PROGMEM) {"wu0"}, // ㄊㄧㄢ 384
  (const spell PROGMEM) {"wu06"}, // ㄊㄧㄢˊ 385
  (const spell PROGMEM) {"wu03"}, // ㄊㄧㄢˇ 386
  (const spell PROGMEM) {"wu04"}, // ㄊㄧㄢˋ 387
  (const spell PROGMEM) {"wu/"}, // ㄊㄧㄥ 388
  (const spell PROGMEM) {"wu/6"}, // ㄊㄧㄥˊ 389
  (const spell PROGMEM) {"wu/3"}, // ㄊㄧㄥˇ 390
  (const spell PROGMEM) {"wu/4"}, // ㄊㄧㄥˋ 391
  (const spell PROGMEM) {"wj"}, // ㄊㄨ 392
  (const spell PROGMEM) {"wj6"}, // ㄊㄨˊ 393
  (const spell PROGMEM) {"wj3"}, // ㄊㄨˇ 394
  (const spell PROGMEM) {"wj4"}, // ㄊㄨˋ 395
  (const spell PROGMEM) {"wji"}, // ㄊㄨㄛ 396
  (const spell PROGMEM) {"wji6"}, // ㄊㄨㄛˊ 397
  (const spell PROGMEM) {"wji3"}, // ㄊㄨㄛˇ 398
  (const spell PROGMEM) {"wji4"}, // ㄊㄨㄛˋ 399
  (const spell PROGMEM) {"wjo"}, // ㄊㄨㄟ 400
  (const spell PROGMEM) {"wjo6"}, // ㄊㄨㄟˊ 401
  (const spell PROGMEM) {"wjo3"}, // ㄊㄨㄟˇ 402
  (const spell PROGMEM) {"wjo4"}, // ㄊㄨㄟˋ 403
  (const spell PROGMEM) {"wj0"}, // ㄊㄨㄢ 404
  (const spell PROGMEM) {"wj06"}, // ㄊㄨㄢˊ 405
  (const spell PROGMEM) {"wj03"}, // ㄊㄨㄢˇ 406
  (const spell PROGMEM) {"wj04"}, // ㄊㄨㄢˋ 407
  (const spell PROGMEM) {"wjp"}, // ㄊㄨㄣ 408
  (const spell PROGMEM) {"wjp6"}, // ㄊㄨㄣˊ 409
  (const spell PROGMEM) {"wjp4"}, // ㄊㄨㄣˋ 410
  (const spell PROGMEM) {"wj/"}, // ㄊㄨㄥ 411
  (const spell PROGMEM) {"wj/6"}, // ㄊㄨㄥˊ 412
  (const spell PROGMEM) {"wj/3"}, // ㄊㄨㄥˇ 413
  (const spell PROGMEM) {"wj/4"}, // ㄊㄨㄥˋ 414
  (const spell PROGMEM) {"s8"}, // ㄋㄚ 415
  (const spell PROGMEM) {"s86"}, // ㄋㄚˊ 416
  (const spell PROGMEM) {"s83"}, // ㄋㄚˇ 417
  (const spell PROGMEM) {"s84"}, // ㄋㄚˋ 418
  (const spell PROGMEM) {"s87"}, // ㄋㄚ˙ 419
  (const spell PROGMEM) {"sk"}, // ㄋㄜ 420
  (const spell PROGMEM) {"sk7"}, // ㄋㄜ˙ 421
  (const spell PROGMEM) {"s93"}, // ㄋㄞˇ 422
  (const spell PROGMEM) {"s94"}, // ㄋㄞˋ 423
  (const spell PROGMEM) {"s97"}, // ㄋㄞ˙ 424
  (const spell PROGMEM) {"so3"}, // ㄋㄟˇ 425
  (const spell PROGMEM) {"so4"}, // ㄋㄟˋ 426
  (const spell PROGMEM) {"sl"}, // ㄋㄠ 427
  (const spell PROGMEM) {"sl6"}, // ㄋㄠˊ 428
  (const spell PROGMEM) {"sl3"}, // ㄋㄠˇ 429
  (const spell PROGMEM) {"sl4"}, // ㄋㄠˋ 430
  (const spell PROGMEM) {"s.4"}, // ㄋㄡˋ 431
  (const spell PROGMEM) {"s0"}, // ㄋㄢ 432
  (const spell PROGMEM) {"s06"}, // ㄋㄢˊ 433
  (const spell PROGMEM) {"s03"}, // ㄋㄢˇ 434
  (const spell PROGMEM) {"s04"}, // ㄋㄢˋ 435
  (const spell PROGMEM) {"sp4"}, // ㄋㄣˋ 436
  (const spell PROGMEM) {"s;6"}, // ㄋㄤˊ 437
  (const spell PROGMEM) {"s;3"}, // ㄋㄤˇ 438
  (const spell PROGMEM) {"s;4"}, // ㄋㄤˋ 439
  (const spell PROGMEM) {"s;7"}, // ㄋㄤ˙ 440
  (const spell PROGMEM) {"s/6"}, // ㄋㄥˊ 441
  (const spell PROGMEM) {"su6"}, // ㄋㄧˊ 442
  (const spell PROGMEM) {"su3"}, // ㄋㄧˇ 443
  (const spell PROGMEM) {"su4"}, // ㄋㄧˋ 444
  (const spell PROGMEM) {"su,"}, // ㄋㄧㄝ 445
  (const spell PROGMEM) {"su,6"}, // ㄋㄧㄝˊ 446
  (const spell PROGMEM) {"su,4"}, // ㄋㄧㄝˋ 447
  (const spell PROGMEM) {"sul3"}, // ㄋㄧㄠˇ 448
  (const spell PROGMEM) {"sul4"}, // ㄋㄧㄠˋ 449
  (const spell PROGMEM) {"su."}, // ㄋㄧㄡ 450
  (const spell PROGMEM) {"su.6"}, // ㄋㄧㄡˊ 451
  (const spell PROGMEM) {"su.3"}, // ㄋㄧㄡˇ 452
  (const spell PROGMEM) {"su.4"}, // ㄋㄧㄡˋ 453
  (const spell PROGMEM) {"su0"}, // ㄋㄧㄢ 454
  (const spell PROGMEM) {"su06"}, // ㄋㄧㄢˊ 455
  (const spell PROGMEM) {"su03"}, // ㄋㄧㄢˇ 456
  (const spell PROGMEM) {"su04"}, // ㄋㄧㄢˋ 457
  (const spell PROGMEM) {"sup6"}, // ㄋㄧㄣˊ 458
  (const spell PROGMEM) {"su;6"}, // ㄋㄧㄤˊ 459
  (const spell PROGMEM) {"su;4"}, // ㄋㄧㄤˋ 460
  (const spell PROGMEM) {"su;7"}, // ㄋㄧㄤ˙ 461
  (const spell PROGMEM) {"su/6"}, // ㄋㄧㄥˊ 462
  (const spell PROGMEM) {"su/3"}, // ㄋㄧㄥˇ 463
  (const spell PROGMEM) {"su/4"}, // ㄋㄧㄥˋ 464
  (const spell PROGMEM) {"sj6"}, // ㄋㄨˊ 465
  (const spell PROGMEM) {"sj3"}, // ㄋㄨˇ 466
  (const spell PROGMEM) {"sj4"}, // ㄋㄨˋ 467
  (const spell PROGMEM) {"sji6"}, // ㄋㄨㄛˊ 468
  (const spell PROGMEM) {"sji3"}, // ㄋㄨㄛˇ 469
  (const spell PROGMEM) {"sji4"}, // ㄋㄨㄛˋ 470
  (const spell PROGMEM) {"sj03"}, // ㄋㄨㄢˇ 471
  (const spell PROGMEM) {"sj/6"}, // ㄋㄨㄥˊ 472
  (const spell PROGMEM) {"sj/4"}, // ㄋㄨㄥˋ 473
  (const spell PROGMEM) {"sj/7"}, // ㄋㄨㄥ˙ 474
  (const spell PROGMEM) {"sm3"}, // ㄋㄩˇ 475
  (const spell PROGMEM) {"sm4"}, // ㄋㄩˋ 476
  (const spell PROGMEM) {"sm,4"}, // ㄋㄩㄝˋ 477
  (const spell PROGMEM) {"x8"}, // ㄌㄚ 478
  (const spell PROGMEM) {"x86"}, // ㄌㄚˊ 479
  (const spell PROGMEM) {"x83"}, // ㄌㄚˇ 480
  (const spell PROGMEM) {"x84"}, // ㄌㄚˋ 481
  (const spell PROGMEM) {"x87"}, // ㄌㄚ˙ 482
  (const spell PROGMEM) {"xk"}, // ㄌㄜ 483
  (const spell PROGMEM) {"xk4"}, // ㄌㄜˋ 484
  (const spell PROGMEM) {"xk7"}, // ㄌㄜ˙ 485
  (const spell PROGMEM) {"x96"}, // ㄌㄞˊ 486
  (const spell PROGMEM) {"x94"}, // ㄌㄞˋ 487
  (const spell PROGMEM) {"xo"}, // ㄌㄟ 488
  (const spell PROGMEM) {"xo6"}, // ㄌㄟˊ 489
  (const spell PROGMEM) {"xo3"}, // ㄌㄟˇ 490
  (const spell PROGMEM) {"xo4"}, // ㄌㄟˋ 491
  (const spell PROGMEM) {"xl"}, // ㄌㄠ 492
  (const spell PROGMEM) {"xl6"}, // ㄌㄠˊ 493
  (const spell PROGMEM) {"xl3"}, // ㄌㄠˇ 494
  (const spell PROGMEM) {"xl4"}, // ㄌㄠˋ 495
  (const spell PROGMEM) {"xl7"}, // ㄌㄠ˙ 496
  (const spell PROGMEM) {"x."}, // ㄌㄡ 497
  (const spell PROGMEM) {"x.6"}, // ㄌㄡˊ 498
  (const spell PROGMEM) {"x.3"}, // ㄌㄡˇ 499
  (const spell PROGMEM) {"x.4"}, // ㄌㄡˋ 500
  (const spell PROGMEM) {"x.7"}, // ㄌㄡ˙ 501
  (const spell PROGMEM) {"x06"}, // ㄌㄢˊ 502
  (const spell PROGMEM) {"x03"}, // ㄌㄢˇ 503
  (const spell PROGMEM) {"x04"}, // ㄌㄢˋ 504
  (const spell PROGMEM) {"x;"}, // ㄌㄤ 505
  (const spell PROGMEM) {"x;6"}, // ㄌㄤˊ 506
  (const spell PROGMEM) {"x;3"}, // ㄌㄤˇ 507
  (const spell PROGMEM) {"x;4"}, // ㄌㄤˋ 508
  (const spell PROGMEM) {"x/"}, // ㄌㄥ 509
  (const spell PROGMEM) {"x/6"}, // ㄌㄥˊ 510
  (const spell PROGMEM) {"x/3"}, // ㄌㄥˇ 511
  (const spell PROGMEM) {"x/4"}, // ㄌㄥˋ 512
  (const spell PROGMEM) {"xu"}, // ㄌㄧ 513
  (const spell PROGMEM) {"xu6"}, // ㄌㄧˊ 514
  (const spell PROGMEM) {"xu3"}, // ㄌㄧˇ 515
  (const spell PROGMEM) {"xu4"}, // ㄌㄧˋ 516
  (const spell PROGMEM) {"xu7"}, // ㄌㄧ˙ 517
  (const spell PROGMEM) {"xu83"}, // ㄌㄧㄚˇ 518
  (const spell PROGMEM) {"xu,"}, // ㄌㄧㄝ 519
  (const spell PROGMEM) {"xu,6"}, // ㄌㄧㄝˊ 520
  (const spell PROGMEM) {"xu,3"}, // ㄌㄧㄝˇ 521
  (const spell PROGMEM) {"xu,4"}, // ㄌㄧㄝˋ 522
  (const spell PROGMEM) {"xul"}, // ㄌㄧㄠ 523
  (const spell PROGMEM) {"xul6"}, // ㄌㄧㄠˊ 524
  (const spell PROGMEM) {"xul3"}, // ㄌㄧㄠˇ 525
  (const spell PROGMEM) {"xul4"}, // ㄌㄧㄠˋ 526
  (const spell PROGMEM) {"xu."}, // ㄌㄧㄡ 527
  (const spell PROGMEM) {"xu.6"}, // ㄌㄧㄡˊ 528
  (const spell PROGMEM) {"xu.3"}, // ㄌㄧㄡˇ 529
  (const spell PROGMEM) {"xu.4"}, // ㄌㄧㄡˋ 530
  (const spell PROGMEM) {"xu0"}, // ㄌㄧㄢ 531
  (const spell PROGMEM) {"xu06"}, // ㄌㄧㄢˊ 532
  (const spell PROGMEM) {"xu03"}, // ㄌㄧㄢˇ 533
  (const spell PROGMEM) {"xu04"}, // ㄌㄧㄢˋ 534
  (const spell PROGMEM) {"xup6"}, // ㄌㄧㄣˊ 535
  (const spell PROGMEM) {"xup3"}, // ㄌㄧㄣˇ 536
  (const spell PROGMEM) {"xup4"}, // ㄌㄧㄣˋ 537
  (const spell PROGMEM) {"xu;6"}, // ㄌㄧㄤˊ 538
  (const spell PROGMEM) {"xu;3"}, // ㄌㄧㄤˇ 539
  (const spell PROGMEM) {"xu;4"}, // ㄌㄧㄤˋ 540
  (const spell PROGMEM) {"xu/"}, // ㄌㄧㄥ 541
  (const spell PROGMEM) {"xu/6"}, // ㄌㄧㄥˊ 542
  (const spell PROGMEM) {"xu/3"}, // ㄌㄧㄥˇ 543
  (const spell PROGMEM) {"xu/4"}, // ㄌㄧㄥˋ 544
  (const spell PROGMEM) {"xj"}, // ㄌㄨ 545
  (const spell PROGMEM) {"xj6"}, // ㄌㄨˊ 546
  (const spell PROGMEM) {"xj3"}, // ㄌㄨˇ 547
  (const spell PROGMEM) {"xj4"}, // ㄌㄨˋ 548
  (const spell PROGMEM) {"xj7"}, // ㄌㄨ˙ 549
  (const spell PROGMEM) {"xji"}, // ㄌㄨㄛ 550
  (const spell PROGMEM) {"xji6"}, // ㄌㄨㄛˊ 551
  (const spell PROGMEM) {"xji3"}, // ㄌㄨㄛˇ 552
  (const spell PROGMEM) {"xji4"}, // ㄌㄨㄛˋ 553
  (const spell PROGMEM) {"xj06"}, // ㄌㄨㄢˊ 554
  (const spell PROGMEM) {"xj03"}, // ㄌㄨㄢˇ 555
  (const spell PROGMEM) {"xj04"}, // ㄌㄨㄢˋ 556
  (const spell PROGMEM) {"xjp"}, // ㄌㄨㄣ 557
  (const spell PROGMEM) {"xjp6"}, // ㄌㄨㄣˊ 558
  (const spell PROGMEM) {"xjp4"}, // ㄌㄨㄣˋ 559
  (const spell PROGMEM) {"xj/6"}, // ㄌㄨㄥˊ 560
  (const spell PROGMEM) {"xj/3"}, // ㄌㄨㄥˇ 561
  (const spell PROGMEM) {"xj/4"}, // ㄌㄨㄥˋ 562
  (const spell PROGMEM) {"xm6"}, // ㄌㄩˊ 563
  (const spell PROGMEM) {"xm3"}, // ㄌㄩˇ 564
  (const spell PROGMEM) {"xm4"}, // ㄌㄩˋ 565
  (const spell PROGMEM) {"xm,4"}, // ㄌㄩㄝˋ 566
  (const spell PROGMEM) {"xm06"}, // ㄌㄩㄢˊ 567
  (const spell PROGMEM) {"xm03"}, // ㄌㄩㄢˇ 568
  (const spell PROGMEM) {"e8"}, // ㄍㄚ 569
  (const spell PROGMEM) {"e86"}, // ㄍㄚˊ 570
  (const spell PROGMEM) {"e83"}, // ㄍㄚˇ 571
  (const spell PROGMEM) {"e84"}, // ㄍㄚˋ 572
  (const spell PROGMEM) {"e87"}, // ㄍㄚ˙ 573
  (const spell PROGMEM) {"ek"}, // ㄍㄜ 574
  (const spell PROGMEM) {"ek6"}, // ㄍㄜˊ 575
  (const spell PROGMEM) {"ek3"}, // ㄍㄜˇ 576
  (const spell PROGMEM) {"ek4"}, // ㄍㄜˋ 577
  (const spell PROGMEM) {"ek7"}, // ㄍㄜ˙ 578
  (const spell PROGMEM) {"e9"}, // ㄍㄞ 579
  (const spell PROGMEM) {"e96"}, // ㄍㄞˊ 580
  (const spell PROGMEM) {"e93"}, // ㄍㄞˇ 581
  (const spell PROGMEM) {"e94"}, // ㄍㄞˋ 582
  (const spell PROGMEM) {"eo6"}, // ㄍㄟˊ 583
  (const spell PROGMEM) {"eo3"}, // ㄍㄟˇ 584
  (const spell PROGMEM) {"el"}, // ㄍㄠ 585
  (const spell PROGMEM) {"el6"}, // ㄍㄠˊ 586
  (const spell PROGMEM) {"el3"}, // ㄍㄠˇ 587
  (const spell PROGMEM) {"el4"}, // ㄍㄠˋ 588
  (const spell PROGMEM) {"e."}, // ㄍㄡ 589
  (const spell PROGMEM) {"e.6"}, // ㄍㄡˊ 590
  (const spell PROGMEM) {"e.3"}, // ㄍㄡˇ 591
  (const spell PROGMEM) {"e.4"}, // ㄍㄡˋ 592
  (const spell PROGMEM) {"e.7"}, // ㄍㄡ˙ 593
  (const spell PROGMEM) {"e0"}, // ㄍㄢ 594
  (const spell PROGMEM) {"e06"}, // ㄍㄢˊ 595
  (const spell PROGMEM) {"e03"}, // ㄍㄢˇ 596
  (const spell PROGMEM) {"e04"}, // ㄍㄢˋ 597
  (const spell PROGMEM) {"ep"}, // ㄍㄣ 598
  (const spell PROGMEM) {"ep6"}, // ㄍㄣˊ 599
  (const spell PROGMEM) {"ep3"}, // ㄍㄣˇ 600
  (const spell PROGMEM) {"ep4"}, // ㄍㄣˋ 601
  (const spell PROGMEM) {"e;"}, // ㄍㄤ 602
  (const spell PROGMEM) {"e;6"}, // ㄍㄤˊ 603
  (const spell PROGMEM) {"e;3"}, // ㄍㄤˇ 604
  (const spell PROGMEM) {"e;4"}, // ㄍㄤˋ 605
  (const spell PROGMEM) {"e/"}, // ㄍㄥ 606
  (const spell PROGMEM) {"e/6"}, // ㄍㄥˊ 607
  (const spell PROGMEM) {"e/3"}, // ㄍㄥˇ 608
  (const spell PROGMEM) {"e/4"}, // ㄍㄥˋ 609
  (const spell PROGMEM) {"euj4"}, // ㄍㄧㄨˋ 610
  (const spell PROGMEM) {"eup"}, // ㄍㄧㄣ 611
  (const spell PROGMEM) {"ej"}, // ㄍㄨ 612
  (const spell PROGMEM) {"ej6"}, // ㄍㄨˊ 613
  (const spell PROGMEM) {"ej3"}, // ㄍㄨˇ 614
  (const spell PROGMEM) {"ej4"}, // ㄍㄨˋ 615
  (const spell PROGMEM) {"ej8"}, // ㄍㄨㄚ 616
  (const spell PROGMEM) {"ej86"}, // ㄍㄨㄚˊ 617
  (const spell PROGMEM) {"ej83"}, // ㄍㄨㄚˇ 618
  (const spell PROGMEM) {"ej84"}, // ㄍㄨㄚˋ 619
  (const spell PROGMEM) {"eji"}, // ㄍㄨㄛ 620
  (const spell PROGMEM) {"eji6"}, // ㄍㄨㄛˊ 621
  (const spell PROGMEM) {"eji3"}, // ㄍㄨㄛˇ 622
  (const spell PROGMEM) {"eji4"}, // ㄍㄨㄛˋ 623
  (const spell PROGMEM) {"eji7"}, // ㄍㄨㄛ˙ 624
  (const spell PROGMEM) {"ej9"}, // ㄍㄨㄞ 625
  (const spell PROGMEM) {"ej96"}, // ㄍㄨㄞˊ 626
  (const spell PROGMEM) {"ej93"}, // ㄍㄨㄞˇ 627
  (const spell PROGMEM) {"ej94"}, // ㄍㄨㄞˋ 628
  (const spell PROGMEM) {"ejo"}, // ㄍㄨㄟ 629
  (const spell PROGMEM) {"ejo6"}, // ㄍㄨㄟˊ 630
  (const spell PROGMEM) {"ejo3"}, // ㄍㄨㄟˇ 631
  (const spell PROGMEM) {"ejo4"}, // ㄍㄨㄟˋ 632
  (const spell PROGMEM) {"ej0"}, // ㄍㄨㄢ 633
  (const spell PROGMEM) {"ej06"}, // ㄍㄨㄢˊ 634
  (const spell PROGMEM) {"ej03"}, // ㄍㄨㄢˇ 635
  (const spell PROGMEM) {"ej04"}, // ㄍㄨㄢˋ 636
  (const spell PROGMEM) {"ejp6"}, // ㄍㄨㄣˊ 637
  (const spell PROGMEM) {"ejp3"}, // ㄍㄨㄣˇ 638
  (const spell PROGMEM) {"ejp4"}, // ㄍㄨㄣˋ 639
  (const spell PROGMEM) {"ej;"}, // ㄍㄨㄤ 640
  (const spell PROGMEM) {"ej;6"}, // ㄍㄨㄤˊ 641
  (const spell PROGMEM) {"ej;3"}, // ㄍㄨㄤˇ 642
  (const spell PROGMEM) {"ej;4"}, // ㄍㄨㄤˋ 643
  (const spell PROGMEM) {"ej/"}, // ㄍㄨㄥ 644
  (const spell PROGMEM) {"ej/6"}, // ㄍㄨㄥˊ 645
  (const spell PROGMEM) {"ej/3"}, // ㄍㄨㄥˇ 646
  (const spell PROGMEM) {"ej/4"}, // ㄍㄨㄥˋ 647
  (const spell PROGMEM) {"d8"}, // ㄎㄚ 648
  (const spell PROGMEM) {"d86"}, // ㄎㄚˊ 649
  (const spell PROGMEM) {"d83"}, // ㄎㄚˇ 650
  (const spell PROGMEM) {"d84"}, // ㄎㄚˋ 651
  (const spell PROGMEM) {"dk"}, // ㄎㄜ 652
  (const spell PROGMEM) {"dk6"}, // ㄎㄜˊ 653
  (const spell PROGMEM) {"dk3"}, // ㄎㄜˇ 654
  (const spell PROGMEM) {"dk4"}, // ㄎㄜˋ 655
  (const spell PROGMEM) {"d9"}, // ㄎㄞ 656
  (const spell PROGMEM) {"d96"}, // ㄎㄞˊ 657
  (const spell PROGMEM) {"d93"}, // ㄎㄞˇ 658
  (const spell PROGMEM) {"d94"}, // ㄎㄞˋ 659
  (const spell PROGMEM) {"do"}, // ㄎㄟ 660
  (const spell PROGMEM) {"dl"}, // ㄎㄠ 661
  (const spell PROGMEM) {"dl6"}, // ㄎㄠˊ 662
  (const spell PROGMEM) {"dl3"}, // ㄎㄠˇ 663
  (const spell PROGMEM) {"dl4"}, // ㄎㄠˋ 664
  (const spell PROGMEM) {"dl7"}, // ㄎㄠ˙ 665
  (const spell PROGMEM) {"d."}, // ㄎㄡ 666
  (const spell PROGMEM) {"d.6"}, // ㄎㄡˊ 667
  (const spell PROGMEM) {"d.3"}, // ㄎㄡˇ 668
  (const spell PROGMEM) {"d.4"}, // ㄎㄡˋ 669
  (const spell PROGMEM) {"d0"}, // ㄎㄢ 670
  (const spell PROGMEM) {"d06"}, // ㄎㄢˊ 671
  (const spell PROGMEM) {"d03"}, // ㄎㄢˇ 672
  (const spell PROGMEM) {"d04"}, // ㄎㄢˋ 673
  (const spell PROGMEM) {"dp6"}, // ㄎㄣˊ 674
  (const spell PROGMEM) {"dp3"}, // ㄎㄣˇ 675
  (const spell PROGMEM) {"dp4"}, // ㄎㄣˋ 676
  (const spell PROGMEM) {"d;"}, // ㄎㄤ 677
  (const spell PROGMEM) {"d;6"}, // ㄎㄤˊ 678
  (const spell PROGMEM) {"d;3"}, // ㄎㄤˇ 679
  (const spell PROGMEM) {"d;4"}, // ㄎㄤˋ 680
  (const spell PROGMEM) {"d/"}, // ㄎㄥ 681
  (const spell PROGMEM) {"d/6"}, // ㄎㄥˊ 682
  (const spell PROGMEM) {"d/3"}, // ㄎㄥˇ 683
  (const spell PROGMEM) {"dj"}, // ㄎㄨ 684
  (const spell PROGMEM) {"dj6"}, // ㄎㄨˊ 685
  (const spell PROGMEM) {"dj3"}, // ㄎㄨˇ 686
  (const spell PROGMEM) {"dj4"}, // ㄎㄨˋ 687
  (const spell PROGMEM) {"dj8"}, // ㄎㄨㄚ 688
  (const spell PROGMEM) {"dj86"}, // ㄎㄨㄚˊ 689
  (const spell PROGMEM) {"dj83"}, // ㄎㄨㄚˇ 690
  (const spell PROGMEM) {"dj84"}, // ㄎㄨㄚˋ 691
  (const spell PROGMEM) {"dj9"}, // ㄎㄨㄞ 692
  (const spell PROGMEM) {"dj96"}, // ㄎㄨㄞˊ 693
  (const spell PROGMEM) {"dj93"}, // ㄎㄨㄞˇ 694
  (const spell PROGMEM) {"dj94"}, // ㄎㄨㄞˋ 695
  (const spell PROGMEM) {"djo"}, // ㄎㄨㄟ 696
  (const spell PROGMEM) {"djo6"}, // ㄎㄨㄟˊ 697
  (const spell PROGMEM) {"djo3"}, // ㄎㄨㄟˇ 698
  (const spell PROGMEM) {"djo4"}, // ㄎㄨㄟˋ 699
  (const spell PROGMEM) {"dj0"}, // ㄎㄨㄢ 700
  (const spell PROGMEM) {"dj06"}, // ㄎㄨㄢˊ 701
  (const spell PROGMEM) {"dj03"}, // ㄎㄨㄢˇ 702
  (const spell PROGMEM) {"djp"}, // ㄎㄨㄣ 703
  (const spell PROGMEM) {"djp6"}, // ㄎㄨㄣˊ 704
  (const spell PROGMEM) {"djp3"}, // ㄎㄨㄣˇ 705
  (const spell PROGMEM) {"djp4"}, // ㄎㄨㄣˋ 706
  (const spell PROGMEM) {"dj;"}, // ㄎㄨㄤ 707
  (const spell PROGMEM) {"dj;6"}, // ㄎㄨㄤˊ 708
  (const spell PROGMEM) {"dj;4"}, // ㄎㄨㄤˋ 709
  (const spell PROGMEM) {"dj/"}, // ㄎㄨㄥ 710
  (const spell PROGMEM) {"dj/6"}, // ㄎㄨㄥˊ 711
  (const spell PROGMEM) {"dj/3"}, // ㄎㄨㄥˇ 712
  (const spell PROGMEM) {"dj/4"}, // ㄎㄨㄥˋ 713
  (const spell PROGMEM) {"c8"}, // ㄏㄚ 714
  (const spell PROGMEM) {"c86"}, // ㄏㄚˊ 715
  (const spell PROGMEM) {"c83"}, // ㄏㄚˇ 716
  (const spell PROGMEM) {"c84"}, // ㄏㄚˋ 717
  (const spell PROGMEM) {"ck"}, // ㄏㄜ 718
  (const spell PROGMEM) {"ck6"}, // ㄏㄜˊ 719
  (const spell PROGMEM) {"ck4"}, // ㄏㄜˋ 720
  (const spell PROGMEM) {"c9"}, // ㄏㄞ 721
  (const spell PROGMEM) {"c96"}, // ㄏㄞˊ 722
  (const spell PROGMEM) {"c93"}, // ㄏㄞˇ 723
  (const spell PROGMEM) {"c94"}, // ㄏㄞˋ 724
  (const spell PROGMEM) {"co"}, // ㄏㄟ 725
  (const spell PROGMEM) {"co3"}, // ㄏㄟˇ 726
  (const spell PROGMEM) {"cl"}, // ㄏㄠ 727
  (const spell PROGMEM) {"cl6"}, // ㄏㄠˊ 728
  (const spell PROGMEM) {"cl3"}, // ㄏㄠˇ 729
  (const spell PROGMEM) {"cl4"}, // ㄏㄠˋ 730
  (const spell PROGMEM) {"c."}, // ㄏㄡ 731
  (const spell PROGMEM) {"c.6"}, // ㄏㄡˊ 732
  (const spell PROGMEM) {"c.3"}, // ㄏㄡˇ 733
  (const spell PROGMEM) {"c.4"}, // ㄏㄡˋ 734
  (const spell PROGMEM) {"c0"}, // ㄏㄢ 735
  (const spell PROGMEM) {"c06"}, // ㄏㄢˊ 736
  (const spell PROGMEM) {"c03"}, // ㄏㄢˇ 737
  (const spell PROGMEM) {"c04"}, // ㄏㄢˋ 738
  (const spell PROGMEM) {"cp"}, // ㄏㄣ 739
  (const spell PROGMEM) {"cp6"}, // ㄏㄣˊ 740
  (const spell PROGMEM) {"cp3"}, // ㄏㄣˇ 741
  (const spell PROGMEM) {"cp4"}, // ㄏㄣˋ 742
  (const spell PROGMEM) {"c;"}, // ㄏㄤ 743
  (const spell PROGMEM) {"c;6"}, // ㄏㄤˊ 744
  (const spell PROGMEM) {"c;4"}, // ㄏㄤˋ 745
  (const spell PROGMEM) {"c/"}, // ㄏㄥ 746
  (const spell PROGMEM) {"c/6"}, // ㄏㄥˊ 747
  (const spell PROGMEM) {"c/4"}, // ㄏㄥˋ 748
  (const spell PROGMEM) {"cj"}, // ㄏㄨ 749
  (const spell PROGMEM) {"cj6"}, // ㄏㄨˊ 750
  (const spell PROGMEM) {"cj3"}, // ㄏㄨˇ 751
  (const spell PROGMEM) {"cj4"}, // ㄏㄨˋ 752
  (const spell PROGMEM) {"cj8"}, // ㄏㄨㄚ 753
  (const spell PROGMEM) {"cj86"}, // ㄏㄨㄚˊ 754
  (const spell PROGMEM) {"cj84"}, // ㄏㄨㄚˋ 755
  (const spell PROGMEM) {"cji"}, // ㄏㄨㄛ 756
  (const spell PROGMEM) {"cji6"}, // ㄏㄨㄛˊ 757
  (const spell PROGMEM) {"cji3"}, // ㄏㄨㄛˇ 758
  (const spell PROGMEM) {"cji4"}, // ㄏㄨㄛˋ 759
  (const spell PROGMEM) {"cji7"}, // ㄏㄨㄛ˙ 760
  (const spell PROGMEM) {"cj96"}, // ㄏㄨㄞˊ 761
  (const spell PROGMEM) {"cj94"}, // ㄏㄨㄞˋ 762
  (const spell PROGMEM) {"cjo"}, // ㄏㄨㄟ 763
  (const spell PROGMEM) {"cjo6"}, // ㄏㄨㄟˊ 764
  (const spell PROGMEM) {"cjo3"}, // ㄏㄨㄟˇ 765
  (const spell PROGMEM) {"cjo4"}, // ㄏㄨㄟˋ 766
  (const spell PROGMEM) {"cj0"}, // ㄏㄨㄢ 767
  (const spell PROGMEM) {"cj06"}, // ㄏㄨㄢˊ 768
  (const spell PROGMEM) {"cj03"}, // ㄏㄨㄢˇ 769
  (const spell PROGMEM) {"cj04"}, // ㄏㄨㄢˋ 770
  (const spell PROGMEM) {"cjp"}, // ㄏㄨㄣ 771
  (const spell PROGMEM) {"cjp6"}, // ㄏㄨㄣˊ 772
  (const spell PROGMEM) {"cjp3"}, // ㄏㄨㄣˇ 773
  (const spell PROGMEM) {"cjp4"}, // ㄏㄨㄣˋ 774
  (const spell PROGMEM) {"cj;"}, // ㄏㄨㄤ 775
  (const spell PROGMEM) {"cj;6"}, // ㄏㄨㄤˊ 776
  (const spell PROGMEM) {"cj;3"}, // ㄏㄨㄤˇ 777
  (const spell PROGMEM) {"cj;4"}, // ㄏㄨㄤˋ 778
  (const spell PROGMEM) {"cj;7"}, // ㄏㄨㄤ˙ 779
  (const spell PROGMEM) {"cj/"}, // ㄏㄨㄥ 780
  (const spell PROGMEM) {"cj/6"}, // ㄏㄨㄥˊ 781
  (const spell PROGMEM) {"cj/3"}, // ㄏㄨㄥˇ 782
  (const spell PROGMEM) {"cj/4"}, // ㄏㄨㄥˋ 783
  (const spell PROGMEM) {"ru"}, // ㄐㄧ 784
  (const spell PROGMEM) {"ru6"}, // ㄐㄧˊ 785
  (const spell PROGMEM) {"ru3"}, // ㄐㄧˇ 786
  (const spell PROGMEM) {"ru4"}, // ㄐㄧˋ 787
  (const spell PROGMEM) {"ru7"}, // ㄐㄧ˙ 788
  (const spell PROGMEM) {"ru8"}, // ㄐㄧㄚ 789
  (const spell PROGMEM) {"ru86"}, // ㄐㄧㄚˊ 790
  (const spell PROGMEM) {"ru83"}, // ㄐㄧㄚˇ 791
  (const spell PROGMEM) {"ru84"}, // ㄐㄧㄚˋ 792
  (const spell PROGMEM) {"ru,"}, // ㄐㄧㄝ 793
  (const spell PROGMEM) {"ru,6"}, // ㄐㄧㄝˊ 794
  (const spell PROGMEM) {"ru,3"}, // ㄐㄧㄝˇ 795
  (const spell PROGMEM) {"ru,4"}, // ㄐㄧㄝˋ 796
  (const spell PROGMEM) {"ru,7"}, // ㄐㄧㄝ˙ 797
  (const spell PROGMEM) {"rul"}, // ㄐㄧㄠ 798
  (const spell PROGMEM) {"rul6"}, // ㄐㄧㄠˊ 799
  (const spell PROGMEM) {"rul3"}, // ㄐㄧㄠˇ 800
  (const spell PROGMEM) {"rul4"}, // ㄐㄧㄠˋ 801
  (const spell PROGMEM) {"ru."}, // ㄐㄧㄡ 802
  (const spell PROGMEM) {"ru.6"}, // ㄐㄧㄡˊ 803
  (const spell PROGMEM) {"ru.3"}, // ㄐㄧㄡˇ 804
  (const spell PROGMEM) {"ru.4"}, // ㄐㄧㄡˋ 805
  (const spell PROGMEM) {"ru0"}, // ㄐㄧㄢ 806
  (const spell PROGMEM) {"ru06"}, // ㄐㄧㄢˊ 807
  (const spell PROGMEM) {"ru03"}, // ㄐㄧㄢˇ 808
  (const spell PROGMEM) {"ru04"}, // ㄐㄧㄢˋ 809
  (const spell PROGMEM) {"rup"}, // ㄐㄧㄣ 810
  (const spell PROGMEM) {"rup6"}, // ㄐㄧㄣˊ 811
  (const spell PROGMEM) {"rup3"}, // ㄐㄧㄣˇ 812
  (const spell PROGMEM) {"rup4"}, // ㄐㄧㄣˋ 813
  (const spell PROGMEM) {"rup7"}, // ㄐㄧㄣ˙ 814
  (const spell PROGMEM) {"ru;"}, // ㄐㄧㄤ 815
  (const spell PROGMEM) {"ru;6"}, // ㄐㄧㄤˊ 816
  (const spell PROGMEM) {"ru;3"}, // ㄐㄧㄤˇ 817
  (const spell PROGMEM) {"ru;4"}, // ㄐㄧㄤˋ 818
  (const spell PROGMEM) {"ru/"}, // ㄐㄧㄥ 819
  (const spell PROGMEM) {"ru/6"}, // ㄐㄧㄥˊ 820
  (const spell PROGMEM) {"ru/3"}, // ㄐㄧㄥˇ 821
  (const spell PROGMEM) {"ru/4"}, // ㄐㄧㄥˋ 822
  (const spell PROGMEM) {"rm"}, // ㄐㄩ 823
  (const spell PROGMEM) {"rm6"}, // ㄐㄩˊ 824
  (const spell PROGMEM) {"rm3"}, // ㄐㄩˇ 825
  (const spell PROGMEM) {"rm4"}, // ㄐㄩˋ 826
  (const spell PROGMEM) {"rm,"}, // ㄐㄩㄝ 827
  (const spell PROGMEM) {"rm,6"}, // ㄐㄩㄝˊ 828
  (const spell PROGMEM) {"rm,3"}, // ㄐㄩㄝˇ 829
  (const spell PROGMEM) {"rm,4"}, // ㄐㄩㄝˋ 830
  (const spell PROGMEM) {"rm0"}, // ㄐㄩㄢ 831
  (const spell PROGMEM) {"rm06"}, // ㄐㄩㄢˊ 832
  (const spell PROGMEM) {"rm03"}, // ㄐㄩㄢˇ 833
  (const spell PROGMEM) {"rm04"}, // ㄐㄩㄢˋ 834
  (const spell PROGMEM) {"rmp"}, // ㄐㄩㄣ 835
  (const spell PROGMEM) {"rmp4"}, // ㄐㄩㄣˋ 836
  (const spell PROGMEM) {"rm/"}, // ㄐㄩㄥ 837
  (const spell PROGMEM) {"rm/6"}, // ㄐㄩㄥˊ 838
  (const spell PROGMEM) {"rm/3"}, // ㄐㄩㄥˇ 839
  (const spell PROGMEM) {"fu"}, // ㄑㄧ 840
  (const spell PROGMEM) {"fu6"}, // ㄑㄧˊ 841
  (const spell PROGMEM) {"fu3"}, // ㄑㄧˇ 842
  (const spell PROGMEM) {"fu4"}, // ㄑㄧˋ 843
  (const spell PROGMEM) {"fu8"}, // ㄑㄧㄚ 844
  (const spell PROGMEM) {"fu86"}, // ㄑㄧㄚˊ 845
  (const spell PROGMEM) {"fu83"}, // ㄑㄧㄚˇ 846
  (const spell PROGMEM) {"fu84"}, // ㄑㄧㄚˋ 847
  (const spell PROGMEM) {"fu,"}, // ㄑㄧㄝ 848
  (const spell PROGMEM) {"fu,6"}, // ㄑㄧㄝˊ 849
  (const spell PROGMEM) {"fu,3"}, // ㄑㄧㄝˇ 850
  (const spell PROGMEM) {"fu,4"}, // ㄑㄧㄝˋ 851
  (const spell PROGMEM) {"ful"}, // ㄑㄧㄠ 852
  (const spell PROGMEM) {"ful6"}, // ㄑㄧㄠˊ 853
  (const spell PROGMEM) {"ful3"}, // ㄑㄧㄠˇ 854
  (const spell PROGMEM) {"ful4"}, // ㄑㄧㄠˋ 855
  (const spell PROGMEM) {"fu."}, // ㄑㄧㄡ 856
  (const spell PROGMEM) {"fu.6"}, // ㄑㄧㄡˊ 857
  (const spell PROGMEM) {"fu.3"}, // ㄑㄧㄡˇ 858
  (const spell PROGMEM) {"fu.7"}, // ㄑㄧㄡ˙ 859
  (const spell PROGMEM) {"fu0"}, // ㄑㄧㄢ 860
  (const spell PROGMEM) {"fu06"}, // ㄑㄧㄢˊ 861
  (const spell PROGMEM) {"fu03"}, // ㄑㄧㄢˇ 862
  (const spell PROGMEM) {"fu04"}, // ㄑㄧㄢˋ 863
  (const spell PROGMEM) {"fup"}, // ㄑㄧㄣ 864
  (const spell PROGMEM) {"fup6"}, // ㄑㄧㄣˊ 865
  (const spell PROGMEM) {"fup3"}, // ㄑㄧㄣˇ 866
  (const spell PROGMEM) {"fup4"}, // ㄑㄧㄣˋ 867
  (const spell PROGMEM) {"fu;"}, // ㄑㄧㄤ 868
  (const spell PROGMEM) {"fu;6"}, // ㄑㄧㄤˊ 869
  (const spell PROGMEM) {"fu;3"}, // ㄑㄧㄤˇ 870
  (const spell PROGMEM) {"fu;4"}, // ㄑㄧㄤˋ 871
  (const spell PROGMEM) {"fu/"}, // ㄑㄧㄥ 872
  (const spell PROGMEM) {"fu/6"}, // ㄑㄧㄥˊ 873
  (const spell PROGMEM) {"fu/3"}, // ㄑㄧㄥˇ 874
  (const spell PROGMEM) {"fu/4"}, // ㄑㄧㄥˋ 875
  (const spell PROGMEM) {"fm"}, // ㄑㄩ 876
  (const spell PROGMEM) {"fm6"}, // ㄑㄩˊ 877
  (const spell PROGMEM) {"fm3"}, // ㄑㄩˇ 878
  (const spell PROGMEM) {"fm4"}, // ㄑㄩˋ 879
  (const spell PROGMEM) {"fm,"}, // ㄑㄩㄝ 880
  (const spell PROGMEM) {"fm,6"}, // ㄑㄩㄝˊ 881
  (const spell PROGMEM) {"fm,4"}, // ㄑㄩㄝˋ 882
  (const spell PROGMEM) {"fm0"}, // ㄑㄩㄢ 883
  (const spell PROGMEM) {"fm06"}, // ㄑㄩㄢˊ 884
  (const spell PROGMEM) {"fm03"}, // ㄑㄩㄢˇ 885
  (const spell PROGMEM) {"fm04"}, // ㄑㄩㄢˋ 886
  (const spell PROGMEM) {"fmp"}, // ㄑㄩㄣ 887
  (const spell PROGMEM) {"fmp6"}, // ㄑㄩㄣˊ 888
  (const spell PROGMEM) {"fm/"}, // ㄑㄩㄥ 889
  (const spell PROGMEM) {"fm/6"}, // ㄑㄩㄥˊ 890
  (const spell PROGMEM) {"fm/3"}, // ㄑㄩㄥˇ 891
  (const spell PROGMEM) {"vu"}, // ㄒㄧ 892
  (const spell PROGMEM) {"vu6"}, // ㄒㄧˊ 893
  (const spell PROGMEM) {"vu3"}, // ㄒㄧˇ 894
  (const spell PROGMEM) {"vu4"}, // ㄒㄧˋ 895
  (const spell PROGMEM) {"vu7"}, // ㄒㄧ˙ 896
  (const spell PROGMEM) {"vu8"}, // ㄒㄧㄚ 897
  (const spell PROGMEM) {"vu86"}, // ㄒㄧㄚˊ 898
  (const spell PROGMEM) {"vu84"}, // ㄒㄧㄚˋ 899
  (const spell PROGMEM) {"vu,"}, // ㄒㄧㄝ 900
  (const spell PROGMEM) {"vu,6"}, // ㄒㄧㄝˊ 901
  (const spell PROGMEM) {"vu,3"}, // ㄒㄧㄝˇ 902
  (const spell PROGMEM) {"vu,4"}, // ㄒㄧㄝˋ 903
  (const spell PROGMEM) {"vu,7"}, // ㄒㄧㄝ˙ 904
  (const spell PROGMEM) {"vul"}, // ㄒㄧㄠ 905
  (const spell PROGMEM) {"vul6"}, // ㄒㄧㄠˊ 906
  (const spell PROGMEM) {"vul3"}, // ㄒㄧㄠˇ 907
  (const spell PROGMEM) {"vul4"}, // ㄒㄧㄠˋ 908
  (const spell PROGMEM) {"vu."}, // ㄒㄧㄡ 909
  (const spell PROGMEM) {"vu.6"}, // ㄒㄧㄡˊ 910
  (const spell PROGMEM) {"vu.3"}, // ㄒㄧㄡˇ 911
  (const spell PROGMEM) {"vu.4"}, // ㄒㄧㄡˋ 912
  (const spell PROGMEM) {"vu0"}, // ㄒㄧㄢ 913
  (const spell PROGMEM) {"vu06"}, // ㄒㄧㄢˊ 914
  (const spell PROGMEM) {"vu03"}, // ㄒㄧㄢˇ 915
  (const spell PROGMEM) {"vu04"}, // ㄒㄧㄢˋ 916
  (const spell PROGMEM) {"vup"}, // ㄒㄧㄣ 917
  (const spell PROGMEM) {"vup6"}, // ㄒㄧㄣˊ 918
  (const spell PROGMEM) {"vup4"}, // ㄒㄧㄣˋ 919
  (const spell PROGMEM) {"vu;"}, // ㄒㄧㄤ 920
  (const spell PROGMEM) {"vu;6"}, // ㄒㄧㄤˊ 921
  (const spell PROGMEM) {"vu;3"}, // ㄒㄧㄤˇ 922
  (const spell PROGMEM) {"vu;4"}, // ㄒㄧㄤˋ 923
  (const spell PROGMEM) {"vu/"}, // ㄒㄧㄥ 924
  (const spell PROGMEM) {"vu/6"}, // ㄒㄧㄥˊ 925
  (const spell PROGMEM) {"vu/3"}, // ㄒㄧㄥˇ 926
  (const spell PROGMEM) {"vu/4"}, // ㄒㄧㄥˋ 927
  (const spell PROGMEM) {"vm"}, // ㄒㄩ 928
  (const spell PROGMEM) {"vm6"}, // ㄒㄩˊ 929
  (const spell PROGMEM) {"vm3"}, // ㄒㄩˇ 930
  (const spell PROGMEM) {"vm4"}, // ㄒㄩˋ 931
  (const spell PROGMEM) {"vm,"}, // ㄒㄩㄝ 932
  (const spell PROGMEM) {"vm,6"}, // ㄒㄩㄝˊ 933
  (const spell PROGMEM) {"vm,3"}, // ㄒㄩㄝˇ 934
  (const spell PROGMEM) {"vm,4"}, // ㄒㄩㄝˋ 935
  (const spell PROGMEM) {"vm0"}, // ㄒㄩㄢ 936
  (const spell PROGMEM) {"vm06"}, // ㄒㄩㄢˊ 937
  (const spell PROGMEM) {"vm03"}, // ㄒㄩㄢˇ 938
  (const spell PROGMEM) {"vm04"}, // ㄒㄩㄢˋ 939
  (const spell PROGMEM) {"vmp"}, // ㄒㄩㄣ 940
  (const spell PROGMEM) {"vmp6"}, // ㄒㄩㄣˊ 941
  (const spell PROGMEM) {"vmp4"}, // ㄒㄩㄣˋ 942
  (const spell PROGMEM) {"vm/"}, // ㄒㄩㄥ 943
  (const spell PROGMEM) {"vm/6"}, // ㄒㄩㄥˊ 944
  (const spell PROGMEM) {"vm/3"}, // ㄒㄩㄥˇ 945
  (const spell PROGMEM) {"vm/4"}, // ㄒㄩㄥˋ 946
  (const spell PROGMEM) {"5"}, // ㄓ 947
  (const spell PROGMEM) {"56"}, // ㄓˊ 948
  (const spell PROGMEM) {"53"}, // ㄓˇ 949
  (const spell PROGMEM) {"54"}, // ㄓˋ 950
  (const spell PROGMEM) {"58"}, // ㄓㄚ 951
  (const spell PROGMEM) {"586"}, // ㄓㄚˊ 952
  (const spell PROGMEM) {"583"}, // ㄓㄚˇ 953
  (const spell PROGMEM) {"584"}, // ㄓㄚˋ 954
  (const spell PROGMEM) {"5k"}, // ㄓㄜ 955
  (const spell PROGMEM) {"5k6"}, // ㄓㄜˊ 956
  (const spell PROGMEM) {"5k3"}, // ㄓㄜˇ 957
  (const spell PROGMEM) {"5k4"}, // ㄓㄜˋ 958
  (const spell PROGMEM) {"5k7"}, // ㄓㄜ˙ 959
  (const spell PROGMEM) {"59"}, // ㄓㄞ 960
  (const spell PROGMEM) {"596"}, // ㄓㄞˊ 961
  (const spell PROGMEM) {"593"}, // ㄓㄞˇ 962
  (const spell PROGMEM) {"594"}, // ㄓㄞˋ 963
  (const spell PROGMEM) {"5o4"}, // ㄓㄟˋ 964
  (const spell PROGMEM) {"5l"}, // ㄓㄠ 965
  (const spell PROGMEM) {"5l6"}, // ㄓㄠˊ 966
  (const spell PROGMEM) {"5l3"}, // ㄓㄠˇ 967
  (const spell PROGMEM) {"5l4"}, // ㄓㄠˋ 968
  (const spell PROGMEM) {"5."}, // ㄓㄡ 969
  (const spell PROGMEM) {"5.6"}, // ㄓㄡˊ 970
  (const spell PROGMEM) {"5.3"}, // ㄓㄡˇ 971
  (const spell PROGMEM) {"5.4"}, // ㄓㄡˋ 972
  (const spell PROGMEM) {"50"}, // ㄓㄢ 973
  (const spell PROGMEM) {"506"}, // ㄓㄢˊ 974
  (const spell PROGMEM) {"503"}, // ㄓㄢˇ 975
  (const spell PROGMEM) {"504"}, // ㄓㄢˋ 976
  (const spell PROGMEM) {"5p"}, // ㄓㄣ 977
  (const spell PROGMEM) {"5p6"}, // ㄓㄣˊ 978
  (const spell PROGMEM) {"5p3"}, // ㄓㄣˇ 979
  (const spell PROGMEM) {"5p4"}, // ㄓㄣˋ 980
  (const spell PROGMEM) {"5;"}, // ㄓㄤ 981
  (const spell PROGMEM) {"5;6"}, // ㄓㄤˊ 982
  (const spell PROGMEM) {"5;3"}, // ㄓㄤˇ 983
  (const spell PROGMEM) {"5;4"}, // ㄓㄤˋ 984
  (const spell PROGMEM) {"5/"}, // ㄓㄥ 985
  (const spell PROGMEM) {"5/6"}, // ㄓㄥˊ 986
  (const spell PROGMEM) {"5/3"}, // ㄓㄥˇ 987
  (const spell PROGMEM) {"5/4"}, // ㄓㄥˋ 988
  (const spell PROGMEM) {"5j"}, // ㄓㄨ 989
  (const spell PROGMEM) {"5j6"}, // ㄓㄨˊ 990
  (const spell PROGMEM) {"5j3"}, // ㄓㄨˇ 991
  (const spell PROGMEM) {"5j4"}, // ㄓㄨˋ 992
  (const spell PROGMEM) {"5j8"}, // ㄓㄨㄚ 993
  (const spell PROGMEM) {"5j86"}, // ㄓㄨㄚˊ 994
  (const spell PROGMEM) {"5j83"}, // ㄓㄨㄚˇ 995
  (const spell PROGMEM) {"5ji"}, // ㄓㄨㄛ 996
  (const spell PROGMEM) {"5ji6"}, // ㄓㄨㄛˊ 997
  (const spell PROGMEM) {"5j9"}, // ㄓㄨㄞ 998
  (const spell PROGMEM) {"5j93"}, // ㄓㄨㄞˇ 999
  (const spell PROGMEM) {"5j94"}, // ㄓㄨㄞˋ 1000
  (const spell PROGMEM) {"5jo"}, // ㄓㄨㄟ 1001
  (const spell PROGMEM) {"5jo4"}, // ㄓㄨㄟˋ 1002
  (const spell PROGMEM) {"5j0"}, // ㄓㄨㄢ 1003
  (const spell PROGMEM) {"5j06"}, // ㄓㄨㄢˊ 1004
  (const spell PROGMEM) {"5j03"}, // ㄓㄨㄢˇ 1005
  (const spell PROGMEM) {"5j04"}, // ㄓㄨㄢˋ 1006
  (const spell PROGMEM) {"5jp"}, // ㄓㄨㄣ 1007
  (const spell PROGMEM) {"5jp3"}, // ㄓㄨㄣˇ 1008
  (const spell PROGMEM) {"5j;"}, // ㄓㄨㄤ 1009
  (const spell PROGMEM) {"5j;3"}, // ㄓㄨㄤˇ 1010
  (const spell PROGMEM) {"5j;4"}, // ㄓㄨㄤˋ 1011
  (const spell PROGMEM) {"5j/"}, // ㄓㄨㄥ 1012
  (const spell PROGMEM) {"5j/6"}, // ㄓㄨㄥˊ 1013
  (const spell PROGMEM) {"5j/3"}, // ㄓㄨㄥˇ 1014
  (const spell PROGMEM) {"5j/4"}, // ㄓㄨㄥˋ 1015
  (const spell PROGMEM) {"t"}, // ㄔ 1016
  (const spell PROGMEM) {"t6"}, // ㄔˊ 1017
  (const spell PROGMEM) {"t3"}, // ㄔˇ 1018
  (const spell PROGMEM) {"t4"}, // ㄔˋ 1019
  (const spell PROGMEM) {"t8"}, // ㄔㄚ 1020
  (const spell PROGMEM) {"t86"}, // ㄔㄚˊ 1021
  (const spell PROGMEM) {"t83"}, // ㄔㄚˇ 1022
  (const spell PROGMEM) {"t84"}, // ㄔㄚˋ 1023
  (const spell PROGMEM) {"tk"}, // ㄔㄜ 1024
  (const spell PROGMEM) {"tk6"}, // ㄔㄜˊ 1025
  (const spell PROGMEM) {"tk3"}, // ㄔㄜˇ 1026
  (const spell PROGMEM) {"tk4"}, // ㄔㄜˋ 1027
  (const spell PROGMEM) {"t9"}, // ㄔㄞ 1028
  (const spell PROGMEM) {"t96"}, // ㄔㄞˊ 1029
  (const spell PROGMEM) {"t93"}, // ㄔㄞˇ 1030
  (const spell PROGMEM) {"t94"}, // ㄔㄞˋ 1031
  (const spell PROGMEM) {"tl"}, // ㄔㄠ 1032
  (const spell PROGMEM) {"tl6"}, // ㄔㄠˊ 1033
  (const spell PROGMEM) {"tl3"}, // ㄔㄠˇ 1034
  (const spell PROGMEM) {"tl4"}, // ㄔㄠˋ 1035
  (const spell PROGMEM) {"t."}, // ㄔㄡ 1036
  (const spell PROGMEM) {"t.6"}, // ㄔㄡˊ 1037
  (const spell PROGMEM) {"t.3"}, // ㄔㄡˇ 1038
  (const spell PROGMEM) {"t.4"}, // ㄔㄡˋ 1039
  (const spell PROGMEM) {"t0"}, // ㄔㄢ 1040
  (const spell PROGMEM) {"t06"}, // ㄔㄢˊ 1041
  (const spell PROGMEM) {"t03"}, // ㄔㄢˇ 1042
  (const spell PROGMEM) {"t04"}, // ㄔㄢˋ 1043
  (const spell PROGMEM) {"tp"}, // ㄔㄣ 1044
  (const spell PROGMEM) {"tp6"}, // ㄔㄣˊ 1045
  (const spell PROGMEM) {"tp3"}, // ㄔㄣˇ 1046
  (const spell PROGMEM) {"tp4"}, // ㄔㄣˋ 1047
  (const spell PROGMEM) {"t;"}, // ㄔㄤ 1048
  (const spell PROGMEM) {"t;6"}, // ㄔㄤˊ 1049
  (const spell PROGMEM) {"t;3"}, // ㄔㄤˇ 1050
  (const spell PROGMEM) {"t;4"}, // ㄔㄤˋ 1051
  (const spell PROGMEM) {"t/"}, // ㄔㄥ 1052
  (const spell PROGMEM) {"t/6"}, // ㄔㄥˊ 1053
  (const spell PROGMEM) {"t/3"}, // ㄔㄥˇ 1054
  (const spell PROGMEM) {"t/4"}, // ㄔㄥˋ 1055
  (const spell PROGMEM) {"tj"}, // ㄔㄨ 1056
  (const spell PROGMEM) {"tj6"}, // ㄔㄨˊ 1057
  (const spell PROGMEM) {"tj3"}, // ㄔㄨˇ 1058
  (const spell PROGMEM) {"tj4"}, // ㄔㄨˋ 1059
  (const spell PROGMEM) {"tj8"}, // ㄔㄨㄚ 1060
  (const spell PROGMEM) {"tj83"}, // ㄔㄨㄚˇ 1061
  (const spell PROGMEM) {"tj84"}, // ㄔㄨㄚˋ 1062
  (const spell PROGMEM) {"tji"}, // ㄔㄨㄛ 1063
  (const spell PROGMEM) {"tji4"}, // ㄔㄨㄛˋ 1064
  (const spell PROGMEM) {"tj9"}, // ㄔㄨㄞ 1065
  (const spell PROGMEM) {"tj93"}, // ㄔㄨㄞˇ 1066
  (const spell PROGMEM) {"tj94"}, // ㄔㄨㄞˋ 1067
  (const spell PROGMEM) {"tjo"}, // ㄔㄨㄟ 1068
  (const spell PROGMEM) {"tjo6"}, // ㄔㄨㄟˊ 1069
  (const spell PROGMEM) {"tjo4"}, // ㄔㄨㄟˋ 1070
  (const spell PROGMEM) {"tj0"}, // ㄔㄨㄢ 1071
  (const spell PROGMEM) {"tj06"}, // ㄔㄨㄢˊ 1072
  (const spell PROGMEM) {"tj03"}, // ㄔㄨㄢˇ 1073
  (const spell PROGMEM) {"tj04"}, // ㄔㄨㄢˋ 1074
  (const spell PROGMEM) {"tjp"}, // ㄔㄨㄣ 1075
  (const spell PROGMEM) {"tjp6"}, // ㄔㄨㄣˊ 1076
  (const spell PROGMEM) {"tjp3"}, // ㄔㄨㄣˇ 1077
  (const spell PROGMEM) {"tj;"}, // ㄔㄨㄤ 1078
  (const spell PROGMEM) {"tj;6"}, // ㄔㄨㄤˊ 1079
  (const spell PROGMEM) {"tj;3"}, // ㄔㄨㄤˇ 1080
  (const spell PROGMEM) {"tj;4"}, // ㄔㄨㄤˋ 1081
  (const spell PROGMEM) {"tj/"}, // ㄔㄨㄥ 1082
  (const spell PROGMEM) {"tj/6"}, // ㄔㄨㄥˊ 1083
  (const spell PROGMEM) {"tj/3"}, // ㄔㄨㄥˇ 1084
  (const spell PROGMEM) {"tj/4"}, // ㄔㄨㄥˋ 1085
  (const spell PROGMEM) {"g"}, // ㄕ 1086
  (const spell PROGMEM) {"g6"}, // ㄕˊ 1087
  (const spell PROGMEM) {"g3"}, // ㄕˇ 1088
  (const spell PROGMEM) {"g4"}, // ㄕˋ 1089
  (const spell PROGMEM) {"g7"}, // ㄕ˙ 1090
  (const spell PROGMEM) {"g8"}, // ㄕㄚ 1091
  (const spell PROGMEM) {"g86"}, // ㄕㄚˊ 1092
  (const spell PROGMEM) {"g83"}, // ㄕㄚˇ 1093
  (const spell PROGMEM) {"g84"}, // ㄕㄚˋ 1094
  (const spell PROGMEM) {"gk"}, // ㄕㄜ 1095
  (const spell PROGMEM) {"gk6"}, // ㄕㄜˊ 1096
  (const spell PROGMEM) {"gk3"}, // ㄕㄜˇ 1097
  (const spell PROGMEM) {"gk4"}, // ㄕㄜˋ 1098
  (const spell PROGMEM) {"g9"}, // ㄕㄞ 1099
  (const spell PROGMEM) {"g93"}, // ㄕㄞˇ 1100
  (const spell PROGMEM) {"g94"}, // ㄕㄞˋ 1101
  (const spell PROGMEM) {"go6"}, // ㄕㄟˊ 1102
  (const spell PROGMEM) {"gl"}, // ㄕㄠ 1103
  (const spell PROGMEM) {"gl6"}, // ㄕㄠˊ 1104
  (const spell PROGMEM) {"gl3"}, // ㄕㄠˇ 1105
  (const spell PROGMEM) {"gl4"}, // ㄕㄠˋ 1106
  (const spell PROGMEM) {"g."}, // ㄕㄡ 1107
  (const spell PROGMEM) {"g.6"}, // ㄕㄡˊ 1108
  (const spell PROGMEM) {"g.3"}, // ㄕㄡˇ 1109
  (const spell PROGMEM) {"g.4"}, // ㄕㄡˋ 1110
  (const spell PROGMEM) {"g0"}, // ㄕㄢ 1111
  (const spell PROGMEM) {"g06"}, // ㄕㄢˊ 1112
  (const spell PROGMEM) {"g03"}, // ㄕㄢˇ 1113
  (const spell PROGMEM) {"g04"}, // ㄕㄢˋ 1114
  (const spell PROGMEM) {"gp"}, // ㄕㄣ 1115
  (const spell PROGMEM) {"gp6"}, // ㄕㄣˊ 1116
  (const spell PROGMEM) {"gp3"}, // ㄕㄣˇ 1117
  (const spell PROGMEM) {"gp4"}, // ㄕㄣˋ 1118
  (const spell PROGMEM) {"g;"}, // ㄕㄤ 1119
  (const spell PROGMEM) {"g;6"}, // ㄕㄤˊ 1120
  (const spell PROGMEM) {"g;3"}, // ㄕㄤˇ 1121
  (const spell PROGMEM) {"g;4"}, // ㄕㄤˋ 1122
  (const spell PROGMEM) {"g/"}, // ㄕㄥ 1123
  (const spell PROGMEM) {"g/6"}, // ㄕㄥˊ 1124
  (const spell PROGMEM) {"g/3"}, // ㄕㄥˇ 1125
  (const spell PROGMEM) {"g/4"}, // ㄕㄥˋ 1126
  (const spell PROGMEM) {"g/7"}, // ㄕㄥ˙ 1127
  (const spell PROGMEM) {"gj"}, // ㄕㄨ 1128
  (const spell PROGMEM) {"gj6"}, // ㄕㄨˊ 1129
  (const spell PROGMEM) {"gj3"}, // ㄕㄨˇ 1130
  (const spell PROGMEM) {"gj4"}, // ㄕㄨˋ 1131
  (const spell PROGMEM) {"gj7"}, // ㄕㄨ˙ 1132
  (const spell PROGMEM) {"gj8"}, // ㄕㄨㄚ 1133
  (const spell PROGMEM) {"gj86"}, // ㄕㄨㄚˊ 1134
  (const spell PROGMEM) {"gj83"}, // ㄕㄨㄚˇ 1135
  (const spell PROGMEM) {"gj84"}, // ㄕㄨㄚˋ 1136
  (const spell PROGMEM) {"gji"}, // ㄕㄨㄛ 1137
  (const spell PROGMEM) {"gji4"}, // ㄕㄨㄛˋ 1138
  (const spell PROGMEM) {"gj9"}, // ㄕㄨㄞ 1139
  (const spell PROGMEM) {"gj93"}, // ㄕㄨㄞˇ 1140
  (const spell PROGMEM) {"gj94"}, // ㄕㄨㄞˋ 1141
  (const spell PROGMEM) {"gjo6"}, // ㄕㄨㄟˊ 1142
  (const spell PROGMEM) {"gjo3"}, // ㄕㄨㄟˇ 1143
  (const spell PROGMEM) {"gjo4"}, // ㄕㄨㄟˋ 1144
  (const spell PROGMEM) {"gj0"}, // ㄕㄨㄢ 1145
  (const spell PROGMEM) {"gj04"}, // ㄕㄨㄢˋ 1146
  (const spell PROGMEM) {"gjp3"}, // ㄕㄨㄣˇ 1147
  (const spell PROGMEM) {"gjp4"}, // ㄕㄨㄣˋ 1148
  (const spell PROGMEM) {"gj;"}, // ㄕㄨㄤ 1149
  (const spell PROGMEM) {"gj;6"}, // ㄕㄨㄤˊ 1150
  (const spell PROGMEM) {"gj;3"}, // ㄕㄨㄤˇ 1151
  (const spell PROGMEM) {"gj;4"}, // ㄕㄨㄤˋ 1152
  (const spell PROGMEM) {"b4"}, // ㄖˋ 1153
  (const spell PROGMEM) {"bk3"}, // ㄖㄜˇ 1154
  (const spell PROGMEM) {"bk4"}, // ㄖㄜˋ 1155
  (const spell PROGMEM) {"bl6"}, // ㄖㄠˊ 1156
  (const spell PROGMEM) {"bl3"}, // ㄖㄠˇ 1157
  (const spell PROGMEM) {"bl4"}, // ㄖㄠˋ 1158
  (const spell PROGMEM) {"b.6"}, // ㄖㄡˊ 1159
  (const spell PROGMEM) {"b.3"}, // ㄖㄡˇ 1160
  (const spell PROGMEM) {"b.4"}, // ㄖㄡˋ 1161
  (const spell PROGMEM) {"b06"}, // ㄖㄢˊ 1162
  (const spell PROGMEM) {"b03"}, // ㄖㄢˇ 1163
  (const spell PROGMEM) {"bp6"}, // ㄖㄣˊ 1164
  (const spell PROGMEM) {"bp3"}, // ㄖㄣˇ 1165
  (const spell PROGMEM) {"bp4"}, // ㄖㄣˋ 1166
  (const spell PROGMEM) {"b;"}, // ㄖㄤ 1167
  (const spell PROGMEM) {"b;6"}, // ㄖㄤˊ 1168
  (const spell PROGMEM) {"b;3"}, // ㄖㄤˇ 1169
  (const spell PROGMEM) {"b;4"}, // ㄖㄤˋ 1170
  (const spell PROGMEM) {"b/"}, // ㄖㄥ 1171
  (const spell PROGMEM) {"b/6"}, // ㄖㄥˊ 1172
  (const spell PROGMEM) {"b/3"}, // ㄖㄥˇ 1173
  (const spell PROGMEM) {"bj6"}, // ㄖㄨˊ 1174
  (const spell PROGMEM) {"bj3"}, // ㄖㄨˇ 1175
  (const spell PROGMEM) {"bj4"}, // ㄖㄨˋ 1176
  (const spell PROGMEM) {"bji6"}, // ㄖㄨㄛˊ 1177
  (const spell PROGMEM) {"bji4"}, // ㄖㄨㄛˋ 1178
  (const spell PROGMEM) {"bjo6"}, // ㄖㄨㄟˊ 1179
  (const spell PROGMEM) {"bjo3"}, // ㄖㄨㄟˇ 1180
  (const spell PROGMEM) {"bjo4"}, // ㄖㄨㄟˋ 1181
  (const spell PROGMEM) {"bj06"}, // ㄖㄨㄢˊ 1182
  (const spell PROGMEM) {"bj03"}, // ㄖㄨㄢˇ 1183
  (const spell PROGMEM) {"bjp4"}, // ㄖㄨㄣˋ 1184
  (const spell PROGMEM) {"bj/6"}, // ㄖㄨㄥˊ 1185
  (const spell PROGMEM) {"bj/3"}, // ㄖㄨㄥˇ 1186
  (const spell PROGMEM) {"bj/7"}, // ㄖㄨㄥ˙ 1187
  (const spell PROGMEM) {"y"}, // ㄗ 1188
  (const spell PROGMEM) {"y6"}, // ㄗˊ 1189
  (const spell PROGMEM) {"y3"}, // ㄗˇ 1190
  (const spell PROGMEM) {"y4"}, // ㄗˋ 1191
  (const spell PROGMEM) {"y7"}, // ㄗ˙ 1192
  (const spell PROGMEM) {"y8"}, // ㄗㄚ 1193
  (const spell PROGMEM) {"y86"}, // ㄗㄚˊ 1194
  (const spell PROGMEM) {"yk6"}, // ㄗㄜˊ 1195
  (const spell PROGMEM) {"yk3"}, // ㄗㄜˇ 1196
  (const spell PROGMEM) {"yk4"}, // ㄗㄜˋ 1197
  (const spell PROGMEM) {"y9"}, // ㄗㄞ 1198
  (const spell PROGMEM) {"y96"}, // ㄗㄞˊ 1199
  (const spell PROGMEM) {"y93"}, // ㄗㄞˇ 1200
  (const spell PROGMEM) {"y94"}, // ㄗㄞˋ 1201
  (const spell PROGMEM) {"yo6"}, // ㄗㄟˊ 1202
  (const spell PROGMEM) {"yl"}, // ㄗㄠ 1203
  (const spell PROGMEM) {"yl6"}, // ㄗㄠˊ 1204
  (const spell PROGMEM) {"yl3"}, // ㄗㄠˇ 1205
  (const spell PROGMEM) {"yl4"}, // ㄗㄠˋ 1206
  (const spell PROGMEM) {"y."}, // ㄗㄡ 1207
  (const spell PROGMEM) {"y.6"}, // ㄗㄡˊ 1208
  (const spell PROGMEM) {"y.3"}, // ㄗㄡˇ 1209
  (const spell PROGMEM) {"y.4"}, // ㄗㄡˋ 1210
  (const spell PROGMEM) {"y0"}, // ㄗㄢ 1211
  (const spell PROGMEM) {"y06"}, // ㄗㄢˊ 1212
  (const spell PROGMEM) {"y03"}, // ㄗㄢˇ 1213
  (const spell PROGMEM) {"y04"}, // ㄗㄢˋ 1214
  (const spell PROGMEM) {"yp"}, // ㄗㄣ 1215
  (const spell PROGMEM) {"yp3"}, // ㄗㄣˇ 1216
  (const spell PROGMEM) {"yp4"}, // ㄗㄣˋ 1217
  (const spell PROGMEM) {"y;"}, // ㄗㄤ 1218
  (const spell PROGMEM) {"y;6"}, // ㄗㄤˊ 1219
  (const spell PROGMEM) {"y;3"}, // ㄗㄤˇ 1220
  (const spell PROGMEM) {"y;4"}, // ㄗㄤˋ 1221
  (const spell PROGMEM) {"y/"}, // ㄗㄥ 1222
  (const spell PROGMEM) {"y/4"}, // ㄗㄥˋ 1223
  (const spell PROGMEM) {"yj"}, // ㄗㄨ 1224
  (const spell PROGMEM) {"yj6"}, // ㄗㄨˊ 1225
  (const spell PROGMEM) {"yj3"}, // ㄗㄨˇ 1226
  (const spell PROGMEM) {"yj4"}, // ㄗㄨˋ 1227
  (const spell PROGMEM) {"yji"}, // ㄗㄨㄛ 1228
  (const spell PROGMEM) {"yji6"}, // ㄗㄨㄛˊ 1229
  (const spell PROGMEM) {"yji3"}, // ㄗㄨㄛˇ 1230
  (const spell PROGMEM) {"yji4"}, // ㄗㄨㄛˋ 1231
  (const spell PROGMEM) {"yjo"}, // ㄗㄨㄟ 1232
  (const spell PROGMEM) {"yjo6"}, // ㄗㄨㄟˊ 1233
  (const spell PROGMEM) {"yjo3"}, // ㄗㄨㄟˇ 1234
  (const spell PROGMEM) {"yjo4"}, // ㄗㄨㄟˋ 1235
  (const spell PROGMEM) {"yj0"}, // ㄗㄨㄢ 1236
  (const spell PROGMEM) {"yj06"}, // ㄗㄨㄢˊ 1237
  (const spell PROGMEM) {"yj03"}, // ㄗㄨㄢˇ 1238
  (const spell PROGMEM) {"yj04"}, // ㄗㄨㄢˋ 1239
  (const spell PROGMEM) {"yjp"}, // ㄗㄨㄣ 1240
  (const spell PROGMEM) {"yjp6"}, // ㄗㄨㄣˊ 1241
  (const spell PROGMEM) {"yjp3"}, // ㄗㄨㄣˇ 1242
  (const spell PROGMEM) {"yjp4"}, // ㄗㄨㄣˋ 1243
  (const spell PROGMEM) {"yj/"}, // ㄗㄨㄥ 1244
  (const spell PROGMEM) {"yj/6"}, // ㄗㄨㄥˊ 1245
  (const spell PROGMEM) {"yj/3"}, // ㄗㄨㄥˇ 1246
  (const spell PROGMEM) {"yj/4"}, // ㄗㄨㄥˋ 1247
  (const spell PROGMEM) {"h"}, // ㄘ 1248
  (const spell PROGMEM) {"h6"}, // ㄘˊ 1249
  (const spell PROGMEM) {"h3"}, // ㄘˇ 1250
  (const spell PROGMEM) {"h4"}, // ㄘˋ 1251
  (const spell PROGMEM) {"h8"}, // ㄘㄚ 1252
  (const spell PROGMEM) {"h86"}, // ㄘㄚˊ 1253
  (const spell PROGMEM) {"h83"}, // ㄘㄚˇ 1254
  (const spell PROGMEM) {"hk4"}, // ㄘㄜˋ 1255
  (const spell PROGMEM) {"h9"}, // ㄘㄞ 1256
  (const spell PROGMEM) {"h96"}, // ㄘㄞˊ 1257
  (const spell PROGMEM) {"h93"}, // ㄘㄞˇ 1258
  (const spell PROGMEM) {"h94"}, // ㄘㄞˋ 1259
  (const spell PROGMEM) {"hl"}, // ㄘㄠ 1260
  (const spell PROGMEM) {"hl6"}, // ㄘㄠˊ 1261
  (const spell PROGMEM) {"hl3"}, // ㄘㄠˇ 1262
  (const spell PROGMEM) {"hl4"}, // ㄘㄠˋ 1263
  (const spell PROGMEM) {"h.4"}, // ㄘㄡˋ 1264
  (const spell PROGMEM) {"h0"}, // ㄘㄢ 1265
  (const spell PROGMEM) {"h06"}, // ㄘㄢˊ 1266
  (const spell PROGMEM) {"h03"}, // ㄘㄢˇ 1267
  (const spell PROGMEM) {"h04"}, // ㄘㄢˋ 1268
  (const spell PROGMEM) {"hp"}, // ㄘㄣ 1269
  (const spell PROGMEM) {"hp6"}, // ㄘㄣˊ 1270
  (const spell PROGMEM) {"h;"}, // ㄘㄤ 1271
  (const spell PROGMEM) {"h;6"}, // ㄘㄤˊ 1272
  (const spell PROGMEM) {"h;3"}, // ㄘㄤˇ 1273
  (const spell PROGMEM) {"h/"}, // ㄘㄥ 1274
  (const spell PROGMEM) {"h/6"}, // ㄘㄥˊ 1275
  (const spell PROGMEM) {"h/3"}, // ㄘㄥˇ 1276
  (const spell PROGMEM) {"h/4"}, // ㄘㄥˋ 1277
  (const spell PROGMEM) {"hj"}, // ㄘㄨ 1278
  (const spell PROGMEM) {"hj6"}, // ㄘㄨˊ 1279
  (const spell PROGMEM) {"hj4"}, // ㄘㄨˋ 1280
  (const spell PROGMEM) {"hji"}, // ㄘㄨㄛ 1281
  (const spell PROGMEM) {"hji6"}, // ㄘㄨㄛˊ 1282
  (const spell PROGMEM) {"hji3"}, // ㄘㄨㄛˇ 1283
  (const spell PROGMEM) {"hji4"}, // ㄘㄨㄛˋ 1284
  (const spell PROGMEM) {"hjo"}, // ㄘㄨㄟ 1285
  (const spell PROGMEM) {"hjo6"}, // ㄘㄨㄟˊ 1286
  (const spell PROGMEM) {"hjo3"}, // ㄘㄨㄟˇ 1287
  (const spell PROGMEM) {"hjo4"}, // ㄘㄨㄟˋ 1288
  (const spell PROGMEM) {"hj0"}, // ㄘㄨㄢ 1289
  (const spell PROGMEM) {"hj06"}, // ㄘㄨㄢˊ 1290
  (const spell PROGMEM) {"hj04"}, // ㄘㄨㄢˋ 1291
  (const spell PROGMEM) {"hjp"}, // ㄘㄨㄣ 1292
  (const spell PROGMEM) {"hjp6"}, // ㄘㄨㄣˊ 1293
  (const spell PROGMEM) {"hjp3"}, // ㄘㄨㄣˇ 1294
  (const spell PROGMEM) {"hjp4"}, // ㄘㄨㄣˋ 1295
  (const spell PROGMEM) {"hj/"}, // ㄘㄨㄥ 1296
  (const spell PROGMEM) {"hj/6"}, // ㄘㄨㄥˊ 1297
  (const spell PROGMEM) {"n"}, // ㄙ 1298
  (const spell PROGMEM) {"n6"}, // ㄙˊ 1299
  (const spell PROGMEM) {"n3"}, // ㄙˇ 1300
  (const spell PROGMEM) {"n4"}, // ㄙˋ 1301
  (const spell PROGMEM) {"n7"}, // ㄙ˙ 1302
  (const spell PROGMEM) {"n8"}, // ㄙㄚ 1303
  (const spell PROGMEM) {"n86"}, // ㄙㄚˊ 1304
  (const spell PROGMEM) {"n83"}, // ㄙㄚˇ 1305
  (const spell PROGMEM) {"n84"}, // ㄙㄚˋ 1306
  (const spell PROGMEM) {"n87"}, // ㄙㄚ˙ 1307
  (const spell PROGMEM) {"nk4"}, // ㄙㄜˋ 1308
  (const spell PROGMEM) {"n9"}, // ㄙㄞ 1309
  (const spell PROGMEM) {"n94"}, // ㄙㄞˋ 1310
  (const spell PROGMEM) {"no"}, // ㄙㄟ 1311
  (const spell PROGMEM) {"nl"}, // ㄙㄠ 1312
  (const spell PROGMEM) {"nl6"}, // ㄙㄠˊ 1313
  (const spell PROGMEM) {"nl3"}, // ㄙㄠˇ 1314
  (const spell PROGMEM) {"nl4"}, // ㄙㄠˋ 1315
  (const spell PROGMEM) {"n."}, // ㄙㄡ 1316
  (const spell PROGMEM) {"n.6"}, // ㄙㄡˊ 1317
  (const spell PROGMEM) {"n.3"}, // ㄙㄡˇ 1318
  (const spell PROGMEM) {"n.4"}, // ㄙㄡˋ 1319
  (const spell PROGMEM) {"n0"}, // ㄙㄢ 1320
  (const spell PROGMEM) {"n06"}, // ㄙㄢˊ 1321
  (const spell PROGMEM) {"n03"}, // ㄙㄢˇ 1322
  (const spell PROGMEM) {"n04"}, // ㄙㄢˋ 1323
  (const spell PROGMEM) {"np"}, // ㄙㄣ 1324
  (const spell PROGMEM) {"n;"}, // ㄙㄤ 1325
  (const spell PROGMEM) {"n;6"}, // ㄙㄤˊ 1326
  (const spell PROGMEM) {"n;3"}, // ㄙㄤˇ 1327
  (const spell PROGMEM) {"n;4"}, // ㄙㄤˋ 1328
  (const spell PROGMEM) {"n/"}, // ㄙㄥ 1329
  (const spell PROGMEM) {"nj"}, // ㄙㄨ 1330
  (const spell PROGMEM) {"nj6"}, // ㄙㄨˊ 1331
  (const spell PROGMEM) {"nj4"}, // ㄙㄨˋ 1332
  (const spell PROGMEM) {"nji"}, // ㄙㄨㄛ 1333
  (const spell PROGMEM) {"nji6"}, // ㄙㄨㄛˊ 1334
  (const spell PROGMEM) {"nji3"}, // ㄙㄨㄛˇ 1335
  (const spell PROGMEM) {"nji4"}, // ㄙㄨㄛˋ 1336
  (const spell PROGMEM) {"njo"}, // ㄙㄨㄟ 1337
  (const spell PROGMEM) {"njo6"}, // ㄙㄨㄟˊ 1338
  (const spell PROGMEM) {"njo3"}, // ㄙㄨㄟˇ 1339
  (const spell PROGMEM) {"njo4"}, // ㄙㄨㄟˋ 1340
  (const spell PROGMEM) {"nj0"}, // ㄙㄨㄢ 1341
  (const spell PROGMEM) {"nj06"}, // ㄙㄨㄢˊ 1342
  (const spell PROGMEM) {"nj03"}, // ㄙㄨㄢˇ 1343
  (const spell PROGMEM) {"nj04"}, // ㄙㄨㄢˋ 1344
  (const spell PROGMEM) {"njp"}, // ㄙㄨㄣ 1345
  (const spell PROGMEM) {"njp6"}, // ㄙㄨㄣˊ 1346
  (const spell PROGMEM) {"njp3"}, // ㄙㄨㄣˇ 1347
  (const spell PROGMEM) {"njp4"}, // ㄙㄨㄣˋ 1348
  (const spell PROGMEM) {"nj/"}, // ㄙㄨㄥ 1349
  (const spell PROGMEM) {"nj/6"}, // ㄙㄨㄥˊ 1350
  (const spell PROGMEM) {"nj/3"}, // ㄙㄨㄥˇ 1351
  (const spell PROGMEM) {"nj/4"}, // ㄙㄨㄥˋ 1352
  (const spell PROGMEM) {"8"}, // ㄚ 1353
  (const spell PROGMEM) {"86"}, // ㄚˊ 1354
  (const spell PROGMEM) {"83"}, // ㄚˇ 1355
  (const spell PROGMEM) {"84"}, // ㄚˋ 1356
  (const spell PROGMEM) {"87"}, // ㄚ˙ 1357
  (const spell PROGMEM) {"i"}, // ㄛ 1358
  (const spell PROGMEM) {"i6"}, // ㄛˊ 1359
  (const spell PROGMEM) {"i3"}, // ㄛˇ 1360
  (const spell PROGMEM) {"i4"}, // ㄛˋ 1361
  (const spell PROGMEM) {"i7"}, // ㄛ˙ 1362
  (const spell PROGMEM) {"k"}, // ㄜ 1363
  (const spell PROGMEM) {"k6"}, // ㄜˊ 1364
  (const spell PROGMEM) {"k3"}, // ㄜˇ 1365
  (const spell PROGMEM) {"k4"}, // ㄜˋ 1366
  (const spell PROGMEM) {","}, // ㄝ 1367
  (const spell PROGMEM) {",4"}, // ㄝˋ 1368
  (const spell PROGMEM) {"9"}, // ㄞ 1369
  (const spell PROGMEM) {"96"}, // ㄞˊ 1370
  (const spell PROGMEM) {"93"}, // ㄞˇ 1371
  (const spell PROGMEM) {"94"}, // ㄞˋ 1372
  (const spell PROGMEM) {"97"}, // ㄞ˙ 1373
  (const spell PROGMEM) {"o"}, // ㄟ 1374
  (const spell PROGMEM) {"o6"}, // ㄟˊ 1375
  (const spell PROGMEM) {"o3"}, // ㄟˇ 1376
  (const spell PROGMEM) {"o4"}, // ㄟˋ 1377
  (const spell PROGMEM) {"o7"}, // ㄟ˙ 1378
  (const spell PROGMEM) {"l"}, // ㄠ 1379
  (const spell PROGMEM) {"l6"}, // ㄠˊ 1380
  (const spell PROGMEM) {"l3"}, // ㄠˇ 1381
  (const spell PROGMEM) {"l4"}, // ㄠˋ 1382
  (const spell PROGMEM) {"."}, // ㄡ 1383
  (const spell PROGMEM) {".6"}, // ㄡˊ 1384
  (const spell PROGMEM) {".3"}, // ㄡˇ 1385
  (const spell PROGMEM) {".4"}, // ㄡˋ 1386
  (const spell PROGMEM) {"0"}, // ㄢ 1387
  (const spell PROGMEM) {"06"}, // ㄢˊ 1388
  (const spell PROGMEM) {"03"}, // ㄢˇ 1389
  (const spell PROGMEM) {"04"}, // ㄢˋ 1390
  (const spell PROGMEM) {"p"}, // ㄣ 1391
  (const spell PROGMEM) {"p4"}, // ㄣˋ 1392
  (const spell PROGMEM) {";"}, // ㄤ 1393
  (const spell PROGMEM) {";6"}, // ㄤˊ 1394
  (const spell PROGMEM) {";4"}, // ㄤˋ 1395
  (const spell PROGMEM) {"-"}, // ㄦ 1396
  (const spell PROGMEM) {"-6"}, // ㄦˊ 1397
  (const spell PROGMEM) {"-3"}, // ㄦˇ 1398
  (const spell PROGMEM) {"-4"}, // ㄦˋ 1399
  (const spell PROGMEM) {"u"}, // ㄧ 1400
  (const spell PROGMEM) {"u6"}, // ㄧˊ 1401
  (const spell PROGMEM) {"u3"}, // ㄧˇ 1402
  (const spell PROGMEM) {"u4"}, // ㄧˋ 1403
  (const spell PROGMEM) {"u8"}, // ㄧㄚ 1404
  (const spell PROGMEM) {"u86"}, // ㄧㄚˊ 1405
  (const spell PROGMEM) {"u83"}, // ㄧㄚˇ 1406
  (const spell PROGMEM) {"u84"}, // ㄧㄚˋ 1407
  (const spell PROGMEM) {"u87"}, // ㄧㄚ˙ 1408
  (const spell PROGMEM) {"ui"}, // ㄧㄛ 1409
  (const spell PROGMEM) {"ui4"}, // ㄧㄛˋ 1410
  (const spell PROGMEM) {"u,"}, // ㄧㄝ 1411
  (const spell PROGMEM) {"u,6"}, // ㄧㄝˊ 1412
  (const spell PROGMEM) {"u,3"}, // ㄧㄝˇ 1413
  (const spell PROGMEM) {"u,4"}, // ㄧㄝˋ 1414
  (const spell PROGMEM) {"u,7"}, // ㄧㄝ˙ 1415
  (const spell PROGMEM) {"u96"}, // ㄧㄞˊ 1416
  (const spell PROGMEM) {"ul"}, // ㄧㄠ 1417
  (const spell PROGMEM) {"ul6"}, // ㄧㄠˊ 1418
  (const spell PROGMEM) {"ul3"}, // ㄧㄠˇ 1419
  (const spell PROGMEM) {"ul4"}, // ㄧㄠˋ 1420
  (const spell PROGMEM) {"u."}, // ㄧㄡ 1421
  (const spell PROGMEM) {"u.6"}, // ㄧㄡˊ 1422
  (const spell PROGMEM) {"u.3"}, // ㄧㄡˇ 1423
  (const spell PROGMEM) {"u.4"}, // ㄧㄡˋ 1424
  (const spell PROGMEM) {"u0"}, // ㄧㄢ 1425
  (const spell PROGMEM) {"u06"}, // ㄧㄢˊ 1426
  (const spell PROGMEM) {"u03"}, // ㄧㄢˇ 1427
  (const spell PROGMEM) {"u04"}, // ㄧㄢˋ 1428
  (const spell PROGMEM) {"up"}, // ㄧㄣ 1429
  (const spell PROGMEM) {"up6"}, // ㄧㄣˊ 1430
  (const spell PROGMEM) {"up3"}, // ㄧㄣˇ 1431
  (const spell PROGMEM) {"up4"}, // ㄧㄣˋ 1432
  (const spell PROGMEM) {"u;"}, // ㄧㄤ 1433
  (const spell PROGMEM) {"u;6"}, // ㄧㄤˊ 1434
  (const spell PROGMEM) {"u;3"}, // ㄧㄤˇ 1435
  (const spell PROGMEM) {"u;4"}, // ㄧㄤˋ 1436
  (const spell PROGMEM) {"u/"}, // ㄧㄥ 1437
  (const spell PROGMEM) {"u/6"}, // ㄧㄥˊ 1438
  (const spell PROGMEM) {"u/3"}, // ㄧㄥˇ 1439
  (const spell PROGMEM) {"u/4"}, // ㄧㄥˋ 1440
  (const spell PROGMEM) {"j"}, // ㄨ 1441
  (const spell PROGMEM) {"j6"}, // ㄨˊ 1442
  (const spell PROGMEM) {"j3"}, // ㄨˇ 1443
  (const spell PROGMEM) {"j4"}, // ㄨˋ 1444
  (const spell PROGMEM) {"j8"}, // ㄨㄚ 1445
  (const spell PROGMEM) {"j86"}, // ㄨㄚˊ 1446
  (const spell PROGMEM) {"j83"}, // ㄨㄚˇ 1447
  (const spell PROGMEM) {"j84"}, // ㄨㄚˋ 1448
  (const spell PROGMEM) {"j87"}, // ㄨㄚ˙ 1449
  (const spell PROGMEM) {"ji"}, // ㄨㄛ 1450
  (const spell PROGMEM) {"ji6"}, // ㄨㄛˊ 1451
  (const spell PROGMEM) {"ji3"}, // ㄨㄛˇ 1452
  (const spell PROGMEM) {"ji4"}, // ㄨㄛˋ 1453
  (const spell PROGMEM) {"j9"}, // ㄨㄞ 1454
  (const spell PROGMEM) {"j93"}, // ㄨㄞˇ 1455
  (const spell PROGMEM) {"j94"}, // ㄨㄞˋ 1456
  (const spell PROGMEM) {"jo"}, // ㄨㄟ 1457
  (const spell PROGMEM) {"jo6"}, // ㄨㄟˊ 1458
  (const spell PROGMEM) {"jo3"}, // ㄨㄟˇ 1459
  (const spell PROGMEM) {"jo4"}, // ㄨㄟˋ 1460
  (const spell PROGMEM) {"j0"}, // ㄨㄢ 1461
  (const spell PROGMEM) {"j06"}, // ㄨㄢˊ 1462
  (const spell PROGMEM) {"j03"}, // ㄨㄢˇ 1463
  (const spell PROGMEM) {"j04"}, // ㄨㄢˋ 1464
  (const spell PROGMEM) {"jp"}, // ㄨㄣ 1465
  (const spell PROGMEM) {"jp6"}, // ㄨㄣˊ 1466
  (const spell PROGMEM) {"jp3"}, // ㄨㄣˇ 1467
  (const spell PROGMEM) {"jp4"}, // ㄨㄣˋ 1468
  (const spell PROGMEM) {"j;"}, // ㄨㄤ 1469
  (const spell PROGMEM) {"j;6"}, // ㄨㄤˊ 1470
  (const spell PROGMEM) {"j;3"}, // ㄨㄤˇ 1471
  (const spell PROGMEM) {"j;4"}, // ㄨㄤˋ 1472
  (const spell PROGMEM) {"j/"}, // ㄨㄥ 1473
  (const spell PROGMEM) {"j/6"}, // ㄨㄥˊ 1474
  (const spell PROGMEM) {"j/3"}, // ㄨㄥˇ 1475
  (const spell PROGMEM) {"j/4"}, // ㄨㄥˋ 1476
  (const spell PROGMEM) {"m"}, // ㄩ 1477
  (const spell PROGMEM) {"m6"}, // ㄩˊ 1478
  (const spell PROGMEM) {"m3"}, // ㄩˇ 1479
  (const spell PROGMEM) {"m4"}, // ㄩˋ 1480
  (const spell PROGMEM) {"m,"}, // ㄩㄝ 1481
  (const spell PROGMEM) {"m,4"}, // ㄩㄝˋ 1482
  (const spell PROGMEM) {"m0"}, // ㄩㄢ 1483
  (const spell PROGMEM) {"m06"}, // ㄩㄢˊ 1484
  (const spell PROGMEM) {"m03"}, // ㄩㄢˇ 1485
  (const spell PROGMEM) {"m04"}, // ㄩㄢˋ 1486
  (const spell PROGMEM) {"mp"}, // ㄩㄣ 1487
  (const spell PROGMEM) {"mp6"}, // ㄩㄣˊ 1488
  (const spell PROGMEM) {"mp3"}, // ㄩㄣˇ 1489
  (const spell PROGMEM) {"mp4"}, // ㄩㄣˋ 1490
  (const spell PROGMEM) {"m/"}, // ㄩㄥ 1491
  (const spell PROGMEM) {"m/6"}, // ㄩㄥˊ 1492
  (const spell PROGMEM) {"m/3"}, // ㄩㄥˇ 1493
  (const spell PROGMEM) {"m/4"}, // ㄩㄥˋ 1494

  (const spell PROGMEM) {""},      // End Guard
};





#endif
